// Code generated by go-tdlib codegen. DO NOT EDIT.
package tdapi

// GetArchivedStickerSetsRequest — Returns a list of archived sticker sets
type GetArchivedStickerSetsRequest struct {
	StickerType *StickerType `json:"sticker_type"` // Type of the sticker sets to return
	OffsetStickerSetID JSONInt64 `json:"offset_sticker_set_id"` // Identifier of the sticker set from which to return the result; use 0 to get results from the beginning
	Limit int32 `json:"limit"` // The maximum number of sticker sets to return; up to 100
}

func (r *GetArchivedStickerSetsRequest) GetType() string { return "getArchivedStickerSets" }

// GetTrendingStickerSetsRequest — Returns a list of trending sticker sets. For optimal performance, the number of returned sticker sets is chosen by TDLib
type GetTrendingStickerSetsRequest struct {
	StickerType *StickerType `json:"sticker_type"` // Type of the sticker sets to return
	Offset int32 `json:"offset"` // The offset from which to return the sticker sets; must be non-negative
	Limit int32 `json:"limit"` // The maximum number of sticker sets to be returned; up to 100. For optimal performance, the number of returned sticker sets is chosen by TDLib and can be smaller than the specified limit, even if the end of the list has not been reached
}

func (r *GetTrendingStickerSetsRequest) GetType() string { return "getTrendingStickerSets" }

// GetAttachedStickerSetsRequest — Returns a list of sticker sets attached to a file, including regular, mask, and emoji sticker sets. Currently, only animations, photos, and videos can have attached sticker sets @file_id File identifier
type GetAttachedStickerSetsRequest struct {
	FileID int32 `json:"file_id"`
}

func (r *GetAttachedStickerSetsRequest) GetType() string { return "getAttachedStickerSets" }

// GetStickerSetRequest — Returns information about a sticker set by its identifier @set_id Identifier of the sticker set
type GetStickerSetRequest struct {
	SetID JSONInt64 `json:"set_id"`
}

func (r *GetStickerSetRequest) GetType() string { return "getStickerSet" }

// GetStickerSetNameRequest — Returns name of a sticker set by its identifier @set_id Identifier of the sticker set
type GetStickerSetNameRequest struct {
	SetID JSONInt64 `json:"set_id"`
}

func (r *GetStickerSetNameRequest) GetType() string { return "getStickerSetName" }

// SearchStickerSetRequest — Searches for a sticker set by its name @name Name of the sticker set @ignore_cache Pass true to ignore local cache of sticker sets and always send a network request
type SearchStickerSetRequest struct {
	Name string `json:"name"`
	IgnoreCache bool `json:"ignore_cache"`
}

func (r *SearchStickerSetRequest) GetType() string { return "searchStickerSet" }

// SearchInstalledStickerSetsRequest — Searches for installed sticker sets by looking for specified query in their title and name @sticker_type Type of the sticker sets to search for @query Query to search for @limit The maximum number of sticker sets to return
type SearchInstalledStickerSetsRequest struct {
	StickerType *StickerType `json:"sticker_type"`
	Query string `json:"query"`
	Limit int32 `json:"limit"`
}

func (r *SearchInstalledStickerSetsRequest) GetType() string { return "searchInstalledStickerSets" }

// SearchStickerSetsRequest — Searches for sticker sets by looking for specified query in their title and name. Excludes installed sticker sets from the results
type SearchStickerSetsRequest struct {
	StickerType *StickerType `json:"sticker_type"` // Type of the sticker sets to return
	Query string `json:"query"` // Query to search for
}

func (r *SearchStickerSetsRequest) GetType() string { return "searchStickerSets" }

// ChangeStickerSetRequest — Installs/uninstalls or activates/archives a sticker set @set_id Identifier of the sticker set @is_installed The new value of is_installed @is_archived The new value of is_archived. A sticker set can't be installed and archived simultaneously
type ChangeStickerSetRequest struct {
	SetID JSONInt64 `json:"set_id"`
	IsInstalled bool `json:"is_installed"`
	IsArchived bool `json:"is_archived"`
}

func (r *ChangeStickerSetRequest) GetType() string { return "changeStickerSet" }

// ViewTrendingStickerSetsRequest — Informs the server that some trending sticker sets have been viewed by the user @sticker_set_ids Identifiers of viewed trending sticker sets
type ViewTrendingStickerSetsRequest struct {
	StickerSetIDs []JSONInt64 `json:"sticker_set_ids"`
}

func (r *ViewTrendingStickerSetsRequest) GetType() string { return "viewTrendingStickerSets" }

// ReorderInstalledStickerSetsRequest — Changes the order of installed sticker sets @sticker_type Type of the sticker sets to reorder @sticker_set_ids Identifiers of installed sticker sets in the new correct order
type ReorderInstalledStickerSetsRequest struct {
	StickerType *StickerType `json:"sticker_type"`
	StickerSetIDs []JSONInt64 `json:"sticker_set_ids"`
}

func (r *ReorderInstalledStickerSetsRequest) GetType() string { return "reorderInstalledStickerSets" }

// GetRecentStickersRequest — Returns a list of recently used stickers @is_attached Pass true to return stickers and masks that were recently attached to photos or video files; pass false to return recently sent stickers
type GetRecentStickersRequest struct {
	IsAttached bool `json:"is_attached"`
}

func (r *GetRecentStickersRequest) GetType() string { return "getRecentStickers" }

// AddRecentStickerRequest — Manually adds a new sticker to the list of recently used stickers. The new sticker is added to the top of the list. If the sticker was already in the list, it is removed from the list first.
type AddRecentStickerRequest struct {
	IsAttached bool `json:"is_attached"` // Pass true to add the sticker to the list of stickers recently attached to photo or video files; pass false to add the sticker to the list of recently sent stickers
	Sticker *InputFile `json:"sticker"` // Sticker file to add
}

func (r *AddRecentStickerRequest) GetType() string { return "addRecentSticker" }

// RemoveRecentStickerRequest — Removes a sticker from the list of recently used stickers @is_attached Pass true to remove the sticker from the list of stickers recently attached to photo or video files; pass false to remove the sticker from the list of recently sent stickers @sticker Sticker file to delete
type RemoveRecentStickerRequest struct {
	IsAttached bool `json:"is_attached"`
	Sticker *InputFile `json:"sticker"`
}

func (r *RemoveRecentStickerRequest) GetType() string { return "removeRecentSticker" }

// ClearRecentStickersRequest — Clears the list of recently used stickers @is_attached Pass true to clear the list of stickers recently attached to photo or video files; pass false to clear the list of recently sent stickers
type ClearRecentStickersRequest struct {
	IsAttached bool `json:"is_attached"`
}

func (r *ClearRecentStickersRequest) GetType() string { return "clearRecentStickers" }

// GetFavoriteStickersRequest — Returns favorite stickers
type GetFavoriteStickersRequest struct {
}

func (r *GetFavoriteStickersRequest) GetType() string { return "getFavoriteStickers" }

// AddFavoriteStickerRequest — Adds a new sticker to the list of favorite stickers. The new sticker is added to the top of the list. If the sticker was already in the list, it is removed from the list first.
type AddFavoriteStickerRequest struct {
	Sticker *InputFile `json:"sticker"` // Sticker file to add
}

func (r *AddFavoriteStickerRequest) GetType() string { return "addFavoriteSticker" }

// RemoveFavoriteStickerRequest — Removes a sticker from the list of favorite stickers @sticker Sticker file to delete from the list
type RemoveFavoriteStickerRequest struct {
	Sticker *InputFile `json:"sticker"`
}

func (r *RemoveFavoriteStickerRequest) GetType() string { return "removeFavoriteSticker" }

// GetStickerEmojisRequest — Returns emoji corresponding to a sticker. The list is only for informational purposes, because a sticker is always sent with a fixed emoji from the corresponding Sticker object @sticker Sticker file identifier
type GetStickerEmojisRequest struct {
	Sticker *InputFile `json:"sticker"`
}

func (r *GetStickerEmojisRequest) GetType() string { return "getStickerEmojis" }

// SearchEmojisRequest — Searches for emojis by keywords. Supported only if the file database is enabled. Order of results is unspecified
type SearchEmojisRequest struct {
	Text string `json:"text"` // Text to search for
	InputLanguageCodes []string `json:"input_language_codes"` // List of possible IETF language tags of the user's input language; may be empty if unknown
}

func (r *SearchEmojisRequest) GetType() string { return "searchEmojis" }

// GetKeywordEmojisRequest — Returns emojis matching the keyword. Supported only if the file database is enabled. Order of results is unspecified
type GetKeywordEmojisRequest struct {
	Text string `json:"text"` // Text to search for
	InputLanguageCodes []string `json:"input_language_codes"` // List of possible IETF language tags of the user's input language; may be empty if unknown
}

func (r *GetKeywordEmojisRequest) GetType() string { return "getKeywordEmojis" }

// GetEmojiCategoriesRequest — Returns available emoji categories @type Type of emoji categories to return; pass null to get default emoji categories
type GetEmojiCategoriesRequest struct {
	Type *EmojiCategoryType `json:"type"`
}

func (r *GetEmojiCategoriesRequest) GetType() string { return "getEmojiCategories" }

// GetAnimatedEmojiRequest — Returns an animated emoji corresponding to a given emoji. Returns a 404 error if the emoji has no animated emoji @emoji The emoji
type GetAnimatedEmojiRequest struct {
	Emoji string `json:"emoji"`
}

func (r *GetAnimatedEmojiRequest) GetType() string { return "getAnimatedEmoji" }

// GetEmojiSuggestionsURLRequest — Returns an HTTP URL which can be used to automatically log in to the translation platform and suggest new emoji replacements. The URL will be valid for 30 seconds after generation
type GetEmojiSuggestionsURLRequest struct {
	LanguageCode string `json:"language_code"` // Language code for which the emoji replacements will be suggested
}

func (r *GetEmojiSuggestionsURLRequest) GetType() string { return "getEmojiSuggestionsUrl" }

// GetCustomEmojiStickersRequest — Returns the list of custom emoji stickers by their identifiers. Stickers are returned in arbitrary order. Only found stickers are returned
type GetCustomEmojiStickersRequest struct {
	CustomEmojiIDs []JSONInt64 `json:"custom_emoji_ids"` // Identifiers of custom emoji stickers. At most 200 custom emoji stickers can be received simultaneously
}

func (r *GetCustomEmojiStickersRequest) GetType() string { return "getCustomEmojiStickers" }

// GetDefaultChatPhotoCustomEmojiStickersRequest — Returns default list of custom emoji stickers for placing on a chat photo
type GetDefaultChatPhotoCustomEmojiStickersRequest struct {
}

func (r *GetDefaultChatPhotoCustomEmojiStickersRequest) GetType() string { return "getDefaultChatPhotoCustomEmojiStickers" }

// GetDefaultProfilePhotoCustomEmojiStickersRequest — Returns default list of custom emoji stickers for placing on a profile photo
type GetDefaultProfilePhotoCustomEmojiStickersRequest struct {
}

func (r *GetDefaultProfilePhotoCustomEmojiStickersRequest) GetType() string { return "getDefaultProfilePhotoCustomEmojiStickers" }

// GetDefaultBackgroundCustomEmojiStickersRequest — Returns default list of custom emoji stickers for reply background
type GetDefaultBackgroundCustomEmojiStickersRequest struct {
}

func (r *GetDefaultBackgroundCustomEmojiStickersRequest) GetType() string { return "getDefaultBackgroundCustomEmojiStickers" }

// GetSavedAnimationsRequest — Returns saved animations
type GetSavedAnimationsRequest struct {
}

func (r *GetSavedAnimationsRequest) GetType() string { return "getSavedAnimations" }

// AddSavedAnimationRequest — Manually adds a new animation to the list of saved animations. The new animation is added to the beginning of the list. If the animation was already in the list, it is removed first.
type AddSavedAnimationRequest struct {
	Animation *InputFile `json:"animation"` // The animation file to be added. Only animations known to the server (i.e., successfully sent via a message) can be added to the list
}

func (r *AddSavedAnimationRequest) GetType() string { return "addSavedAnimation" }

// RemoveSavedAnimationRequest — Removes an animation from the list of saved animations @animation Animation file to be removed
type RemoveSavedAnimationRequest struct {
	Animation *InputFile `json:"animation"`
}

func (r *RemoveSavedAnimationRequest) GetType() string { return "removeSavedAnimation" }

// GetRecentInlineBotsRequest — Returns up to 20 recently used inline bots in the order of their last usage
type GetRecentInlineBotsRequest struct {
}

func (r *GetRecentInlineBotsRequest) GetType() string { return "getRecentInlineBots" }

// GetOwnedBotsRequest — Returns the list of bots owned by the current user
type GetOwnedBotsRequest struct {
}

func (r *GetOwnedBotsRequest) GetType() string { return "getOwnedBots" }

// SearchHashtagsRequest — Searches for recently used hashtags by their prefix @prefix Hashtag prefix to search for @limit The maximum number of hashtags to be returned
type SearchHashtagsRequest struct {
	Prefix string `json:"prefix"`
	Limit int32 `json:"limit"`
}

func (r *SearchHashtagsRequest) GetType() string { return "searchHashtags" }

// RemoveRecentHashtagRequest — Removes a hashtag from the list of recently used hashtags @hashtag Hashtag to delete
type RemoveRecentHashtagRequest struct {
	Hashtag string `json:"hashtag"`
}

func (r *RemoveRecentHashtagRequest) GetType() string { return "removeRecentHashtag" }

// GetLinkPreviewRequest — Returns a link preview by the text of a message. Do not call this function too often. Returns a 404 error if the text has no link preview
type GetLinkPreviewRequest struct {
	Text *FormattedText `json:"text"` // Message text with formatting
	LinkPreviewOptions *LinkPreviewOptions `json:"link_preview_options"` // Options to be used for generation of the link preview; pass null to use default link preview options
}

func (r *GetLinkPreviewRequest) GetType() string { return "getLinkPreview" }

// GetWebPageInstantViewRequest — Returns an instant view version of a web page if available. This is an offline method if only_local is true. Returns a 404 error if the web page has no instant view page
type GetWebPageInstantViewRequest struct {
	URL string `json:"url"` // The web page URL
	OnlyLocal bool `json:"only_local"` // Pass true to get only locally available information without sending network requests
}

func (r *GetWebPageInstantViewRequest) GetType() string { return "getWebPageInstantView" }

// SetProfilePhotoRequest — Changes a profile photo for the current user
type SetProfilePhotoRequest struct {
	Photo *InputChatPhoto `json:"photo"` // Profile photo to set
	IsPublic bool `json:"is_public"` // Pass true to set the public photo, which will be visible even if the main photo is hidden by privacy settings
}

func (r *SetProfilePhotoRequest) GetType() string { return "setProfilePhoto" }

// DeleteProfilePhotoRequest — Deletes a profile photo @profile_photo_id Identifier of the profile photo to delete
type DeleteProfilePhotoRequest struct {
	ProfilePhotoID JSONInt64 `json:"profile_photo_id"`
}

func (r *DeleteProfilePhotoRequest) GetType() string { return "deleteProfilePhoto" }

// SetAccentColorRequest — Changes accent color and background custom emoji for the current user; for Telegram Premium users only
type SetAccentColorRequest struct {
	AccentColorID int32 `json:"accent_color_id"` // Identifier of the accent color to use
	BackgroundCustomEmojiID JSONInt64 `json:"background_custom_emoji_id"` // Identifier of a custom emoji to be shown on the reply header and link preview background; 0 if none
}

func (r *SetAccentColorRequest) GetType() string { return "setAccentColor" }

// SetUpgradedGiftColorsRequest — Changes color scheme for the current user based on an owned or a hosted upgraded gift; for Telegram Premium users only
type SetUpgradedGiftColorsRequest struct {
	UpgradedGiftColorsID JSONInt64 `json:"upgraded_gift_colors_id"` // Identifier of the upgradedGiftColors scheme to use
}

func (r *SetUpgradedGiftColorsRequest) GetType() string { return "setUpgradedGiftColors" }

// SetProfileAccentColorRequest — Changes accent color and background custom emoji for profile of the current user; for Telegram Premium users only
type SetProfileAccentColorRequest struct {
	ProfileAccentColorID int32 `json:"profile_accent_color_id"` // Identifier of the accent color to use for profile; pass -1 if none
	ProfileBackgroundCustomEmojiID JSONInt64 `json:"profile_background_custom_emoji_id"` // Identifier of a custom emoji to be shown on the user's profile photo background; 0 if none
}

func (r *SetProfileAccentColorRequest) GetType() string { return "setProfileAccentColor" }

// SetNameRequest — Changes the first and last name of the current user @first_name The new value of the first name for the current user; 1-64 characters @last_name The new value of the optional last name for the current user; 0-64 characters
type SetNameRequest struct {
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
}

func (r *SetNameRequest) GetType() string { return "setName" }

// SetBioRequest — Changes the bio of the current user @bio The new value of the user bio; 0-getOption("bio_length_max") characters without line feeds
type SetBioRequest struct {
	Bio string `json:"bio"`
}

func (r *SetBioRequest) GetType() string { return "setBio" }

// SetUsernameRequest — Changes the editable username of the current user
type SetUsernameRequest struct {
	Username string `json:"username"` // The new value of the username. Use an empty string to remove the username. The username can't be completely removed if there is another active or disabled username
}

func (r *SetUsernameRequest) GetType() string { return "setUsername" }

// ToggleUsernameIsActiveRequest — Changes active state for a username of the current user. The editable username can't be disabled. May return an error with a message "USERNAMES_ACTIVE_TOO_MUCH" if the maximum number of active usernames has been reached
type ToggleUsernameIsActiveRequest struct {
	Username string `json:"username"` // The username to change
	IsActive bool `json:"is_active"` // Pass true to activate the username; pass false to disable it
}

func (r *ToggleUsernameIsActiveRequest) GetType() string { return "toggleUsernameIsActive" }

// ReorderActiveUsernamesRequest — Changes order of active usernames of the current user @usernames The new order of active usernames. All currently active usernames must be specified
type ReorderActiveUsernamesRequest struct {
	Usernames []string `json:"usernames"`
}

func (r *ReorderActiveUsernamesRequest) GetType() string { return "reorderActiveUsernames" }

// SetBirthdateRequest — Changes the birthdate of the current user @birthdate The new value of the current user's birthdate; pass null to remove the birthdate
type SetBirthdateRequest struct {
	Birthdate *Birthdate `json:"birthdate"`
}

func (r *SetBirthdateRequest) GetType() string { return "setBirthdate" }

// SetMainProfileTabRequest — Changes the main profile tab of the current user @main_profile_tab The new value of the main profile tab
type SetMainProfileTabRequest struct {
	MainProfileTab *ProfileTab `json:"main_profile_tab"`
}

func (r *SetMainProfileTabRequest) GetType() string { return "setMainProfileTab" }

// SetPersonalChatRequest — Changes the personal chat of the current user @chat_id Identifier of the new personal chat; pass 0 to remove the chat. Use getSuitablePersonalChats to get suitable chats
type SetPersonalChatRequest struct {
	ChatID int64 `json:"chat_id"`
}

func (r *SetPersonalChatRequest) GetType() string { return "setPersonalChat" }

// SetEmojiStatusRequest — Changes the emoji status of the current user; for Telegram Premium users only @emoji_status New emoji status; pass null to switch to the default badge
type SetEmojiStatusRequest struct {
	EmojiStatus *EmojiStatus `json:"emoji_status"`
}

func (r *SetEmojiStatusRequest) GetType() string { return "setEmojiStatus" }

// ToggleHasSponsoredMessagesEnabledRequest — Toggles whether the current user has sponsored messages enabled. The setting has no effect for users without Telegram Premium for which sponsored messages are always enabled
type ToggleHasSponsoredMessagesEnabledRequest struct {
	HasSponsoredMessagesEnabled bool `json:"has_sponsored_messages_enabled"` // Pass true to enable sponsored messages for the current user; false to disable them
}

func (r *ToggleHasSponsoredMessagesEnabledRequest) GetType() string { return "toggleHasSponsoredMessagesEnabled" }

// SetBusinessLocationRequest — Changes the business location of the current user. Requires Telegram Business subscription @location The new location of the business; pass null to remove the location
type SetBusinessLocationRequest struct {
	Location *BusinessLocation `json:"location"`
}

func (r *SetBusinessLocationRequest) GetType() string { return "setBusinessLocation" }

// SetBusinessOpeningHoursRequest — Changes the business opening hours of the current user. Requires Telegram Business subscription
type SetBusinessOpeningHoursRequest struct {
	OpeningHours *BusinessOpeningHours `json:"opening_hours"` // The new opening hours of the business; pass null to remove the opening hours; up to 28 time intervals can be specified
}

func (r *SetBusinessOpeningHoursRequest) GetType() string { return "setBusinessOpeningHours" }

// SetBusinessGreetingMessageSettingsRequest — Changes the business greeting message settings of the current user. Requires Telegram Business subscription @greeting_message_settings The new settings for the greeting message of the business; pass null to disable the greeting message
type SetBusinessGreetingMessageSettingsRequest struct {
	GreetingMessageSettings *BusinessGreetingMessageSettings `json:"greeting_message_settings"`
}

func (r *SetBusinessGreetingMessageSettingsRequest) GetType() string { return "setBusinessGreetingMessageSettings" }

// SetBusinessAwayMessageSettingsRequest — Changes the business away message settings of the current user. Requires Telegram Business subscription @away_message_settings The new settings for the away message of the business; pass null to disable the away message
type SetBusinessAwayMessageSettingsRequest struct {
	AwayMessageSettings *BusinessAwayMessageSettings `json:"away_message_settings"`
}

func (r *SetBusinessAwayMessageSettingsRequest) GetType() string { return "setBusinessAwayMessageSettings" }

// SetBusinessStartPageRequest — Changes the business start page of the current user. Requires Telegram Business subscription @start_page The new start page of the business; pass null to remove custom start page
type SetBusinessStartPageRequest struct {
	StartPage *InputBusinessStartPage `json:"start_page"`
}

func (r *SetBusinessStartPageRequest) GetType() string { return "setBusinessStartPage" }

// SendPhoneNumberCodeRequest — Sends a code to the specified phone number. Aborts previous phone number verification if there was one. On success, returns information about the sent code
type SendPhoneNumberCodeRequest struct {
	PhoneNumber string `json:"phone_number"` // The phone number, in international format
	Settings *PhoneNumberAuthenticationSettings `json:"settings"` // Settings for the authentication of the user's phone number; pass null to use default settings
	Type *PhoneNumberCodeType `json:"type"` // Type of the request for which the code is sent
}

func (r *SendPhoneNumberCodeRequest) GetType() string { return "sendPhoneNumberCode" }

// SendPhoneNumberFirebaseSmsRequest — Sends Firebase Authentication SMS to the specified phone number. Works only when received a code of the type authenticationCodeTypeFirebaseAndroid or authenticationCodeTypeFirebaseIos
type SendPhoneNumberFirebaseSmsRequest struct {
	Token string `json:"token"` // Play Integrity API or SafetyNet Attestation API token for the Android application, or secret from push notification for the iOS application
}

func (r *SendPhoneNumberFirebaseSmsRequest) GetType() string { return "sendPhoneNumberFirebaseSms" }

// ReportPhoneNumberCodeMissingRequest — Reports that authentication code wasn't delivered via SMS to the specified phone number; for official mobile applications only @mobile_network_code Current mobile network code
type ReportPhoneNumberCodeMissingRequest struct {
	MobileNetworkCode string `json:"mobile_network_code"`
}

func (r *ReportPhoneNumberCodeMissingRequest) GetType() string { return "reportPhoneNumberCodeMissing" }

// ResendPhoneNumberCodeRequest — Resends the authentication code sent to a phone number. Works only if the previously received authenticationCodeInfo next_code_type was not null and the server-specified timeout has passed
type ResendPhoneNumberCodeRequest struct {
	Reason *ResendCodeReason `json:"reason"` // Reason of code resending; pass null if unknown
}

func (r *ResendPhoneNumberCodeRequest) GetType() string { return "resendPhoneNumberCode" }

// CheckPhoneNumberCodeRequest — Checks the authentication code and completes the request for which the code was sent if appropriate @code Authentication code to check
type CheckPhoneNumberCodeRequest struct {
	Code string `json:"code"`
}

func (r *CheckPhoneNumberCodeRequest) GetType() string { return "checkPhoneNumberCode" }

// GetBusinessConnectedBotRequest — Returns the business bot that is connected to the current user account. Returns a 404 error if there is no connected bot
type GetBusinessConnectedBotRequest struct {
}

func (r *GetBusinessConnectedBotRequest) GetType() string { return "getBusinessConnectedBot" }

// SetBusinessConnectedBotRequest — Adds or changes business bot that is connected to the current user account @bot Connection settings for the bot
type SetBusinessConnectedBotRequest struct {
	Bot *BusinessConnectedBot `json:"bot"`
}

func (r *SetBusinessConnectedBotRequest) GetType() string { return "setBusinessConnectedBot" }

// DeleteBusinessConnectedBotRequest — Deletes the business bot that is connected to the current user account @bot_user_id Unique user identifier for the bot
type DeleteBusinessConnectedBotRequest struct {
	BotUserID int64 `json:"bot_user_id"`
}

func (r *DeleteBusinessConnectedBotRequest) GetType() string { return "deleteBusinessConnectedBot" }

// ToggleBusinessConnectedBotChatIsPausedRequest — Pauses or resumes the connected business bot in a specific chat @chat_id Chat identifier @is_paused Pass true to pause the connected bot in the chat; pass false to resume the bot
type ToggleBusinessConnectedBotChatIsPausedRequest struct {
	ChatID int64 `json:"chat_id"`
	IsPaused bool `json:"is_paused"`
}

func (r *ToggleBusinessConnectedBotChatIsPausedRequest) GetType() string { return "toggleBusinessConnectedBotChatIsPaused" }

// RemoveBusinessConnectedBotFromChatRequest — Removes the connected business bot from a specific chat by adding the chat to businessRecipients.excluded_chat_ids @chat_id Chat identifier
type RemoveBusinessConnectedBotFromChatRequest struct {
	ChatID int64 `json:"chat_id"`
}

func (r *RemoveBusinessConnectedBotFromChatRequest) GetType() string { return "removeBusinessConnectedBotFromChat" }

// GetBusinessChatLinksRequest — Returns business chat links created for the current account
type GetBusinessChatLinksRequest struct {
}

func (r *GetBusinessChatLinksRequest) GetType() string { return "getBusinessChatLinks" }

// CreateBusinessChatLinkRequest — Creates a business chat link for the current account. Requires Telegram Business subscription. There can be up to getOption("business_chat_link_count_max") links created. Returns the created link
type CreateBusinessChatLinkRequest struct {
	LinkInfo *InputBusinessChatLink `json:"link_info"` // Information about the link to create
}

func (r *CreateBusinessChatLinkRequest) GetType() string { return "createBusinessChatLink" }

// EditBusinessChatLinkRequest — Edits a business chat link of the current account. Requires Telegram Business subscription. Returns the edited link
type EditBusinessChatLinkRequest struct {
	Link string `json:"link"` // The link to edit
	LinkInfo *InputBusinessChatLink `json:"link_info"` // New description of the link
}

func (r *EditBusinessChatLinkRequest) GetType() string { return "editBusinessChatLink" }

// DeleteBusinessChatLinkRequest — Deletes a business chat link of the current account @link The link to delete
type DeleteBusinessChatLinkRequest struct {
	Link string `json:"link"`
}

func (r *DeleteBusinessChatLinkRequest) GetType() string { return "deleteBusinessChatLink" }

// GetBusinessChatLinkInfoRequest — Returns information about a business chat link @link_name Name of the link
type GetBusinessChatLinkInfoRequest struct {
	LinkName string `json:"link_name"`
}

func (r *GetBusinessChatLinkInfoRequest) GetType() string { return "getBusinessChatLinkInfo" }

// GetUserLinkRequest — Returns an HTTPS link, which can be used to get information about the current user
type GetUserLinkRequest struct {
}

func (r *GetUserLinkRequest) GetType() string { return "getUserLink" }

// SearchUserByTokenRequest — Searches a user by a token from the user's link @token Token to search for
type SearchUserByTokenRequest struct {
	Token string `json:"token"`
}

func (r *SearchUserByTokenRequest) GetType() string { return "searchUserByToken" }

// SetCommandsRequest — Sets the list of commands supported by the bot for the given user scope and language; for bots only
type SetCommandsRequest struct {
	Scope *BotCommandScope `json:"scope"` // The scope to which the commands are relevant; pass null to change commands in the default bot command scope
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code. If empty, the commands will be applied to all users from the given scope, for which language there are no dedicated commands
	Commands []*BotCommand `json:"commands"` // List of the bot's commands
}

func (r *SetCommandsRequest) GetType() string { return "setCommands" }

// DeleteCommandsRequest — Deletes commands supported by the bot for the given user scope and language; for bots only
type DeleteCommandsRequest struct {
	Scope *BotCommandScope `json:"scope"` // The scope to which the commands are relevant; pass null to delete commands in the default bot command scope
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code or an empty string
}

func (r *DeleteCommandsRequest) GetType() string { return "deleteCommands" }

// GetCommandsRequest — Returns the list of commands supported by the bot for the given user scope and language; for bots only
type GetCommandsRequest struct {
	Scope *BotCommandScope `json:"scope"` // The scope to which the commands are relevant; pass null to get commands in the default bot command scope
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code or an empty string
}

func (r *GetCommandsRequest) GetType() string { return "getCommands" }

// SetMenuButtonRequest — Sets menu button for the given user or for all users; for bots only
type SetMenuButtonRequest struct {
	UserID int64 `json:"user_id"` // Identifier of the user or 0 to set menu button for all users
	MenuButton *BotMenuButton `json:"menu_button"` // New menu button
}

func (r *SetMenuButtonRequest) GetType() string { return "setMenuButton" }

// GetMenuButtonRequest — Returns menu button set by the bot for the given user; for bots only @user_id Identifier of the user or 0 to get the default menu button
type GetMenuButtonRequest struct {
	UserID int64 `json:"user_id"`
}

func (r *GetMenuButtonRequest) GetType() string { return "getMenuButton" }

// SetDefaultGroupAdministratorRightsRequest — Sets default administrator rights for adding the bot to basic group and supergroup chats; for bots only @default_group_administrator_rights Default administrator rights for adding the bot to basic group and supergroup chats; pass null to remove default rights
type SetDefaultGroupAdministratorRightsRequest struct {
	DefaultGroupAdministratorRights *ChatAdministratorRights `json:"default_group_administrator_rights"`
}

func (r *SetDefaultGroupAdministratorRightsRequest) GetType() string { return "setDefaultGroupAdministratorRights" }

// SetDefaultChannelAdministratorRightsRequest — Sets default administrator rights for adding the bot to channel chats; for bots only @default_channel_administrator_rights Default administrator rights for adding the bot to channels; pass null to remove default rights
type SetDefaultChannelAdministratorRightsRequest struct {
	DefaultChannelAdministratorRights *ChatAdministratorRights `json:"default_channel_administrator_rights"`
}

func (r *SetDefaultChannelAdministratorRightsRequest) GetType() string { return "setDefaultChannelAdministratorRights" }

// CanBotSendMessagesRequest — Checks whether the specified bot can send messages to the user. Returns a 404 error if can't and the access can be granted by call to allowBotToSendMessages @bot_user_id Identifier of the target bot
type CanBotSendMessagesRequest struct {
	BotUserID int64 `json:"bot_user_id"`
}

func (r *CanBotSendMessagesRequest) GetType() string { return "canBotSendMessages" }

// AllowBotToSendMessagesRequest — Allows the specified bot to send messages to the user @bot_user_id Identifier of the target bot
type AllowBotToSendMessagesRequest struct {
	BotUserID int64 `json:"bot_user_id"`
}

func (r *AllowBotToSendMessagesRequest) GetType() string { return "allowBotToSendMessages" }

// SendWebAppCustomRequestRequest — Sends a custom request from a Web App
type SendWebAppCustomRequestRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the bot
	Method string `json:"method"` // The method name
	Parameters string `json:"parameters"` // JSON-serialized method parameters
}

func (r *SendWebAppCustomRequestRequest) GetType() string { return "sendWebAppCustomRequest" }

// GetBotMediaPreviewsRequest — Returns the list of media previews of a bot @bot_user_id Identifier of the target bot. The bot must have the main Web App
type GetBotMediaPreviewsRequest struct {
	BotUserID int64 `json:"bot_user_id"`
}

func (r *GetBotMediaPreviewsRequest) GetType() string { return "getBotMediaPreviews" }

// GetBotMediaPreviewInfoRequest — Returns the list of media previews for the given language and the list of languages for which the bot has dedicated previews
type GetBotMediaPreviewInfoRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot. The bot must be owned and must have the main Web App
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code for which to get previews. If empty, then default previews are returned
}

func (r *GetBotMediaPreviewInfoRequest) GetType() string { return "getBotMediaPreviewInfo" }

// AddBotMediaPreviewRequest — Adds a new media preview to the beginning of the list of media previews of a bot. Returns the added preview after addition is completed server-side. The total number of previews must not exceed getOption("bot_media_preview_count_max") for the given language
type AddBotMediaPreviewRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot. The bot must be owned and must have the main Web App
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code for which preview is added. If empty, then the preview will be shown to all users for whose languages there are no dedicated previews.
	Content *InputStoryContent `json:"content"` // Content of the added preview
}

func (r *AddBotMediaPreviewRequest) GetType() string { return "addBotMediaPreview" }

// EditBotMediaPreviewRequest — Replaces media preview in the list of media previews of a bot. Returns the new preview after edit is completed server-side
type EditBotMediaPreviewRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot. The bot must be owned and must have the main Web App
	LanguageCode string `json:"language_code"` // Language code of the media preview to edit
	FileID int32 `json:"file_id"` // File identifier of the media to replace
	Content *InputStoryContent `json:"content"` // Content of the new preview
}

func (r *EditBotMediaPreviewRequest) GetType() string { return "editBotMediaPreview" }

// ReorderBotMediaPreviewsRequest — Changes order of media previews in the list of media previews of a bot
type ReorderBotMediaPreviewsRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot. The bot must be owned and must have the main Web App
	LanguageCode string `json:"language_code"` // Language code of the media previews to reorder
	FileIDs []int32 `json:"file_ids"` // File identifiers of the media in the new order
}

func (r *ReorderBotMediaPreviewsRequest) GetType() string { return "reorderBotMediaPreviews" }

// DeleteBotMediaPreviewsRequest — Deletes media previews from the list of media previews of a bot
type DeleteBotMediaPreviewsRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot. The bot must be owned and must have the main Web App
	LanguageCode string `json:"language_code"` // Language code of the media previews to delete
	FileIDs []int32 `json:"file_ids"` // File identifiers of the media to delete
}

func (r *DeleteBotMediaPreviewsRequest) GetType() string { return "deleteBotMediaPreviews" }

// SetBotNameRequest — Sets the name of a bot. Can be called only if userTypeBot.can_be_edited == true
type SetBotNameRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code. If empty, the name will be shown to all users for whose languages there is no dedicated name
	Name string `json:"name"` // New bot's name on the specified language; 0-64 characters; must be non-empty if language code is empty
}

func (r *SetBotNameRequest) GetType() string { return "setBotName" }

// GetBotNameRequest — Returns the name of a bot in the given language. Can be called only if userTypeBot.can_be_edited == true
type GetBotNameRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code or an empty string
}

func (r *GetBotNameRequest) GetType() string { return "getBotName" }

// SetBotProfilePhotoRequest — Changes a profile photo for a bot @bot_user_id Identifier of the target bot @photo Profile photo to set; pass null to delete the chat photo
type SetBotProfilePhotoRequest struct {
	BotUserID int64 `json:"bot_user_id"`
	Photo *InputChatPhoto `json:"photo"`
}

func (r *SetBotProfilePhotoRequest) GetType() string { return "setBotProfilePhoto" }

// ToggleBotUsernameIsActiveRequest — Changes active state for a username of a bot. The editable username can be disabled only if there are other active usernames.
type ToggleBotUsernameIsActiveRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	Username string `json:"username"` // The username to change
	IsActive bool `json:"is_active"` // Pass true to activate the username; pass false to disable it
}

func (r *ToggleBotUsernameIsActiveRequest) GetType() string { return "toggleBotUsernameIsActive" }

// ReorderBotActiveUsernamesRequest — Changes order of active usernames of a bot. Can be called only if userTypeBot.can_be_edited == true @bot_user_id Identifier of the target bot @usernames The new order of active usernames. All currently active usernames must be specified
type ReorderBotActiveUsernamesRequest struct {
	BotUserID int64 `json:"bot_user_id"`
	Usernames []string `json:"usernames"`
}

func (r *ReorderBotActiveUsernamesRequest) GetType() string { return "reorderBotActiveUsernames" }

// SetBotInfoDescriptionRequest — Sets the text shown in the chat with a bot if the chat is empty. Can be called only if userTypeBot.can_be_edited == true
type SetBotInfoDescriptionRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code. If empty, the description will be shown to all users for whose languages there is no dedicated description
	Description string `json:"description"` // Sets the text shown in the chat with a bot if the chat is empty. Can be called only if userTypeBot.can_be_edited == true
}

func (r *SetBotInfoDescriptionRequest) GetType() string { return "setBotInfoDescription" }

// GetBotInfoDescriptionRequest — Returns the text shown in the chat with a bot if the chat is empty in the given language. Can be called only if userTypeBot.can_be_edited == true
type GetBotInfoDescriptionRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code or an empty string
}

func (r *GetBotInfoDescriptionRequest) GetType() string { return "getBotInfoDescription" }

// SetBotInfoShortDescriptionRequest — Sets the text shown on a bot's profile page and sent together with the link when users share the bot. Can be called only if userTypeBot.can_be_edited == true
type SetBotInfoShortDescriptionRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code. If empty, the short description will be shown to all users for whose languages there is no dedicated description
	ShortDescription string `json:"short_description"` // New bot's short description on the specified language
}

func (r *SetBotInfoShortDescriptionRequest) GetType() string { return "setBotInfoShortDescription" }

// GetBotInfoShortDescriptionRequest — Returns the text shown on a bot's profile page and sent together with the link when users share the bot in the given language. Can be called only if userTypeBot.can_be_edited == true
type GetBotInfoShortDescriptionRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the target bot
	LanguageCode string `json:"language_code"` // A two-letter ISO 639-1 language code or an empty string
}

func (r *GetBotInfoShortDescriptionRequest) GetType() string { return "getBotInfoShortDescription" }

// SetMessageSenderBotVerificationRequest — Changes the verification status of a user or a chat by an owned bot
type SetMessageSenderBotVerificationRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the owned bot, which will verify the user or the chat
	VerifiedID *MessageSender `json:"verified_id"` // Identifier of the user or the supergroup or channel chat, which will be verified by the bot
	CustomDescription string `json:"custom_description"` // Custom description of verification reason; 0-getOption("bot_verification_custom_description_length_max").
}

func (r *SetMessageSenderBotVerificationRequest) GetType() string { return "setMessageSenderBotVerification" }

// RemoveMessageSenderBotVerificationRequest — Removes the verification status of a user or a chat by an owned bot
type RemoveMessageSenderBotVerificationRequest struct {
	BotUserID int64 `json:"bot_user_id"` // Identifier of the owned bot, which verified the user or the chat
	VerifiedID *MessageSender `json:"verified_id"` // Identifier of the user or the supergroup or channel chat, which verification is removed
}

func (r *RemoveMessageSenderBotVerificationRequest) GetType() string { return "removeMessageSenderBotVerification" }

// GetActiveSessionsRequest — Returns all active sessions of the current user
type GetActiveSessionsRequest struct {
}

func (r *GetActiveSessionsRequest) GetType() string { return "getActiveSessions" }

// TerminateSessionRequest — Terminates a session of the current user @session_id Session identifier
type TerminateSessionRequest struct {
	SessionID JSONInt64 `json:"session_id"`
}

func (r *TerminateSessionRequest) GetType() string { return "terminateSession" }

// TerminateAllOtherSessionsRequest — Terminates all other sessions of the current user
type TerminateAllOtherSessionsRequest struct {
}

func (r *TerminateAllOtherSessionsRequest) GetType() string { return "terminateAllOtherSessions" }

// ConfirmSessionRequest — Confirms an unconfirmed session of the current user from another device @session_id Session identifier
type ConfirmSessionRequest struct {
	SessionID JSONInt64 `json:"session_id"`
}

func (r *ConfirmSessionRequest) GetType() string { return "confirmSession" }

// ToggleSessionCanAcceptCallsRequest — Toggles whether a session can accept incoming calls @session_id Session identifier @can_accept_calls Pass true to allow accepting incoming calls by the session; pass false otherwise
type ToggleSessionCanAcceptCallsRequest struct {
	SessionID JSONInt64 `json:"session_id"`
	CanAcceptCalls bool `json:"can_accept_calls"`
}

func (r *ToggleSessionCanAcceptCallsRequest) GetType() string { return "toggleSessionCanAcceptCalls" }

// ToggleSessionCanAcceptSecretChatsRequest — Toggles whether a session can accept incoming secret chats @session_id Session identifier @can_accept_secret_chats Pass true to allow accepting secret chats by the session; pass false otherwise
type ToggleSessionCanAcceptSecretChatsRequest struct {
	SessionID JSONInt64 `json:"session_id"`
	CanAcceptSecretChats bool `json:"can_accept_secret_chats"`
}

func (r *ToggleSessionCanAcceptSecretChatsRequest) GetType() string { return "toggleSessionCanAcceptSecretChats" }

// SetInactiveSessionTtlRequest — Changes the period of inactivity after which sessions will automatically be terminated @inactive_session_ttl_days New number of days of inactivity before sessions will be automatically terminated; 1-366 days
type SetInactiveSessionTtlRequest struct {
	InactiveSessionTtlDays int32 `json:"inactive_session_ttl_days"`
}

func (r *SetInactiveSessionTtlRequest) GetType() string { return "setInactiveSessionTtl" }

// GetConnectedWebsitesRequest — Returns all website where the current user used Telegram to log in
type GetConnectedWebsitesRequest struct {
}

func (r *GetConnectedWebsitesRequest) GetType() string { return "getConnectedWebsites" }

// DisconnectWebsiteRequest — Disconnects website from the current user's Telegram account @website_id Website identifier
type DisconnectWebsiteRequest struct {
	WebsiteID JSONInt64 `json:"website_id"`
}

func (r *DisconnectWebsiteRequest) GetType() string { return "disconnectWebsite" }

// DisconnectAllWebsitesRequest — Disconnects all websites from the current user's Telegram account
type DisconnectAllWebsitesRequest struct {
}

func (r *DisconnectAllWebsitesRequest) GetType() string { return "disconnectAllWebsites" }

// SetSupergroupUsernameRequest — Changes the editable username of a supergroup or channel, requires owner privileges in the supergroup or channel
type SetSupergroupUsernameRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup or channel
	Username string `json:"username"` // New value of the username. Use an empty string to remove the username. The username can't be completely removed if there is another active or disabled username
}

func (r *SetSupergroupUsernameRequest) GetType() string { return "setSupergroupUsername" }

// ToggleSupergroupUsernameIsActiveRequest — Changes active state for a username of a supergroup or channel, requires owner privileges in the supergroup or channel. The editable username can't be disabled.
type ToggleSupergroupUsernameIsActiveRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup or channel
	Username string `json:"username"` // The username to change
	IsActive bool `json:"is_active"` // Pass true to activate the username; pass false to disable it
}

func (r *ToggleSupergroupUsernameIsActiveRequest) GetType() string { return "toggleSupergroupUsernameIsActive" }

// DisableAllSupergroupUsernamesRequest — Disables all active non-editable usernames of a supergroup or channel, requires owner privileges in the supergroup or channel @supergroup_id Identifier of the supergroup or channel
type DisableAllSupergroupUsernamesRequest struct {
	SupergroupID int64 `json:"supergroup_id"`
}

func (r *DisableAllSupergroupUsernamesRequest) GetType() string { return "disableAllSupergroupUsernames" }

// ReorderSupergroupActiveUsernamesRequest — Changes order of active usernames of a supergroup or channel, requires owner privileges in the supergroup or channel
type ReorderSupergroupActiveUsernamesRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup or channel
	Usernames []string `json:"usernames"` // The new order of active usernames. All currently active usernames must be specified
}

func (r *ReorderSupergroupActiveUsernamesRequest) GetType() string { return "reorderSupergroupActiveUsernames" }

// SetSupergroupStickerSetRequest — Changes the sticker set of a supergroup; requires can_change_info administrator right @supergroup_id Identifier of the supergroup @sticker_set_id New value of the supergroup sticker set identifier. Use 0 to remove the supergroup sticker set
type SetSupergroupStickerSetRequest struct {
	SupergroupID int64 `json:"supergroup_id"`
	StickerSetID JSONInt64 `json:"sticker_set_id"`
}

func (r *SetSupergroupStickerSetRequest) GetType() string { return "setSupergroupStickerSet" }

// SetSupergroupCustomEmojiStickerSetRequest — Changes the custom emoji sticker set of a supergroup; requires can_change_info administrator right. The chat must have at least chatBoostFeatures.min_custom_emoji_sticker_set_boost_level boost level to pass the corresponding color
type SetSupergroupCustomEmojiStickerSetRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup
	CustomEmojiStickerSetID JSONInt64 `json:"custom_emoji_sticker_set_id"` // New value of the custom emoji sticker set identifier for the supergroup. Use 0 to remove the custom emoji sticker set in the supergroup
}

func (r *SetSupergroupCustomEmojiStickerSetRequest) GetType() string { return "setSupergroupCustomEmojiStickerSet" }

// SetSupergroupUnrestrictBoostCountRequest — Changes the number of times the supergroup must be boosted by a user to ignore slow mode and chat permission restrictions; requires can_restrict_members administrator right
type SetSupergroupUnrestrictBoostCountRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup
	UnrestrictBoostCount int32 `json:"unrestrict_boost_count"` // New value of the unrestrict_boost_count supergroup setting; 0-8. Use 0 to remove the setting
}

func (r *SetSupergroupUnrestrictBoostCountRequest) GetType() string { return "setSupergroupUnrestrictBoostCount" }

// SetSupergroupMainProfileTabRequest — Changes the main profile tab of the channel; requires can_change_info administrator right
type SetSupergroupMainProfileTabRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the channel
	MainProfileTab *ProfileTab `json:"main_profile_tab"` // The new value of the main profile tab
}

func (r *SetSupergroupMainProfileTabRequest) GetType() string { return "setSupergroupMainProfileTab" }

// ToggleSupergroupSignMessagesRequest — Toggles whether sender signature or link to the account is added to sent messages in a channel; requires can_change_info member right
type ToggleSupergroupSignMessagesRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the channel
	SignMessages bool `json:"sign_messages"` // New value of sign_messages
	ShowMessageSender bool `json:"show_message_sender"` // New value of show_message_sender
}

func (r *ToggleSupergroupSignMessagesRequest) GetType() string { return "toggleSupergroupSignMessages" }

// ToggleSupergroupJoinToSendMessagesRequest — Toggles whether joining is mandatory to send messages to a discussion supergroup; requires can_restrict_members administrator right
type ToggleSupergroupJoinToSendMessagesRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup that isn't a broadcast group
	JoinToSendMessages bool `json:"join_to_send_messages"` // New value of join_to_send_messages
}

func (r *ToggleSupergroupJoinToSendMessagesRequest) GetType() string { return "toggleSupergroupJoinToSendMessages" }

// ToggleSupergroupJoinByRequestRequest — Toggles whether all users directly joining the supergroup need to be approved by supergroup administrators; requires can_restrict_members administrator right
type ToggleSupergroupJoinByRequestRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup that isn't a broadcast group and isn't a channel direct message group
	JoinByRequest bool `json:"join_by_request"` // New value of join_by_request
}

func (r *ToggleSupergroupJoinByRequestRequest) GetType() string { return "toggleSupergroupJoinByRequest" }

// ToggleSupergroupIsAllHistoryAvailableRequest — Toggles whether the message history of a supergroup is available to new members; requires can_change_info member right @supergroup_id The identifier of the supergroup @is_all_history_available The new value of is_all_history_available
type ToggleSupergroupIsAllHistoryAvailableRequest struct {
	SupergroupID int64 `json:"supergroup_id"`
	IsAllHistoryAvailable bool `json:"is_all_history_available"`
}

func (r *ToggleSupergroupIsAllHistoryAvailableRequest) GetType() string { return "toggleSupergroupIsAllHistoryAvailable" }

// ToggleSupergroupCanHaveSponsoredMessagesRequest — Toggles whether sponsored messages are shown in the channel chat; requires owner privileges in the channel. The chat must have at least chatBoostFeatures.min_sponsored_message_disable_boost_level boost level to disable sponsored messages
type ToggleSupergroupCanHaveSponsoredMessagesRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // The identifier of the channel
	CanHaveSponsoredMessages bool `json:"can_have_sponsored_messages"` // The new value of can_have_sponsored_messages
}

func (r *ToggleSupergroupCanHaveSponsoredMessagesRequest) GetType() string { return "toggleSupergroupCanHaveSponsoredMessages" }

// ToggleSupergroupHasAutomaticTranslationRequest — Toggles whether messages are automatically translated in the channel chat; requires can_change_info administrator right in the channel.
type ToggleSupergroupHasAutomaticTranslationRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // The identifier of the channel
	HasAutomaticTranslation bool `json:"has_automatic_translation"` // The new value of has_automatic_translation
}

func (r *ToggleSupergroupHasAutomaticTranslationRequest) GetType() string { return "toggleSupergroupHasAutomaticTranslation" }

// ToggleSupergroupHasHiddenMembersRequest — Toggles whether non-administrators can receive only administrators and bots using getSupergroupMembers or searchChatMembers. Can be called only if supergroupFullInfo.can_hide_members == true
type ToggleSupergroupHasHiddenMembersRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup
	HasHiddenMembers bool `json:"has_hidden_members"` // New value of has_hidden_members
}

func (r *ToggleSupergroupHasHiddenMembersRequest) GetType() string { return "toggleSupergroupHasHiddenMembers" }

// ToggleSupergroupHasAggressiveAntiSpamEnabledRequest — Toggles whether aggressive anti-spam checks are enabled in the supergroup. Can be called only if supergroupFullInfo.can_toggle_aggressive_anti_spam == true
type ToggleSupergroupHasAggressiveAntiSpamEnabledRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // The identifier of the supergroup, which isn't a broadcast group
	HasAggressiveAntiSpamEnabled bool `json:"has_aggressive_anti_spam_enabled"` // The new value of has_aggressive_anti_spam_enabled
}

func (r *ToggleSupergroupHasAggressiveAntiSpamEnabledRequest) GetType() string { return "toggleSupergroupHasAggressiveAntiSpamEnabled" }

// ToggleSupergroupIsForumRequest — Toggles whether the supergroup is a forum; requires owner privileges in the supergroup. Discussion supergroups can't be converted to forums
type ToggleSupergroupIsForumRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup
	IsForum bool `json:"is_forum"` // New value of is_forum
	HasForumTabs bool `json:"has_forum_tabs"` // New value of has_forum_tabs; ignored if is_forum is false
}

func (r *ToggleSupergroupIsForumRequest) GetType() string { return "toggleSupergroupIsForum" }

// ToggleSupergroupIsBroadcastGroupRequest — Upgrades supergroup to a broadcast group; requires owner privileges in the supergroup @supergroup_id Identifier of the supergroup
type ToggleSupergroupIsBroadcastGroupRequest struct {
	SupergroupID int64 `json:"supergroup_id"`
}

func (r *ToggleSupergroupIsBroadcastGroupRequest) GetType() string { return "toggleSupergroupIsBroadcastGroup" }

// ReportSupergroupSpamRequest — Reports messages in a supergroup as spam; requires administrator rights in the supergroup
type ReportSupergroupSpamRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Supergroup identifier
	MessageIDs []int64 `json:"message_ids"` // Identifiers of messages to report. Use messageProperties.can_report_supergroup_spam to check whether the message can be reported
}

func (r *ReportSupergroupSpamRequest) GetType() string { return "reportSupergroupSpam" }

// ReportSupergroupAntiSpamFalsePositiveRequest — Reports a false deletion of a message by aggressive anti-spam checks; requires administrator rights in the supergroup. Can be called only for messages from chatEventMessageDeleted with can_report_anti_spam_false_positive == true
type ReportSupergroupAntiSpamFalsePositiveRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Supergroup identifier
	MessageID int64 `json:"message_id"` // Identifier of the erroneously deleted message from chatEventMessageDeleted
}

func (r *ReportSupergroupAntiSpamFalsePositiveRequest) GetType() string { return "reportSupergroupAntiSpamFalsePositive" }

// GetSupergroupMembersRequest — Returns information about members or banned users in a supergroup or channel. Can be used only if supergroupFullInfo.can_get_members == true; additionally, administrator privileges may be required for some filters
type GetSupergroupMembersRequest struct {
	SupergroupID int64 `json:"supergroup_id"` // Identifier of the supergroup or channel
	Filter *SupergroupMembersFilter `json:"filter"` // The type of users to return; pass null to use supergroupMembersFilterRecent
	Offset int32 `json:"offset"` // Number of users to skip
	Limit int32 `json:"limit"` // The maximum number of users to be returned; up to 200
}

func (r *GetSupergroupMembersRequest) GetType() string { return "getSupergroupMembers" }

// CloseSecretChatRequest — Closes a secret chat, effectively transferring its state to secretChatStateClosed @secret_chat_id Secret chat identifier
type CloseSecretChatRequest struct {
	SecretChatID int32 `json:"secret_chat_id"`
}

func (r *CloseSecretChatRequest) GetType() string { return "closeSecretChat" }

// GetChatEventLogRequest — Returns a list of service actions taken by chat members and administrators in the last 48 hours. Available only for supergroups and channels. Requires administrator rights. Returns results in reverse chronological order (i.e., in order of decreasing event_id)
type GetChatEventLogRequest struct {
	ChatID int64 `json:"chat_id"` // Chat identifier
	Query string `json:"query"` // Search query by which to filter events
	FromEventID JSONInt64 `json:"from_event_id"` // Identifier of an event from which to return results. Use 0 to get results from the latest events
	Limit int32 `json:"limit"` // The maximum number of events to return; up to 100
	Filters *ChatEventLogFilters `json:"filters"` // The types of events to return; pass null to get chat events of all types
	UserIDs []int64 `json:"user_ids"` // User identifiers by which to filter events. By default, events relating to all users will be returned
}

func (r *GetChatEventLogRequest) GetType() string { return "getChatEventLog" }

// GetTimeZonesRequest — Returns the list of supported time zones
type GetTimeZonesRequest struct {
}

func (r *GetTimeZonesRequest) GetType() string { return "getTimeZones" }

// GetPaymentFormRequest — Returns an invoice payment form. This method must be called when the user presses inline button of the type inlineKeyboardButtonTypeBuy, or wants to buy access to media in a messagePaidMedia message
type GetPaymentFormRequest struct {
	InputInvoice *InputInvoice `json:"input_invoice"` // The invoice
	Theme *ThemeParameters `json:"theme"` // Preferred payment form theme; pass null to use the default theme
}

func (r *GetPaymentFormRequest) GetType() string { return "getPaymentForm" }

// ValidateOrderInfoRequest — Validates the order information provided by a user and returns the available shipping options for a flexible invoice
type ValidateOrderInfoRequest struct {
	InputInvoice *InputInvoice `json:"input_invoice"` // The invoice
	OrderInfo *OrderInfo `json:"order_info"` // The order information, provided by the user; pass null if empty
	AllowSave bool `json:"allow_save"` // Pass true to save the order information
}

func (r *ValidateOrderInfoRequest) GetType() string { return "validateOrderInfo" }

// SendPaymentFormRequest — Sends a filled-out payment form to the bot for final verification
type SendPaymentFormRequest struct {
	InputInvoice *InputInvoice `json:"input_invoice"` // The invoice
	PaymentFormID JSONInt64 `json:"payment_form_id"` // Payment form identifier returned by getPaymentForm
	OrderInfoID string `json:"order_info_id"` // Identifier returned by validateOrderInfo, or an empty string
	ShippingOptionID string `json:"shipping_option_id"` // Identifier of a chosen shipping option, if applicable
	Credentials *InputCredentials `json:"credentials"` // The credentials chosen by user for payment; pass null for a payment in Telegram Stars
	TipAmount int64 `json:"tip_amount"` // Chosen by the user amount of tip in the smallest units of the currency
}

func (r *SendPaymentFormRequest) GetType() string { return "sendPaymentForm" }

// GetPaymentReceiptRequest — Returns information about a successful payment @chat_id Chat identifier of the messagePaymentSuccessful message @message_id Message identifier
type GetPaymentReceiptRequest struct {
	ChatID int64 `json:"chat_id"`
	MessageID int64 `json:"message_id"`
}

func (r *GetPaymentReceiptRequest) GetType() string { return "getPaymentReceipt" }

// GetSavedOrderInfoRequest — Returns saved order information. Returns a 404 error if there is no saved order information
type GetSavedOrderInfoRequest struct {
}

func (r *GetSavedOrderInfoRequest) GetType() string { return "getSavedOrderInfo" }

// DeleteSavedOrderInfoRequest — Deletes saved order information
type DeleteSavedOrderInfoRequest struct {
}

func (r *DeleteSavedOrderInfoRequest) GetType() string { return "deleteSavedOrderInfo" }

// DeleteSavedCredentialsRequest — Deletes saved credentials for all payment provider bots
type DeleteSavedCredentialsRequest struct {
}

func (r *DeleteSavedCredentialsRequest) GetType() string { return "deleteSavedCredentials" }

// SetGiftSettingsRequest — Changes settings for gift receiving for the current user @settings The new settings
type SetGiftSettingsRequest struct {
	Settings *GiftSettings `json:"settings"`
}

func (r *SetGiftSettingsRequest) GetType() string { return "setGiftSettings" }

// GetAvailableGiftsRequest — Returns gifts that can be sent to other users and channel chats
type GetAvailableGiftsRequest struct {
}

func (r *GetAvailableGiftsRequest) GetType() string { return "getAvailableGifts" }

// CanSendGiftRequest — Checks whether a gift with next_send_date in the future can be sent already
type CanSendGiftRequest struct {
	GiftID JSONInt64 `json:"gift_id"` // Identifier of the gift to send
}

func (r *CanSendGiftRequest) GetType() string { return "canSendGift" }

// SendGiftRequest — Sends a gift to another user or channel chat. May return an error with a message "STARGIFT_USAGE_LIMITED" if the gift was sold out
type SendGiftRequest struct {
	GiftID JSONInt64 `json:"gift_id"` // Identifier of the gift to send
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that will receive the gift; limited gifts can't be sent to channel chats
	Text *FormattedText `json:"text"` // Text to show along with the gift; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed.
	IsPrivate bool `json:"is_private"` // Pass true to show gift text and sender only to the gift receiver; otherwise, everyone will be able to see them
	PayForUpgrade bool `json:"pay_for_upgrade"` // Pass true to additionally pay for the gift upgrade and allow the receiver to upgrade it for free
}

func (r *SendGiftRequest) GetType() string { return "sendGift" }

// GetGiftAuctionStateRequest — Returns auction state for a gift @auction_id Unique identifier of the auction
type GetGiftAuctionStateRequest struct {
	AuctionID string `json:"auction_id"`
}

func (r *GetGiftAuctionStateRequest) GetType() string { return "getGiftAuctionState" }

// GetGiftAuctionAcquiredGiftsRequest — Returns the gifts that were acquired by the current user on a gift auction @gift_id Identifier of the auctioned gift
type GetGiftAuctionAcquiredGiftsRequest struct {
	GiftID JSONInt64 `json:"gift_id"`
}

func (r *GetGiftAuctionAcquiredGiftsRequest) GetType() string { return "getGiftAuctionAcquiredGifts" }

// OpenGiftAuctionRequest — Informs TDLib that a gift auction was opened by the user @gift_id Identifier of the gift, which auction was opened
type OpenGiftAuctionRequest struct {
	GiftID JSONInt64 `json:"gift_id"`
}

func (r *OpenGiftAuctionRequest) GetType() string { return "openGiftAuction" }

// CloseGiftAuctionRequest — Informs TDLib that a gift auction was closed by the user @gift_id Identifier of the gift, which auction was closed
type CloseGiftAuctionRequest struct {
	GiftID JSONInt64 `json:"gift_id"`
}

func (r *CloseGiftAuctionRequest) GetType() string { return "closeGiftAuction" }

// PlaceGiftAuctionBidRequest — Places a bid on an auction gift
type PlaceGiftAuctionBidRequest struct {
	GiftID JSONInt64 `json:"gift_id"` // Identifier of the gift to place the bid on
	StarCount int64 `json:"star_count"` // The number of Telegram Stars to place in the bid
	UserID int64 `json:"user_id"` // Identifier of the user who will receive the gift
	Text *FormattedText `json:"text"` // Text to show along with the gift; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed.
	IsPrivate bool `json:"is_private"` // Pass true to show gift text and sender only to the gift receiver; otherwise, everyone will be able to see them
}

func (r *PlaceGiftAuctionBidRequest) GetType() string { return "placeGiftAuctionBid" }

// IncreaseGiftAuctionBidRequest — Increases a bid for an auction gift without changing gift text and receiver
type IncreaseGiftAuctionBidRequest struct {
	GiftID JSONInt64 `json:"gift_id"` // Identifier of the gift to put the bid on
	StarCount int64 `json:"star_count"` // The number of Telegram Stars to put in the bid
}

func (r *IncreaseGiftAuctionBidRequest) GetType() string { return "increaseGiftAuctionBid" }

// SellGiftRequest — Sells a gift for Telegram Stars; requires owner privileges for gifts owned by a chat
type SellGiftRequest struct {
	BusinessConnectionID string `json:"business_connection_id"` // Unique identifier of business connection on behalf of which to send the request; for bots only
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the gift
}

func (r *SellGiftRequest) GetType() string { return "sellGift" }

// ToggleGiftIsSavedRequest — Toggles whether a gift is shown on the current user's or the channel's profile page; requires can_post_messages administrator right in the channel chat
type ToggleGiftIsSavedRequest struct {
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the gift
	IsSaved bool `json:"is_saved"` // Pass true to display the gift on the user's or the channel's profile page; pass false to remove it from the profile page
}

func (r *ToggleGiftIsSavedRequest) GetType() string { return "toggleGiftIsSaved" }

// SetPinnedGiftsRequest — Changes the list of pinned gifts on the current user's or the channel's profile page; requires can_post_messages administrator right in the channel chat
type SetPinnedGiftsRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that received the gifts
	ReceivedGiftIDs []string `json:"received_gift_ids"` // New list of pinned gifts. All gifts must be upgraded and saved on the profile page first. There can be up to getOption("pinned_gift_count_max") pinned gifts
}

func (r *SetPinnedGiftsRequest) GetType() string { return "setPinnedGifts" }

// ToggleChatGiftNotificationsRequest — Toggles whether notifications for new gifts received by a channel chat are sent to the current user; requires can_post_messages administrator right in the chat
type ToggleChatGiftNotificationsRequest struct {
	ChatID int64 `json:"chat_id"` // Identifier of the channel chat
	AreEnabled bool `json:"are_enabled"` // Pass true to enable notifications about new gifts owned by the channel chat; pass false to disable the notifications
}

func (r *ToggleChatGiftNotificationsRequest) GetType() string { return "toggleChatGiftNotifications" }

// GetGiftUpgradePreviewRequest — Returns examples of possible upgraded gifts for a regular gift @regular_gift_id Identifier of the regular gift
type GetGiftUpgradePreviewRequest struct {
	RegularGiftID JSONInt64 `json:"regular_gift_id"`
}

func (r *GetGiftUpgradePreviewRequest) GetType() string { return "getGiftUpgradePreview" }

// GetUpgradedGiftVariantsRequest — Returns all possible variants of upgraded gifts for a regular gift
type GetUpgradedGiftVariantsRequest struct {
	RegularGiftID JSONInt64 `json:"regular_gift_id"` // Identifier of the regular gift
	ReturnUpgradeModels bool `json:"return_upgrade_models"` // Pass true to get models that can be obtained by upgrading a regular gift
	ReturnCraftModels bool `json:"return_craft_models"` // Pass true to get models that can be obtained by crafting a gift from upgraded gifts
}

func (r *GetUpgradedGiftVariantsRequest) GetType() string { return "getUpgradedGiftVariants" }

// UpgradeGiftRequest — Upgrades a regular gift
type UpgradeGiftRequest struct {
	BusinessConnectionID string `json:"business_connection_id"` // Unique identifier of business connection on behalf of which to send the request; for bots only
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the gift
	KeepOriginalDetails bool `json:"keep_original_details"` // Pass true to keep the original gift text, sender and receiver in the upgraded gift
	StarCount int64 `json:"star_count"` // The Telegram Star amount required to pay for the upgrade. It the gift has prepaid_upgrade_star_count > 0, then pass 0, otherwise, pass gift.upgrade_star_count
}

func (r *UpgradeGiftRequest) GetType() string { return "upgradeGift" }

// BuyGiftUpgradeRequest — Pays for upgrade of a regular gift that is owned by another user or channel chat
type BuyGiftUpgradeRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the gift
	PrepaidUpgradeHash string `json:"prepaid_upgrade_hash"` // Prepaid upgrade hash as received along with the gift
	StarCount int64 `json:"star_count"` // The Telegram Star amount the user agreed to pay for the upgrade; must be equal to gift.upgrade_star_count
}

func (r *BuyGiftUpgradeRequest) GetType() string { return "buyGiftUpgrade" }

// CraftGiftRequest — Crafts a new gift from other gifts that will be permanently lost
type CraftGiftRequest struct {
	ReceivedGiftIDs []string `json:"received_gift_ids"` // Identifier of the gifts to use for crafting. In the case of a successful craft, the resulting gift will have the number of the first gift.
}

func (r *CraftGiftRequest) GetType() string { return "craftGift" }

// TransferGiftRequest — Sends an upgraded gift to another user or channel chat
type TransferGiftRequest struct {
	BusinessConnectionID string `json:"business_connection_id"` // Unique identifier of business connection on behalf of which to send the request; for bots only
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the gift
	NewOwnerID *MessageSender `json:"new_owner_id"` // Identifier of the user or the channel chat that will receive the gift
	StarCount int64 `json:"star_count"` // The Telegram Star amount required to pay for the transfer
}

func (r *TransferGiftRequest) GetType() string { return "transferGift" }

// DropGiftOriginalDetailsRequest — Drops original details for an upgraded gift
type DropGiftOriginalDetailsRequest struct {
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the gift
	StarCount int64 `json:"star_count"` // The Telegram Star amount required to pay for the operation
}

func (r *DropGiftOriginalDetailsRequest) GetType() string { return "dropGiftOriginalDetails" }

// SendResoldGiftRequest — Sends an upgraded gift that is available for resale to another user or channel chat; gifts already owned by the current user
type SendResoldGiftRequest struct {
	GiftName string `json:"gift_name"` // Name of the upgraded gift to send
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that will receive the gift
	Price *GiftResalePrice `json:"price"` // The price that the user agreed to pay for the gift
}

func (r *SendResoldGiftRequest) GetType() string { return "sendResoldGift" }

// SendGiftPurchaseOfferRequest — Sends an offer to purchase an upgraded gift
type SendGiftPurchaseOfferRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that currently owns the gift and will receive the offer
	GiftName string `json:"gift_name"` // Name of the upgraded gift
	Price *GiftResalePrice `json:"price"` // The price that the user agreed to pay for the gift
	Duration int32 `json:"duration"` // Duration of the offer, in seconds; must be one of 21600, 43200, 86400, 129600, 172800, or 259200. Can also be 120 if Telegram test environment is used
	PaidMessageStarCount int64 `json:"paid_message_star_count"` // The number of Telegram Stars the user agreed to pay additionally for sending of the offer message to the current gift owner; pass userFullInfo.outgoing_paid_message_star_count for users and 0 otherwise
}

func (r *SendGiftPurchaseOfferRequest) GetType() string { return "sendGiftPurchaseOffer" }

// ProcessGiftPurchaseOfferRequest — Handles a pending gift purchase offer
type ProcessGiftPurchaseOfferRequest struct {
	MessageID int64 `json:"message_id"` // Identifier of the message with the gift purchase offer
	Accept bool `json:"accept"` // Pass true to accept the request; pass false to reject it
}

func (r *ProcessGiftPurchaseOfferRequest) GetType() string { return "processGiftPurchaseOffer" }

// GetReceivedGiftsRequest — Returns gifts received by the given user or chat
type GetReceivedGiftsRequest struct {
	BusinessConnectionID string `json:"business_connection_id"` // Unique identifier of business connection on behalf of which to send the request; for bots only
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the gift receiver
	CollectionID int32 `json:"collection_id"` // Pass collection identifier to get gifts only from the specified collection; pass 0 to get gifts regardless of collections
	ExcludeUnsaved bool `json:"exclude_unsaved"` // Pass true to exclude gifts that aren't saved to the chat's profile page. Always true for gifts received by other users and channel chats without can_post_messages administrator right
	ExcludeSaved bool `json:"exclude_saved"` // Pass true to exclude gifts that are saved to the chat's profile page. Always false for gifts received by other users and channel chats without can_post_messages administrator right
	ExcludeUnlimited bool `json:"exclude_unlimited"` // Pass true to exclude gifts that can be purchased unlimited number of times
	ExcludeUpgradable bool `json:"exclude_upgradable"` // Pass true to exclude gifts that can be purchased limited number of times and can be upgraded
	ExcludeNonUpgradable bool `json:"exclude_non_upgradable"` // Pass true to exclude gifts that can be purchased limited number of times and can't be upgraded
	ExcludeUpgraded bool `json:"exclude_upgraded"` // Pass true to exclude upgraded gifts
	ExcludeWithoutColors bool `json:"exclude_without_colors"` // Pass true to exclude gifts that can't be used in setUpgradedGiftColors
	ExcludeHosted bool `json:"exclude_hosted"` // Pass true to exclude gifts that are just hosted and are not owned by the owner
	SortByPrice bool `json:"sort_by_price"` // Pass true to sort results by gift price instead of send date
	Offset string `json:"offset"` // Offset of the first entry to return as received from the previous request; use empty string to get the first chunk of results
	Limit int32 `json:"limit"` // The maximum number of gifts to be returned; must be positive and can't be greater than 100. For optimal performance, the number of returned objects is chosen by TDLib and can be smaller than the specified limit
}

func (r *GetReceivedGiftsRequest) GetType() string { return "getReceivedGifts" }

// GetReceivedGiftRequest — Returns information about a received gift @received_gift_id Identifier of the gift
type GetReceivedGiftRequest struct {
	ReceivedGiftID string `json:"received_gift_id"`
}

func (r *GetReceivedGiftRequest) GetType() string { return "getReceivedGift" }

// GetGiftsForCraftingRequest — Returns upgraded gifts of the current user who can be used to craft another gifts
type GetGiftsForCraftingRequest struct {
	RegularGiftID JSONInt64 `json:"regular_gift_id"` // Identifier of the regular gift that will be used for crafting
	Offset string `json:"offset"` // Offset of the first entry to return as received from the previous request; use empty string to get the first chunk of results
	Limit int32 `json:"limit"` // The maximum number of gifts to be returned; must be positive and can't be greater than 100. For optimal performance, the number of returned objects is chosen by TDLib and can be smaller than the specified limit
}

func (r *GetGiftsForCraftingRequest) GetType() string { return "getGiftsForCrafting" }

// GetUpgradedGiftRequest — Returns information about an upgraded gift by its name @name Unique name of the upgraded gift
type GetUpgradedGiftRequest struct {
	Name string `json:"name"`
}

func (r *GetUpgradedGiftRequest) GetType() string { return "getUpgradedGift" }

// GetUpgradedGiftValueInfoRequest — Returns information about value of an upgraded gift by its name @name Unique name of the upgraded gift
type GetUpgradedGiftValueInfoRequest struct {
	Name string `json:"name"`
}

func (r *GetUpgradedGiftValueInfoRequest) GetType() string { return "getUpgradedGiftValueInfo" }

// GetUpgradedGiftWithdrawalURLRequest — Returns a URL for upgraded gift withdrawal in the TON blockchain as an NFT; requires owner privileges for gifts owned by a chat
type GetUpgradedGiftWithdrawalURLRequest struct {
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the gift
	Password string `json:"password"` // The 2-step verification password of the current user
}

func (r *GetUpgradedGiftWithdrawalURLRequest) GetType() string { return "getUpgradedGiftWithdrawalUrl" }

// GetUpgradedGiftsPromotionalAnimationRequest — Returns promotional anumation for upgraded gifts
type GetUpgradedGiftsPromotionalAnimationRequest struct {
}

func (r *GetUpgradedGiftsPromotionalAnimationRequest) GetType() string { return "getUpgradedGiftsPromotionalAnimation" }

// SetGiftResalePriceRequest — Changes resale price of a unique gift owned by the current user
type SetGiftResalePriceRequest struct {
	ReceivedGiftID string `json:"received_gift_id"` // Identifier of the unique gift
	Price *GiftResalePrice `json:"price"` // The new price for the unique gift; pass null to disallow gift resale. The current user will receive
}

func (r *SetGiftResalePriceRequest) GetType() string { return "setGiftResalePrice" }

// SearchGiftsForResaleRequest — Returns upgraded gifts that can be bought from other owners using sendResoldGift
type SearchGiftsForResaleRequest struct {
	GiftID JSONInt64 `json:"gift_id"` // Identifier of the regular gift that was upgraded to a unique gift
	Order *GiftForResaleOrder `json:"order"` // Order in which the results will be sorted
	ForCrafting bool `json:"for_crafting"` // Pass true to get only gifts suitable for crafting
	Attributes []*UpgradedGiftAttributeID `json:"attributes"` // Attributes used to filter received gifts. If multiple attributes of the same type are specified, then all of them are allowed.
	Offset string `json:"offset"` // Offset of the first entry to return as received from the previous request with the same order and attributes; use empty string to get the first chunk of results
	Limit int32 `json:"limit"` // The maximum number of gifts to return
}

func (r *SearchGiftsForResaleRequest) GetType() string { return "searchGiftsForResale" }

// GetGiftCollectionsRequest — Returns collections of gifts owned by the given user or chat
type GetGiftCollectionsRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that received the gifts
}

func (r *GetGiftCollectionsRequest) GetType() string { return "getGiftCollections" }

// CreateGiftCollectionRequest — Creates a collection from gifts on the current user's or a channel's profile page; requires can_post_messages administrator right in the channel chat.
type CreateGiftCollectionRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that received the gifts
	Name string `json:"name"` // Name of the collection; 1-12 characters
	ReceivedGiftIDs []string `json:"received_gift_ids"` // Identifier of the gifts to add to the collection; 0-getOption("gift_collection_size_max") identifiers
}

func (r *CreateGiftCollectionRequest) GetType() string { return "createGiftCollection" }

// ReorderGiftCollectionsRequest — Changes order of gift collections. If the collections are owned by a channel chat, then requires can_post_messages administrator right in the channel chat
type ReorderGiftCollectionsRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the collection
	CollectionIDs []int32 `json:"collection_ids"` // New order of gift collections
}

func (r *ReorderGiftCollectionsRequest) GetType() string { return "reorderGiftCollections" }

// DeleteGiftCollectionRequest — Deletes a gift collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat
type DeleteGiftCollectionRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the collection
	CollectionID int32 `json:"collection_id"` // Identifier of the gift collection
}

func (r *DeleteGiftCollectionRequest) GetType() string { return "deleteGiftCollection" }

// SetGiftCollectionNameRequest — Changes name of a gift collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat. Returns the changed collection
type SetGiftCollectionNameRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the collection
	CollectionID int32 `json:"collection_id"` // Identifier of the gift collection
	Name string `json:"name"` // New name of the collection; 1-12 characters
}

func (r *SetGiftCollectionNameRequest) GetType() string { return "setGiftCollectionName" }

// AddGiftCollectionGiftsRequest — Adds gifts to the beginning of a previously created collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat. Returns the changed collection
type AddGiftCollectionGiftsRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the collection
	CollectionID int32 `json:"collection_id"` // Identifier of the gift collection
	ReceivedGiftIDs []string `json:"received_gift_ids"` // Identifier of the gifts to add to the collection; 1-getOption("gift_collection_size_max") identifiers.
}

func (r *AddGiftCollectionGiftsRequest) GetType() string { return "addGiftCollectionGifts" }

// RemoveGiftCollectionGiftsRequest — Removes gifts from a collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat. Returns the changed collection
type RemoveGiftCollectionGiftsRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the collection
	CollectionID int32 `json:"collection_id"` // Identifier of the gift collection
	ReceivedGiftIDs []string `json:"received_gift_ids"` // Identifier of the gifts to remove from the collection
}

func (r *RemoveGiftCollectionGiftsRequest) GetType() string { return "removeGiftCollectionGifts" }

// ReorderGiftCollectionGiftsRequest — Changes order of gifts in a collection. If the collection is owned by a channel chat, then requires can_post_messages administrator right in the channel chat. Returns the changed collection
type ReorderGiftCollectionGiftsRequest struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the user or the channel chat that owns the collection
	CollectionID int32 `json:"collection_id"` // Identifier of the gift collection
	ReceivedGiftIDs []string `json:"received_gift_ids"` // Identifier of the gifts to move to the beginning of the collection. All other gifts are placed in the current order after the specified gifts
}

func (r *ReorderGiftCollectionGiftsRequest) GetType() string { return "reorderGiftCollectionGifts" }

// CreateInvoiceLinkRequest — Creates a link for the given invoice; for bots only
type CreateInvoiceLinkRequest struct {
	BusinessConnectionID string `json:"business_connection_id"` // Unique identifier of business connection on behalf of which to send the request
	Invoice *InputMessageContent `json:"invoice"` // Information about the invoice of the type inputMessageInvoice
}

func (r *CreateInvoiceLinkRequest) GetType() string { return "createInvoiceLink" }

// RefundStarPaymentRequest — Refunds a previously done payment in Telegram Stars; for bots only
type RefundStarPaymentRequest struct {
	UserID int64 `json:"user_id"` // Identifier of the user who did the payment
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"` // Telegram payment identifier
}

func (r *RefundStarPaymentRequest) GetType() string { return "refundStarPayment" }

// GetSupportUserRequest — Returns a user who can be contacted to get support
type GetSupportUserRequest struct {
}

func (r *GetSupportUserRequest) GetType() string { return "getSupportUser" }

// GetBackgroundURLRequest — Constructs a persistent HTTP URL for a background @name Background name @type Background type; backgroundTypeChatTheme isn't supported
type GetBackgroundURLRequest struct {
	Name string `json:"name"`
	Type *BackgroundType `json:"type"`
}

func (r *GetBackgroundURLRequest) GetType() string { return "getBackgroundUrl" }

// SearchBackgroundRequest — Searches for a background by its name @name The name of the background
type SearchBackgroundRequest struct {
	Name string `json:"name"`
}

func (r *SearchBackgroundRequest) GetType() string { return "searchBackground" }

// SetDefaultBackgroundRequest — Sets default background for chats; adds the background to the list of installed backgrounds
type SetDefaultBackgroundRequest struct {
	Background *InputBackground `json:"background"` // The input background to use; pass null to create a new filled background
	Type *BackgroundType `json:"type"` // Background type; pass null to use the default type of the remote background; backgroundTypeChatTheme isn't supported
	ForDarkTheme bool `json:"for_dark_theme"` // Pass true if the background is set for a dark theme
}

func (r *SetDefaultBackgroundRequest) GetType() string { return "setDefaultBackground" }

// DeleteDefaultBackgroundRequest — Deletes default background for chats @for_dark_theme Pass true if the background is deleted for a dark theme
type DeleteDefaultBackgroundRequest struct {
	ForDarkTheme bool `json:"for_dark_theme"`
}

func (r *DeleteDefaultBackgroundRequest) GetType() string { return "deleteDefaultBackground" }

// GetInstalledBackgroundsRequest — Returns backgrounds installed by the user @for_dark_theme Pass true to order returned backgrounds for a dark theme
type GetInstalledBackgroundsRequest struct {
	ForDarkTheme bool `json:"for_dark_theme"`
}

func (r *GetInstalledBackgroundsRequest) GetType() string { return "getInstalledBackgrounds" }

// RemoveInstalledBackgroundRequest — Removes background from the list of installed backgrounds @background_id The background identifier
type RemoveInstalledBackgroundRequest struct {
	BackgroundID JSONInt64 `json:"background_id"`
}

func (r *RemoveInstalledBackgroundRequest) GetType() string { return "removeInstalledBackground" }

// ResetInstalledBackgroundsRequest — Resets list of installed backgrounds to its default value
type ResetInstalledBackgroundsRequest struct {
}

func (r *ResetInstalledBackgroundsRequest) GetType() string { return "resetInstalledBackgrounds" }

// GetLocalizationTargetInfoRequest — Returns information about the current localization target. This is an offline method if only_local is true. Can be called before authorization @only_local Pass true to get only locally available information without sending network requests
type GetLocalizationTargetInfoRequest struct {
	OnlyLocal bool `json:"only_local"`
}

func (r *GetLocalizationTargetInfoRequest) GetType() string { return "getLocalizationTargetInfo" }

// GetLanguagePackInfoRequest — Returns information about a language pack. Returned language pack identifier may be different from a provided one. Can be called before authorization @language_pack_id Language pack identifier
type GetLanguagePackInfoRequest struct {
	LanguagePackID string `json:"language_pack_id"`
}

func (r *GetLanguagePackInfoRequest) GetType() string { return "getLanguagePackInfo" }

// GetLanguagePackStringsRequest — Returns strings from a language pack in the current localization target by their keys. Can be called before authorization
type GetLanguagePackStringsRequest struct {
	LanguagePackID string `json:"language_pack_id"` // Language pack identifier of the strings to be returned
	Keys []string `json:"keys"` // Language pack keys of the strings to be returned; leave empty to request all available strings
}

func (r *GetLanguagePackStringsRequest) GetType() string { return "getLanguagePackStrings" }

// SynchronizeLanguagePackRequest — Fetches the latest versions of all strings from a language pack in the current localization target from the server.
type SynchronizeLanguagePackRequest struct {
	LanguagePackID string `json:"language_pack_id"` // Language pack identifier
}

func (r *SynchronizeLanguagePackRequest) GetType() string { return "synchronizeLanguagePack" }

// AddCustomServerLanguagePackRequest — Adds a custom server language pack to the list of installed language packs in current localization target. Can be called before authorization @language_pack_id Identifier of a language pack to be added
type AddCustomServerLanguagePackRequest struct {
	LanguagePackID string `json:"language_pack_id"`
}

func (r *AddCustomServerLanguagePackRequest) GetType() string { return "addCustomServerLanguagePack" }

// SetCustomLanguagePackRequest — Adds or changes a custom local language pack to the current localization target
type SetCustomLanguagePackRequest struct {
	Info *LanguagePackInfo `json:"info"` // Information about the language pack. Language pack identifier must start with 'X', consist only of English letters, digits and hyphens, and must not exceed 64 characters. Can be called before authorization
	Strings []*LanguagePackString `json:"strings"` // Strings of the new language pack
}

func (r *SetCustomLanguagePackRequest) GetType() string { return "setCustomLanguagePack" }

// EditCustomLanguagePackInfoRequest — Edits information about a custom local language pack in the current localization target. Can be called before authorization @info New information about the custom local language pack
type EditCustomLanguagePackInfoRequest struct {
	Info *LanguagePackInfo `json:"info"`
}

func (r *EditCustomLanguagePackInfoRequest) GetType() string { return "editCustomLanguagePackInfo" }

