// Code generated by go-tdlib codegen. DO NOT EDIT.
package tdapi

// InternalLinkTypeGiftAuction — The link is a link to a gift auction. Call getGiftAuctionState with the given auction identifier to process the link
type InternalLinkTypeGiftAuction struct {
	AuctionID string `json:"auction_id"` // Unique identifier of the auction
}

func (t *InternalLinkTypeGiftAuction) GetType() string { return "internalLinkTypeGiftAuction" }

// InternalLinkTypeGiftCollection — The link is a link to a gift collection. Call searchPublicChat with the given username, then call getReceivedGifts with the received gift owner identifier
type InternalLinkTypeGiftCollection struct {
	GiftOwnerUsername string `json:"gift_owner_username"` // Username of the owner of the gift collection
	CollectionID int32 `json:"collection_id"` // Gift collection identifier
}

func (t *InternalLinkTypeGiftCollection) GetType() string { return "internalLinkTypeGiftCollection" }

// InternalLinkTypeGroupCall — The link is a link to a group call that isn't bound to a chat. Use getGroupCallParticipants to get the list of group call participants and show them on the join group call screen.
type InternalLinkTypeGroupCall struct {
	InviteLink string `json:"invite_link"` // Internal representation of the invite link
}

func (t *InternalLinkTypeGroupCall) GetType() string { return "internalLinkTypeGroupCall" }

// InternalLinkTypeInstantView — The link must be opened in an Instant View. Call getWebPageInstantView with the given URL to process the link.
type InternalLinkTypeInstantView struct {
	URL string `json:"url"` // URL to be passed to getWebPageInstantView
	FallbackURL string `json:"fallback_url"` // An URL to open if getWebPageInstantView fails
}

func (t *InternalLinkTypeInstantView) GetType() string { return "internalLinkTypeInstantView" }

// InternalLinkTypeInvoice — The link is a link to an invoice. Call getPaymentForm with the given invoice name to process the link @invoice_name Name of the invoice
type InternalLinkTypeInvoice struct {
	InvoiceName string `json:"invoice_name"`
}

func (t *InternalLinkTypeInvoice) GetType() string { return "internalLinkTypeInvoice" }

// InternalLinkTypeLanguagePack — The link is a link to a language pack. Call getLanguagePackInfo with the given language pack identifier to process the link.
type InternalLinkTypeLanguagePack struct {
	LanguagePackID string `json:"language_pack_id"` // Language pack identifier
}

func (t *InternalLinkTypeLanguagePack) GetType() string { return "internalLinkTypeLanguagePack" }

// InternalLinkTypeLiveStory — The link is a link to a live story. Call searchPublicChat with the given chat username, then getChatActiveStories to get active stories in the chat,
type InternalLinkTypeLiveStory struct {
	StoryPosterUsername string `json:"story_poster_username"` // Username of the poster of the story
}

func (t *InternalLinkTypeLiveStory) GetType() string { return "internalLinkTypeLiveStory" }

// InternalLinkTypeMainWebApp — The link is a link to the main Web App of a bot. Call searchPublicChat with the given bot username, check that the user is a bot and has the main Web App.
type InternalLinkTypeMainWebApp struct {
	BotUsername string `json:"bot_username"` // Username of the bot
	StartParameter string `json:"start_parameter"` // Start parameter to be passed to getMainWebApp
	Mode *WebAppOpenMode `json:"mode"` // The mode to be passed to getMainWebApp
}

func (t *InternalLinkTypeMainWebApp) GetType() string { return "internalLinkTypeMainWebApp" }

// InternalLinkTypeMessage — The link is a link to a Telegram message or a forum topic. Call getMessageLinkInfo with the given URL to process the link,
type InternalLinkTypeMessage struct {
	URL string `json:"url"` // URL to be passed to getMessageLinkInfo
}

func (t *InternalLinkTypeMessage) GetType() string { return "internalLinkTypeMessage" }

// InternalLinkTypeMessageDraft — The link contains a message draft text. A share screen needs to be shown to the user, then the chosen chat must be opened and the text is added to the input field
type InternalLinkTypeMessageDraft struct {
	Text *FormattedText `json:"text"` // Message draft text
	ContainsLink bool `json:"contains_link"` // True, if the first line of the text contains a link. If true, the input field needs to be focused and the text after the link must be selected
}

func (t *InternalLinkTypeMessageDraft) GetType() string { return "internalLinkTypeMessageDraft" }

// InternalLinkTypeMyProfilePage — The link is a link to the My Profile application page @section Section of the page; may be one of
type InternalLinkTypeMyProfilePage struct {
	Section string `json:"section"`
}

func (t *InternalLinkTypeMyProfilePage) GetType() string { return "internalLinkTypeMyProfilePage" }

// InternalLinkTypeNewChannelChat — The link is a link to the screen for creating a new channel chat
type InternalLinkTypeNewChannelChat struct {
}

func (t *InternalLinkTypeNewChannelChat) GetType() string { return "internalLinkTypeNewChannelChat" }

// InternalLinkTypeNewGroupChat — The link is a link to the screen for creating a new group chat
type InternalLinkTypeNewGroupChat struct {
}

func (t *InternalLinkTypeNewGroupChat) GetType() string { return "internalLinkTypeNewGroupChat" }

// InternalLinkTypeNewPrivateChat — The link is a link to the screen for creating a new private chat with a contact
type InternalLinkTypeNewPrivateChat struct {
}

func (t *InternalLinkTypeNewPrivateChat) GetType() string { return "internalLinkTypeNewPrivateChat" }

// InternalLinkTypeNewStory — The link is a link to open the story posting interface @content_type The type of the content of the story to post; may be null if unspecified
type InternalLinkTypeNewStory struct {
	ContentType *StoryContentType `json:"content_type"`
}

func (t *InternalLinkTypeNewStory) GetType() string { return "internalLinkTypeNewStory" }

// InternalLinkTypeOauth — The link is an OAuth link. Call getOauthLinkInfo with the given URL to process the link if the link was received from outside of the application; otherwise, ignore it.
type InternalLinkTypeOauth struct {
	URL string `json:"url"` // URL to be passed to getOauthLinkInfo
}

func (t *InternalLinkTypeOauth) GetType() string { return "internalLinkTypeOauth" }

// InternalLinkTypePassportDataRequest — The link contains a request of Telegram passport data. Call getPassportAuthorizationForm with the given parameters to process the link if the link was received from outside of the application; otherwise, ignore it
type InternalLinkTypePassportDataRequest struct {
	BotUserID int64 `json:"bot_user_id"` // User identifier of the service's bot; the corresponding user may be unknown yet
	Scope string `json:"scope"` // Telegram Passport element types requested by the service
	PublicKey string `json:"public_key"` // Service's public key
	Nonce string `json:"nonce"` // Unique request identifier provided by the service
	CallbackURL string `json:"callback_url"` // An HTTP URL to open once the request is finished, canceled, or failed with the parameters tg_passport=success, tg_passport=cancel, or tg_passport=error&error=... respectively.
}

func (t *InternalLinkTypePassportDataRequest) GetType() string { return "internalLinkTypePassportDataRequest" }

// InternalLinkTypePhoneNumberConfirmation — The link can be used to confirm ownership of a phone number to prevent account deletion. Call sendPhoneNumberCode with the given phone number and with phoneNumberCodeTypeConfirmOwnership with the given hash to process the link.
type InternalLinkTypePhoneNumberConfirmation struct {
	Hash string `json:"hash"` // Hash value from the link
	PhoneNumber string `json:"phone_number"` // Phone number value from the link
}

func (t *InternalLinkTypePhoneNumberConfirmation) GetType() string { return "internalLinkTypePhoneNumberConfirmation" }

// InternalLinkTypePremiumFeaturesPage — The link is a link to the Premium features screen of the application from which the user can subscribe to Telegram Premium. Call getPremiumFeatures with the given referrer to process the link
type InternalLinkTypePremiumFeaturesPage struct {
	Referrer string `json:"referrer"` // Referrer specified in the link
}

func (t *InternalLinkTypePremiumFeaturesPage) GetType() string { return "internalLinkTypePremiumFeaturesPage" }

// InternalLinkTypePremiumGiftCode — The link is a link with a Telegram Premium gift code. Call checkPremiumGiftCode with the given code to process the link.
type InternalLinkTypePremiumGiftCode struct {
	Code string `json:"code"` // The Telegram Premium gift code
}

func (t *InternalLinkTypePremiumGiftCode) GetType() string { return "internalLinkTypePremiumGiftCode" }

// InternalLinkTypePremiumGiftPurchase — The link is a link to the screen for gifting Telegram Premium subscriptions to friends via inputInvoiceTelegram with telegramPaymentPurposePremiumGift payments or in-store purchases
type InternalLinkTypePremiumGiftPurchase struct {
	Referrer string `json:"referrer"` // Referrer specified in the link
}

func (t *InternalLinkTypePremiumGiftPurchase) GetType() string { return "internalLinkTypePremiumGiftPurchase" }

// InternalLinkTypeProxy — The link is a link to a proxy. Call addProxy with the given parameters to process the link and add the proxy
type InternalLinkTypeProxy struct {
	Proxy *Proxy `json:"proxy"` // The proxy; may be null if the proxy is unsupported, in which case an alert can be shown to the user
}

func (t *InternalLinkTypeProxy) GetType() string { return "internalLinkTypeProxy" }

// InternalLinkTypePublicChat — The link is a link to a chat by its username. Call searchPublicChat with the given chat username to process the link.
type InternalLinkTypePublicChat struct {
	ChatUsername string `json:"chat_username"` // Username of the chat
	DraftText string `json:"draft_text"` // Draft text for message to send in the chat
	OpenProfile bool `json:"open_profile"` // True, if chat profile information screen must be opened; otherwise, the chat itself must be opened
}

func (t *InternalLinkTypePublicChat) GetType() string { return "internalLinkTypePublicChat" }

// InternalLinkTypeQrCodeAuthentication — The link can be used to login the current user on another device, but it must be scanned from QR-code using in-app camera. An alert similar to
type InternalLinkTypeQrCodeAuthentication struct {
}

func (t *InternalLinkTypeQrCodeAuthentication) GetType() string { return "internalLinkTypeQrCodeAuthentication" }

// InternalLinkTypeRestorePurchases — The link forces restore of App Store purchases when opened. For official iOS application only
type InternalLinkTypeRestorePurchases struct {
}

func (t *InternalLinkTypeRestorePurchases) GetType() string { return "internalLinkTypeRestorePurchases" }

// InternalLinkTypeSavedMessages — The link is a link to the Saved Messages chat. Call createPrivateChat with getOption("my_id") and open the chat
type InternalLinkTypeSavedMessages struct {
}

func (t *InternalLinkTypeSavedMessages) GetType() string { return "internalLinkTypeSavedMessages" }

// InternalLinkTypeSearch — The link is a link to the global chat and messages search field
type InternalLinkTypeSearch struct {
}

func (t *InternalLinkTypeSearch) GetType() string { return "internalLinkTypeSearch" }

// InternalLinkTypeSettings — The link is a link to application settings @section Section of the application settings to open; may be null if none
type InternalLinkTypeSettings struct {
	Section *SettingsSection `json:"section"`
}

func (t *InternalLinkTypeSettings) GetType() string { return "internalLinkTypeSettings" }

// InternalLinkTypeStarPurchase — The link is a link to the Telegram Star purchase section of the application
type InternalLinkTypeStarPurchase struct {
	StarCount int64 `json:"star_count"` // The number of Telegram Stars that must be owned by the user
	Purpose string `json:"purpose"` // Purpose of Telegram Star purchase. Arbitrary string specified by the server, for example, "subs" if the Telegram Stars are required to extend channel subscriptions
}

func (t *InternalLinkTypeStarPurchase) GetType() string { return "internalLinkTypeStarPurchase" }

// InternalLinkTypeStickerSet — The link is a link to a sticker set. Call searchStickerSet with the given sticker set name to process the link and show the sticker set.
type InternalLinkTypeStickerSet struct {
	StickerSetName string `json:"sticker_set_name"` // Name of the sticker set
	ExpectCustomEmoji bool `json:"expect_custom_emoji"` // True, if the sticker set is expected to contain custom emoji
}

func (t *InternalLinkTypeStickerSet) GetType() string { return "internalLinkTypeStickerSet" }

// InternalLinkTypeStory — The link is a link to a story. Call searchPublicChat with the given poster username, then call getStory with the received chat identifier and the given story identifier, then show the story if received
type InternalLinkTypeStory struct {
	StoryPosterUsername string `json:"story_poster_username"` // Username of the poster of the story
	StoryID int32 `json:"story_id"` // Story identifier
}

func (t *InternalLinkTypeStory) GetType() string { return "internalLinkTypeStory" }

// InternalLinkTypeStoryAlbum — The link is a link to an album of stories. Call searchPublicChat with the given username, then call getStoryAlbumStories with the received chat identifier
type InternalLinkTypeStoryAlbum struct {
	StoryAlbumOwnerUsername string `json:"story_album_owner_username"` // Username of the owner of the story album
	StoryAlbumID int32 `json:"story_album_id"` // Story album identifier
}

func (t *InternalLinkTypeStoryAlbum) GetType() string { return "internalLinkTypeStoryAlbum" }

// InternalLinkTypeTheme — The link is a link to a cloud theme. TDLib has no theme support yet @theme_name Name of the theme
type InternalLinkTypeTheme struct {
	ThemeName string `json:"theme_name"`
}

func (t *InternalLinkTypeTheme) GetType() string { return "internalLinkTypeTheme" }

// InternalLinkTypeUnknownDeepLink — The link is an unknown tg: link. Call getDeepLinkInfo to process the link @link Link to be passed to getDeepLinkInfo
type InternalLinkTypeUnknownDeepLink struct {
	Link string `json:"link"`
}

func (t *InternalLinkTypeUnknownDeepLink) GetType() string { return "internalLinkTypeUnknownDeepLink" }

// InternalLinkTypeUpgradedGift — The link is a link to an upgraded gift. Call getUpgradedGift with the given name to process the link @name Name of the unique gift
type InternalLinkTypeUpgradedGift struct {
	Name string `json:"name"`
}

func (t *InternalLinkTypeUpgradedGift) GetType() string { return "internalLinkTypeUpgradedGift" }

// InternalLinkTypeUserPhoneNumber — The link is a link to a user by its phone number. Call searchUserByPhoneNumber with the given phone number to process the link.
type InternalLinkTypeUserPhoneNumber struct {
	PhoneNumber string `json:"phone_number"` // Phone number of the user
	DraftText string `json:"draft_text"` // Draft text for message to send in the chat
	OpenProfile bool `json:"open_profile"` // True, if user's profile information screen must be opened; otherwise, the chat itself must be opened
}

func (t *InternalLinkTypeUserPhoneNumber) GetType() string { return "internalLinkTypeUserPhoneNumber" }

// InternalLinkTypeUserToken — The link is a link to a user by a temporary token. Call searchUserByToken with the given token to process the link.
type InternalLinkTypeUserToken struct {
	Token string `json:"token"` // The token
}

func (t *InternalLinkTypeUserToken) GetType() string { return "internalLinkTypeUserToken" }

// InternalLinkTypeVideoChat — The link is a link to a video chat. Call searchPublicChat with the given chat username, and then joinVideoChat with the given invite hash to process the link
type InternalLinkTypeVideoChat struct {
	ChatUsername string `json:"chat_username"` // Username of the chat with the video chat
	InviteHash string `json:"invite_hash"` // If non-empty, invite hash to be used to join the video chat without being muted by administrators
	IsLiveStream bool `json:"is_live_stream"` // True, if the video chat is expected to be a live stream in a channel or a broadcast group
}

func (t *InternalLinkTypeVideoChat) GetType() string { return "internalLinkTypeVideoChat" }

// InternalLinkTypeWebApp — The link is a link to a Web App. Call searchPublicChat with the given bot username, check that the user is a bot. If the bot is restricted for the current user, then show an error message.
type InternalLinkTypeWebApp struct {
	BotUsername string `json:"bot_username"` // Username of the bot that owns the Web App
	WebAppShortName string `json:"web_app_short_name"` // Short name of the Web App
	StartParameter string `json:"start_parameter"` // Start parameter to be passed to getWebAppLinkUrl
	Mode *WebAppOpenMode `json:"mode"` // The mode in which the Web App must be opened
}

func (t *InternalLinkTypeWebApp) GetType() string { return "internalLinkTypeWebApp" }

// MessageLink — Contains an HTTPS link to a message in a supergroup or channel, or a forum topic @link The link @is_public True, if the link will work for non-members of the chat
type MessageLink struct {
	Link string `json:"link"`
	IsPublic bool `json:"is_public"`
}

func (t *MessageLink) GetType() string { return "messageLink" }

// MessageLinkInfo — Contains information about a link to a message or a forum topic in a chat
type MessageLinkInfo struct {
	IsPublic bool `json:"is_public"` // True, if the link is a public link for a message or a forum topic in a chat
	ChatID int64 `json:"chat_id"` // If found, identifier of the chat to which the link points, 0 otherwise
	TopicID *MessageTopic `json:"topic_id"` // Identifier of the specific topic in which the message must be opened, or a topic to open if the message is missing; may be null if none
	Message *Message `json:"message"` // If found, the linked message; may be null
	MediaTimestamp int32 `json:"media_timestamp"` // Timestamp from which the video/audio/video note/voice note/story playing must start, in seconds; 0 if not specified. The media can be in the message content or in its link preview
	ForAlbum bool `json:"for_album"` // True, if the whole media album to which the message belongs is linked
}

func (t *MessageLinkInfo) GetType() string { return "messageLinkInfo" }

// ChatBoostLink — Contains an HTTPS link to boost a chat @link The link @is_public True, if the link will work for non-members of the chat
type ChatBoostLink struct {
	Link string `json:"link"`
	IsPublic bool `json:"is_public"`
}

func (t *ChatBoostLink) GetType() string { return "chatBoostLink" }

// ChatBoostLinkInfo — Contains information about a link to boost a chat
type ChatBoostLinkInfo struct {
	IsPublic bool `json:"is_public"` // True, if the link will work for non-members of the chat
	ChatID int64 `json:"chat_id"` // Identifier of the chat to which the link points; 0 if the chat isn't found
}

func (t *ChatBoostLinkInfo) GetType() string { return "chatBoostLinkInfo" }

// BlockList — Describes type of block list
type BlockList struct {
}

func (t *BlockList) GetType() string { return "BlockList" }

// BlockListMain — The main block list that disallows writing messages to the current user, receiving their status and photo, viewing of stories, and some other actions
type BlockListMain struct {
}

func (t *BlockListMain) GetType() string { return "blockListMain" }

// BlockListStories — The block list that disallows viewing of stories of the current user
type BlockListStories struct {
}

func (t *BlockListStories) GetType() string { return "blockListStories" }

// FileType — Represents the type of file
type FileType struct {
}

func (t *FileType) GetType() string { return "FileType" }

// FileTypeNone — The data is not a file
type FileTypeNone struct {
}

func (t *FileTypeNone) GetType() string { return "fileTypeNone" }

// FileTypeAnimation — The file is an animation
type FileTypeAnimation struct {
}

func (t *FileTypeAnimation) GetType() string { return "fileTypeAnimation" }

// FileTypeAudio — The file is an audio file
type FileTypeAudio struct {
}

func (t *FileTypeAudio) GetType() string { return "fileTypeAudio" }

// FileTypeDocument — The file is a document
type FileTypeDocument struct {
}

func (t *FileTypeDocument) GetType() string { return "fileTypeDocument" }

// FileTypeNotificationSound — The file is a notification sound
type FileTypeNotificationSound struct {
}

func (t *FileTypeNotificationSound) GetType() string { return "fileTypeNotificationSound" }

// FileTypePhoto — The file is a photo
type FileTypePhoto struct {
}

func (t *FileTypePhoto) GetType() string { return "fileTypePhoto" }

// FileTypePhotoStory — The file is a photo published as a story
type FileTypePhotoStory struct {
}

func (t *FileTypePhotoStory) GetType() string { return "fileTypePhotoStory" }

// FileTypeProfilePhoto — The file is a profile photo
type FileTypeProfilePhoto struct {
}

func (t *FileTypeProfilePhoto) GetType() string { return "fileTypeProfilePhoto" }

// FileTypeSecret — The file was sent to a secret chat (the file type is not known to the server)
type FileTypeSecret struct {
}

func (t *FileTypeSecret) GetType() string { return "fileTypeSecret" }

// FileTypeSecretThumbnail — The file is a thumbnail of a file from a secret chat
type FileTypeSecretThumbnail struct {
}

func (t *FileTypeSecretThumbnail) GetType() string { return "fileTypeSecretThumbnail" }

// FileTypeSecure — The file is a file from Secure storage used for storing Telegram Passport files
type FileTypeSecure struct {
}

func (t *FileTypeSecure) GetType() string { return "fileTypeSecure" }

// FileTypeSelfDestructingPhoto — The file is a self-destructing photo in a private chat
type FileTypeSelfDestructingPhoto struct {
}

func (t *FileTypeSelfDestructingPhoto) GetType() string { return "fileTypeSelfDestructingPhoto" }

// FileTypeSelfDestructingVideo — The file is a self-destructing video in a private chat
type FileTypeSelfDestructingVideo struct {
}

func (t *FileTypeSelfDestructingVideo) GetType() string { return "fileTypeSelfDestructingVideo" }

// FileTypeSelfDestructingVideoNote — The file is a self-destructing video note in a private chat
type FileTypeSelfDestructingVideoNote struct {
}

func (t *FileTypeSelfDestructingVideoNote) GetType() string { return "fileTypeSelfDestructingVideoNote" }

// FileTypeSelfDestructingVoiceNote — The file is a self-destructing voice note in a private chat
type FileTypeSelfDestructingVoiceNote struct {
}

func (t *FileTypeSelfDestructingVoiceNote) GetType() string { return "fileTypeSelfDestructingVoiceNote" }

// FileTypeSticker — The file is a sticker
type FileTypeSticker struct {
}

func (t *FileTypeSticker) GetType() string { return "fileTypeSticker" }

// FileTypeThumbnail — The file is a thumbnail of another file
type FileTypeThumbnail struct {
}

func (t *FileTypeThumbnail) GetType() string { return "fileTypeThumbnail" }

// FileTypeUnknown — The file type is not yet known
type FileTypeUnknown struct {
}

func (t *FileTypeUnknown) GetType() string { return "fileTypeUnknown" }

// FileTypeVideo — The file is a video
type FileTypeVideo struct {
}

func (t *FileTypeVideo) GetType() string { return "fileTypeVideo" }

// FileTypeVideoNote — The file is a video note
type FileTypeVideoNote struct {
}

func (t *FileTypeVideoNote) GetType() string { return "fileTypeVideoNote" }

// FileTypeVideoStory — The file is a video published as a story
type FileTypeVideoStory struct {
}

func (t *FileTypeVideoStory) GetType() string { return "fileTypeVideoStory" }

// FileTypeVoiceNote — The file is a voice note
type FileTypeVoiceNote struct {
}

func (t *FileTypeVoiceNote) GetType() string { return "fileTypeVoiceNote" }

// FileTypeWallpaper — The file is a wallpaper or a background pattern
type FileTypeWallpaper struct {
}

func (t *FileTypeWallpaper) GetType() string { return "fileTypeWallpaper" }

// StorageStatisticsByFileType — Contains the storage usage statistics for a specific file type
type StorageStatisticsByFileType struct {
	FileType *FileType `json:"file_type"` // File type
	Size int64 `json:"size"` // Total size of the files, in bytes
	Count int32 `json:"count"` // Total number of files
}

func (t *StorageStatisticsByFileType) GetType() string { return "storageStatisticsByFileType" }

// StorageStatisticsByChat — Contains the storage usage statistics for a specific chat
type StorageStatisticsByChat struct {
	ChatID int64 `json:"chat_id"` // Chat identifier; 0 if none
	Size int64 `json:"size"` // Total size of the files in the chat, in bytes
	Count int32 `json:"count"` // Total number of files in the chat
	ByFileType []*StorageStatisticsByFileType `json:"by_file_type"` // Statistics split by file types
}

func (t *StorageStatisticsByChat) GetType() string { return "storageStatisticsByChat" }

// StorageStatistics — Contains the exact storage usage statistics split by chats and file type
type StorageStatistics struct {
	Size int64 `json:"size"` // Total size of files, in bytes
	Count int32 `json:"count"` // Total number of files
	ByChat []*StorageStatisticsByChat `json:"by_chat"` // Statistics split by chats
}

func (t *StorageStatistics) GetType() string { return "storageStatistics" }

// StorageStatisticsFast — Contains approximate storage usage statistics, excluding files of unknown file type
type StorageStatisticsFast struct {
	FilesSize int64 `json:"files_size"` // Approximate total size of files, in bytes
	FileCount int32 `json:"file_count"` // Approximate number of files
	DatabaseSize int64 `json:"database_size"` // Size of the database
	LanguagePackDatabaseSize int64 `json:"language_pack_database_size"` // Size of the language pack database
	LogSize int64 `json:"log_size"` // Size of the TDLib internal log
}

func (t *StorageStatisticsFast) GetType() string { return "storageStatisticsFast" }

// DatabaseStatistics — Contains database statistics
type DatabaseStatistics struct {
	Statistics string `json:"statistics"` // Database statistics in an unspecified human-readable format
}

func (t *DatabaseStatistics) GetType() string { return "databaseStatistics" }

// NetworkType — Represents the type of network
type NetworkType struct {
}

func (t *NetworkType) GetType() string { return "NetworkType" }

// NetworkTypeNone — The network is not available
type NetworkTypeNone struct {
}

func (t *NetworkTypeNone) GetType() string { return "networkTypeNone" }

// NetworkTypeMobile — A mobile network
type NetworkTypeMobile struct {
}

func (t *NetworkTypeMobile) GetType() string { return "networkTypeMobile" }

// NetworkTypeMobileRoaming — A mobile roaming network
type NetworkTypeMobileRoaming struct {
}

func (t *NetworkTypeMobileRoaming) GetType() string { return "networkTypeMobileRoaming" }

// NetworkTypeWiFi — A Wi-Fi network
type NetworkTypeWiFi struct {
}

func (t *NetworkTypeWiFi) GetType() string { return "networkTypeWiFi" }

// NetworkTypeOther — A different network type (e.g., Ethernet network)
type NetworkTypeOther struct {
}

func (t *NetworkTypeOther) GetType() string { return "networkTypeOther" }

// NetworkStatisticsEntry — Contains statistics about network usage
type NetworkStatisticsEntry struct {
}

func (t *NetworkStatisticsEntry) GetType() string { return "NetworkStatisticsEntry" }

// NetworkStatisticsEntryFile — Contains information about the total amount of data that was used to send and receive files
type NetworkStatisticsEntryFile struct {
	FileType *FileType `json:"file_type"` // Type of the file the data is part of; pass null if the data isn't related to files
	NetworkType *NetworkType `json:"network_type"` // Type of the network the data was sent through. Call setNetworkType to maintain the actual network type
	SentBytes int64 `json:"sent_bytes"` // Total number of bytes sent
	ReceivedBytes int64 `json:"received_bytes"` // Total number of bytes received
}

func (t *NetworkStatisticsEntryFile) GetType() string { return "networkStatisticsEntryFile" }

// NetworkStatisticsEntryCall — Contains information about the total amount of data that was used for calls
type NetworkStatisticsEntryCall struct {
	NetworkType *NetworkType `json:"network_type"` // Type of the network the data was sent through. Call setNetworkType to maintain the actual network type
	SentBytes int64 `json:"sent_bytes"` // Total number of bytes sent
	ReceivedBytes int64 `json:"received_bytes"` // Total number of bytes received
	Duration float64 `json:"duration"` // Total call duration, in seconds
}

func (t *NetworkStatisticsEntryCall) GetType() string { return "networkStatisticsEntryCall" }

// NetworkStatistics — A full list of available network statistic entries @since_date Point in time (Unix timestamp) from which the statistics are collected @entries Network statistics entries
type NetworkStatistics struct {
	SinceDate int32 `json:"since_date"`
	Entries []*NetworkStatisticsEntry `json:"entries"`
}

func (t *NetworkStatistics) GetType() string { return "networkStatistics" }

// AutoDownloadSettings — Contains auto-download settings
type AutoDownloadSettings struct {
	IsAutoDownloadEnabled bool `json:"is_auto_download_enabled"` // True, if the auto-download is enabled
	MaxPhotoFileSize int32 `json:"max_photo_file_size"` // The maximum size of a photo file to be auto-downloaded, in bytes
	MaxVideoFileSize int64 `json:"max_video_file_size"` // The maximum size of a video file to be auto-downloaded, in bytes
	MaxOtherFileSize int64 `json:"max_other_file_size"` // The maximum size of other file types to be auto-downloaded, in bytes
	VideoUploadBitrate int32 `json:"video_upload_bitrate"` // The maximum suggested bitrate for uploaded videos, in kbit/s
	PreloadLargeVideos bool `json:"preload_large_videos"` // True, if the beginning of video files needs to be preloaded for instant playback
	PreloadNextAudio bool `json:"preload_next_audio"` // True, if the next audio track needs to be preloaded while the user is listening to an audio file
	PreloadStories bool `json:"preload_stories"` // True, if stories needs to be preloaded
	UseLessDataForCalls bool `json:"use_less_data_for_calls"` // True, if "use less data for calls" option needs to be enabled
}

func (t *AutoDownloadSettings) GetType() string { return "autoDownloadSettings" }

// AutoDownloadSettingsPresets — Contains auto-download settings presets for the current user
type AutoDownloadSettingsPresets struct {
	Low *AutoDownloadSettings `json:"low"` // Preset with lowest settings; expected to be used by default when roaming
	Medium *AutoDownloadSettings `json:"medium"` // Preset with medium settings; expected to be used by default when using mobile data
	High *AutoDownloadSettings `json:"high"` // Preset with highest settings; expected to be used by default when connected on Wi-Fi
}

func (t *AutoDownloadSettingsPresets) GetType() string { return "autoDownloadSettingsPresets" }

// AutosaveSettingsScope — Describes scope of autosave settings
type AutosaveSettingsScope struct {
}

func (t *AutosaveSettingsScope) GetType() string { return "AutosaveSettingsScope" }

// AutosaveSettingsScopePrivateChats — Autosave settings applied to all private chats without chat-specific settings
type AutosaveSettingsScopePrivateChats struct {
}

func (t *AutosaveSettingsScopePrivateChats) GetType() string { return "autosaveSettingsScopePrivateChats" }

// AutosaveSettingsScopeGroupChats — Autosave settings applied to all basic group and supergroup chats without chat-specific settings
type AutosaveSettingsScopeGroupChats struct {
}

func (t *AutosaveSettingsScopeGroupChats) GetType() string { return "autosaveSettingsScopeGroupChats" }

// AutosaveSettingsScopeChannelChats — Autosave settings applied to all channel chats without chat-specific settings
type AutosaveSettingsScopeChannelChats struct {
}

func (t *AutosaveSettingsScopeChannelChats) GetType() string { return "autosaveSettingsScopeChannelChats" }

// AutosaveSettingsScopeChat — Autosave settings applied to a chat @chat_id Chat identifier
type AutosaveSettingsScopeChat struct {
	ChatID int64 `json:"chat_id"`
}

func (t *AutosaveSettingsScopeChat) GetType() string { return "autosaveSettingsScopeChat" }

// ScopeAutosaveSettings — Contains autosave settings for an autosave settings scope
type ScopeAutosaveSettings struct {
	AutosavePhotos bool `json:"autosave_photos"` // True, if photo autosave is enabled
	AutosaveVideos bool `json:"autosave_videos"` // True, if video autosave is enabled
	MaxVideoFileSize int64 `json:"max_video_file_size"` // The maximum size of a video file to be autosaved, in bytes; 512 KB - 4000 MB
}

func (t *ScopeAutosaveSettings) GetType() string { return "scopeAutosaveSettings" }

// AutosaveSettingsException — Contains autosave settings for a chat, which overrides default settings for the corresponding scope
type AutosaveSettingsException struct {
	ChatID int64 `json:"chat_id"` // Chat identifier
	Settings *ScopeAutosaveSettings `json:"settings"` // Autosave settings for the chat
}

func (t *AutosaveSettingsException) GetType() string { return "autosaveSettingsException" }

// AutosaveSettings — Describes autosave settings
type AutosaveSettings struct {
	PrivateChatSettings *ScopeAutosaveSettings `json:"private_chat_settings"` // Default autosave settings for private chats
	GroupSettings *ScopeAutosaveSettings `json:"group_settings"` // Default autosave settings for basic group and supergroup chats
	ChannelSettings *ScopeAutosaveSettings `json:"channel_settings"` // Default autosave settings for channel chats
	Exceptions []*AutosaveSettingsException `json:"exceptions"` // Autosave settings for specific chats
}

func (t *AutosaveSettings) GetType() string { return "autosaveSettings" }

// ConnectionState — Describes the current state of the connection to Telegram servers
type ConnectionState struct {
}

func (t *ConnectionState) GetType() string { return "ConnectionState" }

// ConnectionStateWaitingForNetwork — Waiting for the network to become available. Use setNetworkType to change the available network type
type ConnectionStateWaitingForNetwork struct {
}

func (t *ConnectionStateWaitingForNetwork) GetType() string { return "connectionStateWaitingForNetwork" }

// ConnectionStateConnectingToProxy — Establishing a connection with a proxy server
type ConnectionStateConnectingToProxy struct {
}

func (t *ConnectionStateConnectingToProxy) GetType() string { return "connectionStateConnectingToProxy" }

// ConnectionStateConnecting — Establishing a connection to the Telegram servers
type ConnectionStateConnecting struct {
}

func (t *ConnectionStateConnecting) GetType() string { return "connectionStateConnecting" }

// ConnectionStateUpdating — Downloading data expected to be received while the application was offline
type ConnectionStateUpdating struct {
}

func (t *ConnectionStateUpdating) GetType() string { return "connectionStateUpdating" }

// ConnectionStateReady — There is a working connection to the Telegram servers
type ConnectionStateReady struct {
}

func (t *ConnectionStateReady) GetType() string { return "connectionStateReady" }

// AgeVerificationParameters — Describes parameters for age verification of the current user
type AgeVerificationParameters struct {
	MinAge int32 `json:"min_age"` // The minimum age required to view restricted content
	VerificationBotUsername string `json:"verification_bot_username"` // Username of the bot which main Web App may be used to verify age of the user
	Country string `json:"country"` // Unique name for the country or region, which legislation required age verification. May be used to get the corresponding localization key
}

func (t *AgeVerificationParameters) GetType() string { return "ageVerificationParameters" }

// TopChatCategory — Represents the categories of chats for which a list of frequently used chats can be retrieved
type TopChatCategory struct {
}

func (t *TopChatCategory) GetType() string { return "TopChatCategory" }

// TopChatCategoryUsers — A category containing frequently used private chats with non-bot users
type TopChatCategoryUsers struct {
}

func (t *TopChatCategoryUsers) GetType() string { return "topChatCategoryUsers" }

// TopChatCategoryBots — A category containing frequently used private chats with bot users
type TopChatCategoryBots struct {
}

func (t *TopChatCategoryBots) GetType() string { return "topChatCategoryBots" }

// TopChatCategoryGroups — A category containing frequently used basic groups and supergroups
type TopChatCategoryGroups struct {
}

func (t *TopChatCategoryGroups) GetType() string { return "topChatCategoryGroups" }

// TopChatCategoryChannels — A category containing frequently used channels
type TopChatCategoryChannels struct {
}

func (t *TopChatCategoryChannels) GetType() string { return "topChatCategoryChannels" }

// TopChatCategoryInlineBots — A category containing frequently used chats with inline bots sorted by their usage in inline mode
type TopChatCategoryInlineBots struct {
}

func (t *TopChatCategoryInlineBots) GetType() string { return "topChatCategoryInlineBots" }

// TopChatCategoryWebAppBots — A category containing frequently used chats with bots, which Web Apps were opened
type TopChatCategoryWebAppBots struct {
}

func (t *TopChatCategoryWebAppBots) GetType() string { return "topChatCategoryWebAppBots" }

// TopChatCategoryCalls — A category containing frequently used chats used for calls
type TopChatCategoryCalls struct {
}

func (t *TopChatCategoryCalls) GetType() string { return "topChatCategoryCalls" }

// TopChatCategoryForwardChats — A category containing frequently used chats used to forward messages
type TopChatCategoryForwardChats struct {
}

func (t *TopChatCategoryForwardChats) GetType() string { return "topChatCategoryForwardChats" }

// FoundPosition — Contains 0-based match position @position The position of the match
type FoundPosition struct {
	Position int32 `json:"position"`
}

func (t *FoundPosition) GetType() string { return "foundPosition" }

// FoundPositions — Contains 0-based positions of matched objects @total_count Total number of matched objects @positions The positions of the matched objects
type FoundPositions struct {
	TotalCount int32 `json:"total_count"`
	Positions []int32 `json:"positions"`
}

func (t *FoundPositions) GetType() string { return "foundPositions" }

// TMeURLType — Describes the type of URL linking to an internal Telegram entity
type TMeURLType struct {
}

func (t *TMeURLType) GetType() string { return "TMeUrlType" }

// TMeURLTypeUser — A URL linking to a user @user_id Identifier of the user
type TMeURLTypeUser struct {
	UserID int64 `json:"user_id"`
}

func (t *TMeURLTypeUser) GetType() string { return "tMeUrlTypeUser" }

// TMeURLTypeSupergroup — A URL linking to a public supergroup or channel @supergroup_id Identifier of the supergroup or channel
type TMeURLTypeSupergroup struct {
	SupergroupID int64 `json:"supergroup_id"`
}

func (t *TMeURLTypeSupergroup) GetType() string { return "tMeUrlTypeSupergroup" }

// TMeURLTypeChatInvite — A chat invite link @info Information about the chat invite link
type TMeURLTypeChatInvite struct {
	Info *ChatInviteLinkInfo `json:"info"`
}

func (t *TMeURLTypeChatInvite) GetType() string { return "tMeUrlTypeChatInvite" }

// TMeURLTypeStickerSet — A URL linking to a sticker set @sticker_set_id Identifier of the sticker set
type TMeURLTypeStickerSet struct {
	StickerSetID JSONInt64 `json:"sticker_set_id"`
}

func (t *TMeURLTypeStickerSet) GetType() string { return "tMeUrlTypeStickerSet" }

// TMeURL — Represents a URL linking to an internal Telegram entity @url URL @type Type of the URL
type TMeURL struct {
	URL string `json:"url"`
	Type *TMeURLType `json:"type"`
}

func (t *TMeURL) GetType() string { return "tMeUrl" }

// TMeURLs — Contains a list of t.me URLs @urls List of URLs
type TMeURLs struct {
	URLs []*TMeURL `json:"urls"`
}

func (t *TMeURLs) GetType() string { return "tMeUrls" }

// SuggestedAction — Describes an action suggested to the current user
type SuggestedAction struct {
}

func (t *SuggestedAction) GetType() string { return "SuggestedAction" }

// SuggestedActionEnableArchiveAndMuteNewChats — Suggests the user to enable archive_and_mute_new_chats_from_unknown_users setting in archiveChatListSettings
type SuggestedActionEnableArchiveAndMuteNewChats struct {
}

func (t *SuggestedActionEnableArchiveAndMuteNewChats) GetType() string { return "suggestedActionEnableArchiveAndMuteNewChats" }

// SuggestedActionCheckPassword — Suggests the user to check whether they still remember their 2-step verification password
type SuggestedActionCheckPassword struct {
}

func (t *SuggestedActionCheckPassword) GetType() string { return "suggestedActionCheckPassword" }

// SuggestedActionCheckPhoneNumber — Suggests the user to check whether authorization phone number is correct and change the phone number if it is inaccessible
type SuggestedActionCheckPhoneNumber struct {
}

func (t *SuggestedActionCheckPhoneNumber) GetType() string { return "suggestedActionCheckPhoneNumber" }

// SuggestedActionViewChecksHint — Suggests the user to view a hint about the meaning of one and two check marks on sent messages
type SuggestedActionViewChecksHint struct {
}

func (t *SuggestedActionViewChecksHint) GetType() string { return "suggestedActionViewChecksHint" }

// SuggestedActionConvertToBroadcastGroup — Suggests the user to convert specified supergroup to a broadcast group @supergroup_id Supergroup identifier
type SuggestedActionConvertToBroadcastGroup struct {
	SupergroupID int64 `json:"supergroup_id"`
}

func (t *SuggestedActionConvertToBroadcastGroup) GetType() string { return "suggestedActionConvertToBroadcastGroup" }

// SuggestedActionSetPassword — Suggests the user to set a 2-step verification password to be able to log in again
type SuggestedActionSetPassword struct {
	AuthorizationDelay int32 `json:"authorization_delay"` // The number of days to pass between consecutive authorizations if the user declines to set password; if 0, then the user is advised to set the password for security reasons
}

func (t *SuggestedActionSetPassword) GetType() string { return "suggestedActionSetPassword" }

// SuggestedActionUpgradePremium — Suggests the user to upgrade the Premium subscription from monthly payments to annual payments
type SuggestedActionUpgradePremium struct {
}

func (t *SuggestedActionUpgradePremium) GetType() string { return "suggestedActionUpgradePremium" }

// SuggestedActionRestorePremium — Suggests the user to restore a recently expired Premium subscription
type SuggestedActionRestorePremium struct {
}

func (t *SuggestedActionRestorePremium) GetType() string { return "suggestedActionRestorePremium" }

// SuggestedActionSubscribeToAnnualPremium — Suggests the user to subscribe to the Premium subscription with annual payments
type SuggestedActionSubscribeToAnnualPremium struct {
}

func (t *SuggestedActionSubscribeToAnnualPremium) GetType() string { return "suggestedActionSubscribeToAnnualPremium" }

// SuggestedActionGiftPremiumForChristmas — Suggests the user to gift Telegram Premium to friends for Christmas
type SuggestedActionGiftPremiumForChristmas struct {
}

func (t *SuggestedActionGiftPremiumForChristmas) GetType() string { return "suggestedActionGiftPremiumForChristmas" }

// SuggestedActionSetBirthdate — Suggests the user to set birthdate
type SuggestedActionSetBirthdate struct {
}

func (t *SuggestedActionSetBirthdate) GetType() string { return "suggestedActionSetBirthdate" }

// SuggestedActionSetProfilePhoto — Suggests the user to set profile photo
type SuggestedActionSetProfilePhoto struct {
}

func (t *SuggestedActionSetProfilePhoto) GetType() string { return "suggestedActionSetProfilePhoto" }

// SuggestedActionExtendPremium — Suggests the user to extend their expiring Telegram Premium subscription @manage_premium_subscription_url A URL for managing Telegram Premium subscription
type SuggestedActionExtendPremium struct {
	ManagePremiumSubscriptionURL string `json:"manage_premium_subscription_url"`
}

func (t *SuggestedActionExtendPremium) GetType() string { return "suggestedActionExtendPremium" }

// SuggestedActionExtendStarSubscriptions — Suggests the user to extend their expiring Telegram Star subscriptions. Call getStarSubscriptions with only_expiring == true
type SuggestedActionExtendStarSubscriptions struct {
}

func (t *SuggestedActionExtendStarSubscriptions) GetType() string { return "suggestedActionExtendStarSubscriptions" }

// SuggestedActionCustom — A custom suggestion to be shown at the top of the chat list
type SuggestedActionCustom struct {
	Name string `json:"name"` // Unique name of the suggestion
	Title *FormattedText `json:"title"` // Title of the suggestion
	Description *FormattedText `json:"description"` // A custom suggestion to be shown at the top of the chat list
	URL string `json:"url"` // The link to open when the suggestion is clicked
}

func (t *SuggestedActionCustom) GetType() string { return "suggestedActionCustom" }

// SuggestedActionSetLoginEmailAddress — Suggests the user to add login email address. Call isLoginEmailAddressRequired, and then setLoginEmailAddress or checkLoginEmailAddressCode to change the login email address
type SuggestedActionSetLoginEmailAddress struct {
	CanBeHidden bool `json:"can_be_hidden"` // True, if the suggested action can be hidden using hideSuggestedAction. Otherwise, the user must not be able to use the app without setting up the email address
}

func (t *SuggestedActionSetLoginEmailAddress) GetType() string { return "suggestedActionSetLoginEmailAddress" }

// SuggestedActionAddLoginPasskey — Suggests the user to add a passkey for login using addLoginPasskey
type SuggestedActionAddLoginPasskey struct {
}

func (t *SuggestedActionAddLoginPasskey) GetType() string { return "suggestedActionAddLoginPasskey" }

// Count — Contains a counter @count Count
type Count struct {
	Count int32 `json:"count"`
}

func (t *Count) GetType() string { return "count" }

// Text — Contains some text @text Text
type Text struct {
	Text string `json:"text"`
}

func (t *Text) GetType() string { return "text" }

// Data — Contains some binary data @data Data
type Data struct {
	Data []byte `json:"data"`
}

func (t *Data) GetType() string { return "data" }

// Seconds — Contains a value representing a number of seconds @seconds Number of seconds
type Seconds struct {
	Seconds float64 `json:"seconds"`
}

func (t *Seconds) GetType() string { return "seconds" }

// FileDownloadedPrefixSize — Contains size of downloaded prefix of a file @size The prefix size, in bytes
type FileDownloadedPrefixSize struct {
	Size int64 `json:"size"`
}

func (t *FileDownloadedPrefixSize) GetType() string { return "fileDownloadedPrefixSize" }

// StarCount — Contains a number of Telegram Stars @star_count Number of Telegram Stars
type StarCount struct {
	StarCount int64 `json:"star_count"`
}

func (t *StarCount) GetType() string { return "starCount" }

// DeepLinkInfo — Contains information about a tg: deep link @text Text to be shown to the user @need_update_application True, if the user must be asked to update the application
type DeepLinkInfo struct {
	Text *FormattedText `json:"text"`
	NeedUpdateApplication bool `json:"need_update_application"`
}

func (t *DeepLinkInfo) GetType() string { return "deepLinkInfo" }

// TextParseMode — Describes the way the text needs to be parsed for text entities
type TextParseMode struct {
}

func (t *TextParseMode) GetType() string { return "TextParseMode" }

// TextParseModeMarkdown — The text uses Markdown-style formatting
type TextParseModeMarkdown struct {
	Version int32 `json:"version"` // Version of the parser: 0 or 1 - Telegram Bot API "Markdown" parse mode, 2 - Telegram Bot API "MarkdownV2" parse mode
}

func (t *TextParseModeMarkdown) GetType() string { return "textParseModeMarkdown" }

// TextParseModeHTML — The text uses HTML-style formatting. The same as Telegram Bot API "HTML" parse mode
type TextParseModeHTML struct {
}

func (t *TextParseModeHTML) GetType() string { return "textParseModeHTML" }

// ProxyType — Describes the type of proxy server
type ProxyType struct {
}

func (t *ProxyType) GetType() string { return "ProxyType" }

// ProxyTypeSocks5 — A SOCKS5 proxy server @username Username for logging in; may be empty @password Password for logging in; may be empty
type ProxyTypeSocks5 struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (t *ProxyTypeSocks5) GetType() string { return "proxyTypeSocks5" }

// ProxyTypeHTTP — A HTTP transparent proxy server @username Username for logging in; may be empty @password Password for logging in; may be empty @http_only Pass true if the proxy supports only HTTP requests and doesn't support transparent TCP connections via HTTP CONNECT method
type ProxyTypeHTTP struct {
	Username string `json:"username"`
	Password string `json:"password"`
	HTTPOnly bool `json:"http_only"`
}

func (t *ProxyTypeHTTP) GetType() string { return "proxyTypeHttp" }

// ProxyTypeMtproto — An MTProto proxy server @secret The proxy's secret in hexadecimal encoding
type ProxyTypeMtproto struct {
	Secret string `json:"secret"`
}

func (t *ProxyTypeMtproto) GetType() string { return "proxyTypeMtproto" }

// AddedProxy — Contains information about a proxy server added to the list of proxies
type AddedProxy struct {
	ID int32 `json:"id"` // Unique identifier of the proxy
	LastUsedDate int32 `json:"last_used_date"` // Point in time (Unix timestamp) when the proxy was last used; 0 if never
	IsEnabled bool `json:"is_enabled"` // True, if the proxy is enabled now
	Proxy *Proxy `json:"proxy"` // The proxy
}

func (t *AddedProxy) GetType() string { return "addedProxy" }

// AddedProxies — Represents a list of added proxy servers @proxies List of proxy servers
type AddedProxies struct {
	Proxies []*AddedProxy `json:"proxies"`
}

func (t *AddedProxies) GetType() string { return "addedProxies" }

// InputSticker — A sticker to be added to a sticker set
type InputSticker struct {
	Sticker *InputFile `json:"sticker"` // File with the sticker; must fit in a 512x512 square. For WEBP stickers the file must be in WEBP or PNG format, which will be converted to WEBP server-side.
	Format *StickerFormat `json:"format"` // Format of the sticker
	Emojis string `json:"emojis"` // String with 1-20 emoji corresponding to the sticker
	MaskPosition *MaskPosition `json:"mask_position"` // Position where the mask is placed; pass null if not specified
	Keywords []string `json:"keywords"` // List of up to 20 keywords with total length up to 64 characters, which can be used to find the sticker
}

func (t *InputSticker) GetType() string { return "inputSticker" }

// DateRange — Represents a date range @start_date Point in time (Unix timestamp) at which the date range begins @end_date Point in time (Unix timestamp) at which the date range ends
type DateRange struct {
	StartDate int32 `json:"start_date"`
	EndDate int32 `json:"end_date"`
}

func (t *DateRange) GetType() string { return "dateRange" }

// StatisticalValue — A value with information about its recent changes @value The current value @previous_value The value for the previous day @growth_rate_percentage The growth rate of the value, as a percentage
type StatisticalValue struct {
	Value float64 `json:"value"`
	PreviousValue float64 `json:"previous_value"`
	GrowthRatePercentage float64 `json:"growth_rate_percentage"`
}

func (t *StatisticalValue) GetType() string { return "statisticalValue" }

// StatisticalGraph — Describes a statistical graph
type StatisticalGraph struct {
}

func (t *StatisticalGraph) GetType() string { return "StatisticalGraph" }

// StatisticalGraphData — A graph data @json_data Graph data in JSON format @zoom_token If non-empty, a token which can be used to receive a zoomed in graph
type StatisticalGraphData struct {
	JsonData string `json:"json_data"`
	ZoomToken string `json:"zoom_token"`
}

func (t *StatisticalGraphData) GetType() string { return "statisticalGraphData" }

// StatisticalGraphAsync — The graph data to be asynchronously loaded through getStatisticalGraph @token The token to use for data loading
type StatisticalGraphAsync struct {
	Token string `json:"token"`
}

func (t *StatisticalGraphAsync) GetType() string { return "statisticalGraphAsync" }

// StatisticalGraphError — An error message to be shown to the user instead of the graph @error_message The error message
type StatisticalGraphError struct {
	ErrorMessage string `json:"error_message"`
}

func (t *StatisticalGraphError) GetType() string { return "statisticalGraphError" }

// ChatStatisticsObjectType — Describes type of object, for which statistics are provided
type ChatStatisticsObjectType struct {
}

func (t *ChatStatisticsObjectType) GetType() string { return "ChatStatisticsObjectType" }

// ChatStatisticsObjectTypeMessage — Describes a message sent in the chat @message_id Message identifier
type ChatStatisticsObjectTypeMessage struct {
	MessageID int64 `json:"message_id"`
}

func (t *ChatStatisticsObjectTypeMessage) GetType() string { return "chatStatisticsObjectTypeMessage" }

// ChatStatisticsObjectTypeStory — Describes a story posted on behalf of the chat @story_id Story identifier
type ChatStatisticsObjectTypeStory struct {
	StoryID int32 `json:"story_id"`
}

func (t *ChatStatisticsObjectTypeStory) GetType() string { return "chatStatisticsObjectTypeStory" }

// ChatStatisticsInteractionInfo — Contains statistics about interactions with a message sent in the chat or a story posted on behalf of the chat
type ChatStatisticsInteractionInfo struct {
	ObjectType *ChatStatisticsObjectType `json:"object_type"` // Type of the object
	ViewCount int32 `json:"view_count"` // Number of times the object was viewed
	ForwardCount int32 `json:"forward_count"` // Number of times the object was forwarded
	ReactionCount int32 `json:"reaction_count"` // Number of times reactions were added to the object
}

func (t *ChatStatisticsInteractionInfo) GetType() string { return "chatStatisticsInteractionInfo" }

// ChatStatisticsMessageSenderInfo — Contains statistics about messages sent by a user
type ChatStatisticsMessageSenderInfo struct {
	UserID int64 `json:"user_id"` // User identifier
	SentMessageCount int32 `json:"sent_message_count"` // Number of sent messages
	AverageCharacterCount int32 `json:"average_character_count"` // Average number of characters in sent messages; 0 if unknown
}

func (t *ChatStatisticsMessageSenderInfo) GetType() string { return "chatStatisticsMessageSenderInfo" }

// ChatStatisticsAdministratorActionsInfo — Contains statistics about administrator actions done by a user
type ChatStatisticsAdministratorActionsInfo struct {
	UserID int64 `json:"user_id"` // Administrator user identifier
	DeletedMessageCount int32 `json:"deleted_message_count"` // Number of messages deleted by the administrator
	BannedUserCount int32 `json:"banned_user_count"` // Number of users banned by the administrator
	RestrictedUserCount int32 `json:"restricted_user_count"` // Number of users restricted by the administrator
}

func (t *ChatStatisticsAdministratorActionsInfo) GetType() string { return "chatStatisticsAdministratorActionsInfo" }

// ChatStatisticsInviterInfo — Contains statistics about number of new members invited by a user
type ChatStatisticsInviterInfo struct {
	UserID int64 `json:"user_id"` // User identifier
	AddedMemberCount int32 `json:"added_member_count"` // Number of new members invited by the user
}

func (t *ChatStatisticsInviterInfo) GetType() string { return "chatStatisticsInviterInfo" }

// ChatStatistics — Contains a detailed statistics about a chat
type ChatStatistics struct {
}

func (t *ChatStatistics) GetType() string { return "ChatStatistics" }

// ChatStatisticsSupergroup — A detailed statistics about a supergroup chat
type ChatStatisticsSupergroup struct {
	Period *DateRange `json:"period"` // A period to which the statistics applies
	MemberCount *StatisticalValue `json:"member_count"` // Number of members in the chat
	MessageCount *StatisticalValue `json:"message_count"` // Number of messages sent to the chat
	ViewerCount *StatisticalValue `json:"viewer_count"` // Number of users who viewed messages in the chat
	SenderCount *StatisticalValue `json:"sender_count"` // Number of users who sent messages to the chat
	MemberCountGraph *StatisticalGraph `json:"member_count_graph"` // A graph containing number of members in the chat
	JoinGraph *StatisticalGraph `json:"join_graph"` // A graph containing number of members joined and left the chat
	JoinBySourceGraph *StatisticalGraph `json:"join_by_source_graph"` // A graph containing number of new member joins per source
	LanguageGraph *StatisticalGraph `json:"language_graph"` // A graph containing distribution of active users per language
	MessageContentGraph *StatisticalGraph `json:"message_content_graph"` // A graph containing distribution of sent messages by content type
	ActionGraph *StatisticalGraph `json:"action_graph"` // A graph containing number of different actions in the chat
	DayGraph *StatisticalGraph `json:"day_graph"` // A graph containing distribution of message views per hour
	WeekGraph *StatisticalGraph `json:"week_graph"` // A graph containing distribution of message views per day of week
	TopSenders []*ChatStatisticsMessageSenderInfo `json:"top_senders"` // List of users sent most messages in the last week
	TopAdministrators []*ChatStatisticsAdministratorActionsInfo `json:"top_administrators"` // List of most active administrators in the last week
	TopInviters []*ChatStatisticsInviterInfo `json:"top_inviters"` // List of most active inviters of new members in the last week
}

func (t *ChatStatisticsSupergroup) GetType() string { return "chatStatisticsSupergroup" }

// ChatStatisticsChannel — A detailed statistics about a channel chat
type ChatStatisticsChannel struct {
	Period *DateRange `json:"period"` // A period to which the statistics applies
	MemberCount *StatisticalValue `json:"member_count"` // Number of members in the chat
	MeanMessageViewCount *StatisticalValue `json:"mean_message_view_count"` // Mean number of times the recently sent messages were viewed
	MeanMessageShareCount *StatisticalValue `json:"mean_message_share_count"` // Mean number of times the recently sent messages were shared
	MeanMessageReactionCount *StatisticalValue `json:"mean_message_reaction_count"` // Mean number of times reactions were added to the recently sent messages
	MeanStoryViewCount *StatisticalValue `json:"mean_story_view_count"` // Mean number of times the recently posted stories were viewed
	MeanStoryShareCount *StatisticalValue `json:"mean_story_share_count"` // Mean number of times the recently posted stories were shared
	MeanStoryReactionCount *StatisticalValue `json:"mean_story_reaction_count"` // Mean number of times reactions were added to the recently posted stories
	EnabledNotificationsPercentage float64 `json:"enabled_notifications_percentage"` // A percentage of users with enabled notifications for the chat; 0-100
	MemberCountGraph *StatisticalGraph `json:"member_count_graph"` // A graph containing number of members in the chat
	JoinGraph *StatisticalGraph `json:"join_graph"` // A graph containing number of members joined and left the chat
	MuteGraph *StatisticalGraph `json:"mute_graph"` // A graph containing number of members muted and unmuted the chat
	ViewCountByHourGraph *StatisticalGraph `json:"view_count_by_hour_graph"` // A graph containing number of message views in a given hour in the last two weeks
	ViewCountBySourceGraph *StatisticalGraph `json:"view_count_by_source_graph"` // A graph containing number of message views per source
	JoinBySourceGraph *StatisticalGraph `json:"join_by_source_graph"` // A graph containing number of new member joins per source
	LanguageGraph *StatisticalGraph `json:"language_graph"` // A graph containing number of users viewed chat messages per language
	MessageInteractionGraph *StatisticalGraph `json:"message_interaction_graph"` // A graph containing number of chat message views and shares
	MessageReactionGraph *StatisticalGraph `json:"message_reaction_graph"` // A graph containing number of reactions on messages
	StoryInteractionGraph *StatisticalGraph `json:"story_interaction_graph"` // A graph containing number of story views and shares
	StoryReactionGraph *StatisticalGraph `json:"story_reaction_graph"` // A graph containing number of reactions on stories
	InstantViewInteractionGraph *StatisticalGraph `json:"instant_view_interaction_graph"` // A graph containing number of views of associated with the chat instant views
	RecentInteractions []*ChatStatisticsInteractionInfo `json:"recent_interactions"` // Detailed statistics about number of views and shares of recently sent messages and posted stories
}

func (t *ChatStatisticsChannel) GetType() string { return "chatStatisticsChannel" }

// ChatRevenueAmount — Contains information about revenue earned from sponsored messages in a chat
type ChatRevenueAmount struct {
	Cryptocurrency string `json:"cryptocurrency"` // Cryptocurrency in which revenue is calculated
	TotalAmount JSONInt64 `json:"total_amount"` // Total amount of the cryptocurrency earned, in the smallest units of the cryptocurrency
	BalanceAmount JSONInt64 `json:"balance_amount"` // Amount of the cryptocurrency that isn't withdrawn yet, in the smallest units of the cryptocurrency
	AvailableAmount JSONInt64 `json:"available_amount"` // Amount of the cryptocurrency available for withdrawal, in the smallest units of the cryptocurrency
	WithdrawalEnabled bool `json:"withdrawal_enabled"` // True, if Telegram Stars can be withdrawn now or later
}

func (t *ChatRevenueAmount) GetType() string { return "chatRevenueAmount" }

// ChatRevenueStatistics — A detailed statistics about revenue earned from sponsored messages in a chat
type ChatRevenueStatistics struct {
	RevenueByHourGraph *StatisticalGraph `json:"revenue_by_hour_graph"` // A graph containing amount of revenue in a given hour
	RevenueGraph *StatisticalGraph `json:"revenue_graph"` // A graph containing amount of revenue
	RevenueAmount *ChatRevenueAmount `json:"revenue_amount"` // Amount of earned revenue
	UsdRate float64 `json:"usd_rate"` // Current conversion rate of the cryptocurrency in which revenue is calculated to USD
}

func (t *ChatRevenueStatistics) GetType() string { return "chatRevenueStatistics" }

// MessageStatistics — A detailed statistics about a message
type MessageStatistics struct {
	MessageInteractionGraph *StatisticalGraph `json:"message_interaction_graph"` // A graph containing number of message views and shares
	MessageReactionGraph *StatisticalGraph `json:"message_reaction_graph"` // A graph containing number of message reactions
}

func (t *MessageStatistics) GetType() string { return "messageStatistics" }

// StoryStatistics — A detailed statistics about a story
type StoryStatistics struct {
	StoryInteractionGraph *StatisticalGraph `json:"story_interaction_graph"` // A graph containing number of story views and shares
	StoryReactionGraph *StatisticalGraph `json:"story_reaction_graph"` // A graph containing number of story reactions
}

func (t *StoryStatistics) GetType() string { return "storyStatistics" }

// RevenueWithdrawalState — Describes state of a revenue withdrawal
type RevenueWithdrawalState struct {
}

func (t *RevenueWithdrawalState) GetType() string { return "RevenueWithdrawalState" }

// RevenueWithdrawalStatePending — Withdrawal is pending
type RevenueWithdrawalStatePending struct {
}

func (t *RevenueWithdrawalStatePending) GetType() string { return "revenueWithdrawalStatePending" }

// RevenueWithdrawalStateSucceeded — Withdrawal succeeded
type RevenueWithdrawalStateSucceeded struct {
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the withdrawal was completed
	URL string `json:"url"` // The URL where the withdrawal transaction can be viewed
}

func (t *RevenueWithdrawalStateSucceeded) GetType() string { return "revenueWithdrawalStateSucceeded" }

// RevenueWithdrawalStateFailed — Withdrawal failed
type RevenueWithdrawalStateFailed struct {
}

func (t *RevenueWithdrawalStateFailed) GetType() string { return "revenueWithdrawalStateFailed" }

// ChatRevenueTransactionType — Describes type of transaction for revenue earned from sponsored messages in a chat
type ChatRevenueTransactionType struct {
}

func (t *ChatRevenueTransactionType) GetType() string { return "ChatRevenueTransactionType" }

// ChatRevenueTransactionTypeUnsupported — Describes an unsupported transaction
type ChatRevenueTransactionTypeUnsupported struct {
}

func (t *ChatRevenueTransactionTypeUnsupported) GetType() string { return "chatRevenueTransactionTypeUnsupported" }

// ChatRevenueTransactionTypeSponsoredMessageEarnings — Describes earnings from sponsored messages in a chat in some time frame
type ChatRevenueTransactionTypeSponsoredMessageEarnings struct {
	StartDate int32 `json:"start_date"` // Point in time (Unix timestamp) when the earnings started
	EndDate int32 `json:"end_date"` // Point in time (Unix timestamp) when the earnings ended
}

func (t *ChatRevenueTransactionTypeSponsoredMessageEarnings) GetType() string { return "chatRevenueTransactionTypeSponsoredMessageEarnings" }

// ChatRevenueTransactionTypeSuggestedPostEarnings — Describes earnings from a published suggested post @user_id Identifier of the user who paid for the suggested post
type ChatRevenueTransactionTypeSuggestedPostEarnings struct {
	UserID int64 `json:"user_id"`
}

func (t *ChatRevenueTransactionTypeSuggestedPostEarnings) GetType() string { return "chatRevenueTransactionTypeSuggestedPostEarnings" }

// ChatRevenueTransactionTypeFragmentWithdrawal — Describes a withdrawal of earnings through Fragment
type ChatRevenueTransactionTypeFragmentWithdrawal struct {
	WithdrawalDate int32 `json:"withdrawal_date"` // Point in time (Unix timestamp) when the earnings withdrawal started
	State *RevenueWithdrawalState `json:"state"` // State of the withdrawal
}

func (t *ChatRevenueTransactionTypeFragmentWithdrawal) GetType() string { return "chatRevenueTransactionTypeFragmentWithdrawal" }

// ChatRevenueTransactionTypeFragmentRefund — Describes a refund for failed withdrawal of earnings through Fragment
type ChatRevenueTransactionTypeFragmentRefund struct {
	RefundDate int32 `json:"refund_date"` // Point in time (Unix timestamp) when the transaction was refunded
}

func (t *ChatRevenueTransactionTypeFragmentRefund) GetType() string { return "chatRevenueTransactionTypeFragmentRefund" }

// ChatRevenueTransaction — Contains a chat revenue transactions
type ChatRevenueTransaction struct {
	Cryptocurrency string `json:"cryptocurrency"` // Cryptocurrency in which revenue is calculated
	CryptocurrencyAmount JSONInt64 `json:"cryptocurrency_amount"` // The withdrawn amount, in the smallest units of the cryptocurrency
	Type *ChatRevenueTransactionType `json:"type"` // Type of the transaction
}

func (t *ChatRevenueTransaction) GetType() string { return "chatRevenueTransaction" }

// ChatRevenueTransactions — Contains a list of chat revenue transactions
type ChatRevenueTransactions struct {
	TonAmount int64 `json:"ton_amount"` // The amount of owned Toncoins; in the smallest units of the cryptocurrency
	Transactions []*ChatRevenueTransaction `json:"transactions"` // List of transactions
	NextOffset string `json:"next_offset"` // The offset for the next request. If empty, then there are no more results
}

func (t *ChatRevenueTransactions) GetType() string { return "chatRevenueTransactions" }

// StarRevenueStatus — Contains information about Telegram Stars earned by a user or a chat
type StarRevenueStatus struct {
	TotalAmount *StarAmount `json:"total_amount"` // Total Telegram Star amount earned
	CurrentAmount *StarAmount `json:"current_amount"` // The Telegram Star amount that isn't withdrawn yet
	AvailableAmount *StarAmount `json:"available_amount"` // The Telegram Star amount that is available for withdrawal
	WithdrawalEnabled bool `json:"withdrawal_enabled"` // True, if Telegram Stars can be withdrawn now or later
	NextWithdrawalIn int32 `json:"next_withdrawal_in"` // Time left before the next withdrawal can be started, in seconds; 0 if withdrawal can be started now
}

func (t *StarRevenueStatus) GetType() string { return "starRevenueStatus" }

// StarRevenueStatistics — A detailed statistics about Telegram Stars earned by a user or a chat
type StarRevenueStatistics struct {
	RevenueByDayGraph *StatisticalGraph `json:"revenue_by_day_graph"` // A graph containing amount of revenue in a given day
	Status *StarRevenueStatus `json:"status"` // Telegram Star revenue status
	UsdRate float64 `json:"usd_rate"` // Current conversion rate of a Telegram Star to USD
}

func (t *StarRevenueStatistics) GetType() string { return "starRevenueStatistics" }

// TonRevenueStatus — Contains information about Toncoins earned by the current user
type TonRevenueStatus struct {
	TotalAmount JSONInt64 `json:"total_amount"` // Total Toncoin amount earned; in the smallest units of the cryptocurrency
	BalanceAmount JSONInt64 `json:"balance_amount"` // The Toncoin amount that isn't withdrawn yet; in the smallest units of the cryptocurrency
	AvailableAmount JSONInt64 `json:"available_amount"` // The Toncoin amount that is available for withdrawal; in the smallest units of the cryptocurrency
	WithdrawalEnabled bool `json:"withdrawal_enabled"` // True, if Toncoins can be withdrawn
}

func (t *TonRevenueStatus) GetType() string { return "tonRevenueStatus" }

// TonRevenueStatistics — A detailed statistics about Toncoins earned by the current user
type TonRevenueStatistics struct {
	RevenueByDayGraph *StatisticalGraph `json:"revenue_by_day_graph"` // A graph containing amount of revenue in a given day
	Status *TonRevenueStatus `json:"status"` // Amount of earned revenue
	UsdRate float64 `json:"usd_rate"` // Current conversion rate of nanotoncoin to USD cents
}

func (t *TonRevenueStatistics) GetType() string { return "tonRevenueStatistics" }

// Point — A point on a Cartesian plane @x The point's first coordinate @y The point's second coordinate
type Point struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
}

func (t *Point) GetType() string { return "point" }

// VectorPathCommand — Represents a vector path command
type VectorPathCommand struct {
}

func (t *VectorPathCommand) GetType() string { return "VectorPathCommand" }

// VectorPathCommandLine — A straight line to a given point @end_point The end point of the straight line
type VectorPathCommandLine struct {
	EndPoint *Point `json:"end_point"`
}

func (t *VectorPathCommandLine) GetType() string { return "vectorPathCommandLine" }

// VectorPathCommandCubicBezierCurve — A cubic Bézier curve to a given point @start_control_point The start control point of the curve @end_control_point The end control point of the curve @end_point The end point of the curve
type VectorPathCommandCubicBezierCurve struct {
	StartControlPoint *Point `json:"start_control_point"`
	EndControlPoint *Point `json:"end_control_point"`
	EndPoint *Point `json:"end_point"`
}

func (t *VectorPathCommandCubicBezierCurve) GetType() string { return "vectorPathCommandCubicBezierCurve" }

// BotCommandScope — Represents the scope to which bot commands are relevant
type BotCommandScope struct {
}

func (t *BotCommandScope) GetType() string { return "BotCommandScope" }

// BotCommandScopeDefault — A scope covering all users
type BotCommandScopeDefault struct {
}

func (t *BotCommandScopeDefault) GetType() string { return "botCommandScopeDefault" }

// BotCommandScopeAllPrivateChats — A scope covering all private chats
type BotCommandScopeAllPrivateChats struct {
}

func (t *BotCommandScopeAllPrivateChats) GetType() string { return "botCommandScopeAllPrivateChats" }

// BotCommandScopeAllGroupChats — A scope covering all group and supergroup chats
type BotCommandScopeAllGroupChats struct {
}

func (t *BotCommandScopeAllGroupChats) GetType() string { return "botCommandScopeAllGroupChats" }

// BotCommandScopeAllChatAdministrators — A scope covering all group and supergroup chat administrators
type BotCommandScopeAllChatAdministrators struct {
}

func (t *BotCommandScopeAllChatAdministrators) GetType() string { return "botCommandScopeAllChatAdministrators" }

