// Code generated by go-tdlib codegen. DO NOT EDIT.
package tdapi

// PublicForwardMessage — Contains a public forward as a message @message Information about the message
type PublicForwardMessage struct {
	Message *Message `json:"message"`
}

func (t *PublicForwardMessage) GetType() string { return "publicForwardMessage" }

// PublicForwardStory — Contains a public repost to a story @story Information about the story
type PublicForwardStory struct {
	Story *Story `json:"story"`
}

func (t *PublicForwardStory) GetType() string { return "publicForwardStory" }

// PublicForwards — Represents a list of public forwards and reposts as a story of a message or a story
type PublicForwards struct {
	TotalCount int32 `json:"total_count"` // Approximate total number of messages and stories found
	Forwards []*PublicForward `json:"forwards"` // List of found public forwards and reposts
	NextOffset string `json:"next_offset"` // The offset for the next request. If empty, then there are no more results
}

func (t *PublicForwards) GetType() string { return "publicForwards" }

// BotMediaPreview — Describes media previews of a bot
type BotMediaPreview struct {
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the preview was added or changed last time
	Content *StoryContent `json:"content"` // Content of the preview; may only be of the types storyContentPhoto, storyContentVideo, or storyContentUnsupported
}

func (t *BotMediaPreview) GetType() string { return "botMediaPreview" }

// BotMediaPreviews — Contains a list of media previews of a bot @previews List of media previews
type BotMediaPreviews struct {
	Previews []*BotMediaPreview `json:"previews"`
}

func (t *BotMediaPreviews) GetType() string { return "botMediaPreviews" }

// BotMediaPreviewInfo — Contains a list of media previews of a bot for the given language and the list of languages for which the bot has dedicated previews
type BotMediaPreviewInfo struct {
	Previews []*BotMediaPreview `json:"previews"` // List of media previews
	LanguageCodes []string `json:"language_codes"` // List of language codes for which the bot has dedicated previews
}

func (t *BotMediaPreviewInfo) GetType() string { return "botMediaPreviewInfo" }

// ChatBoostLevelFeatures — Contains a list of features available on a specific chat boost level
type ChatBoostLevelFeatures struct {
	Level int32 `json:"level"` // Target chat boost level
	StoryPerDayCount int32 `json:"story_per_day_count"` // Number of stories that the chat can publish daily
	CustomEmojiReactionCount int32 `json:"custom_emoji_reaction_count"` // Number of custom emoji reactions that can be added to the list of available reactions
	TitleColorCount int32 `json:"title_color_count"` // Number of custom colors for chat title
	ProfileAccentColorCount int32 `json:"profile_accent_color_count"` // Number of custom colors for profile photo background
	CanSetProfileBackgroundCustomEmoji bool `json:"can_set_profile_background_custom_emoji"` // True, if custom emoji for profile background can be set
	AccentColorCount int32 `json:"accent_color_count"` // Number of custom colors for background of empty chat photo, replies to messages and link previews
	CanSetBackgroundCustomEmoji bool `json:"can_set_background_custom_emoji"` // True, if custom emoji for reply header and link preview background can be set
	CanSetEmojiStatus bool `json:"can_set_emoji_status"` // True, if emoji status can be set
	ChatThemeBackgroundCount int32 `json:"chat_theme_background_count"` // Number of chat theme backgrounds that can be set as chat background
	CanSetCustomBackground bool `json:"can_set_custom_background"` // True, if custom background can be set in the chat for all users
	CanSetCustomEmojiStickerSet bool `json:"can_set_custom_emoji_sticker_set"` // True, if custom emoji sticker set can be set for the chat
	CanEnableAutomaticTranslation bool `json:"can_enable_automatic_translation"` // True, if automatic translation of messages can be enabled in the chat
	CanRecognizeSpeech bool `json:"can_recognize_speech"` // True, if speech recognition can be used for video note and voice note messages by all users
	CanDisableSponsoredMessages bool `json:"can_disable_sponsored_messages"` // True, if sponsored messages can be disabled in the chat
}

func (t *ChatBoostLevelFeatures) GetType() string { return "chatBoostLevelFeatures" }

// ChatBoostFeatures — Contains a list of features available on the first chat boost levels
type ChatBoostFeatures struct {
	Features []*ChatBoostLevelFeatures `json:"features"` // The list of features
	MinProfileBackgroundCustomEmojiBoostLevel int32 `json:"min_profile_background_custom_emoji_boost_level"` // The minimum boost level required to set custom emoji for profile background
	MinBackgroundCustomEmojiBoostLevel int32 `json:"min_background_custom_emoji_boost_level"` // The minimum boost level required to set custom emoji for reply header and link preview background; for channel chats only
	MinEmojiStatusBoostLevel int32 `json:"min_emoji_status_boost_level"` // The minimum boost level required to set emoji status
	MinChatThemeBackgroundBoostLevel int32 `json:"min_chat_theme_background_boost_level"` // The minimum boost level required to set a chat theme background as chat background
	MinCustomBackgroundBoostLevel int32 `json:"min_custom_background_boost_level"` // The minimum boost level required to set custom chat background
	MinCustomEmojiStickerSetBoostLevel int32 `json:"min_custom_emoji_sticker_set_boost_level"` // The minimum boost level required to set custom emoji sticker set for the chat; for supergroup chats only
	MinAutomaticTranslationBoostLevel int32 `json:"min_automatic_translation_boost_level"` // The minimum boost level allowing to enable automatic translation of messages for non-Premium users; for channel chats only
	MinSpeechRecognitionBoostLevel int32 `json:"min_speech_recognition_boost_level"` // The minimum boost level allowing to recognize speech in video note and voice note messages for non-Premium users; for supergroup chats only
	MinSponsoredMessageDisableBoostLevel int32 `json:"min_sponsored_message_disable_boost_level"` // The minimum boost level allowing to disable sponsored messages in the chat; for channel chats only
}

func (t *ChatBoostFeatures) GetType() string { return "chatBoostFeatures" }

// ChatBoostSource — Describes source of a chat boost
type ChatBoostSource struct {
}

func (t *ChatBoostSource) GetType() string { return "ChatBoostSource" }

// ChatBoostSourceGiftCode — The chat created a Telegram Premium gift code for a user
type ChatBoostSourceGiftCode struct {
	UserID int64 `json:"user_id"` // Identifier of a user, for which the gift code was created
	GiftCode string `json:"gift_code"` // The created Telegram Premium gift code, which is known only if this is a gift code for the current user, or it has already been claimed
}

func (t *ChatBoostSourceGiftCode) GetType() string { return "chatBoostSourceGiftCode" }

// ChatBoostSourceGiveaway — The chat created a giveaway
type ChatBoostSourceGiveaway struct {
	UserID int64 `json:"user_id"` // Identifier of a user who won in the giveaway; 0 if none
	GiftCode string `json:"gift_code"` // The created Telegram Premium gift code if it was used by the user or can be claimed by the current user; an empty string otherwise; for Telegram Premium giveways only
	StarCount int64 `json:"star_count"` // Number of Telegram Stars distributed among winners of the giveaway
	GiveawayMessageID int64 `json:"giveaway_message_id"` // Identifier of the corresponding giveaway message; can be an identifier of a deleted message
	IsUnclaimed bool `json:"is_unclaimed"` // True, if the winner for the corresponding giveaway prize wasn't chosen, because there were not enough participants
}

func (t *ChatBoostSourceGiveaway) GetType() string { return "chatBoostSourceGiveaway" }

// ChatBoostSourcePremium — A user with Telegram Premium subscription or gifted Telegram Premium boosted the chat
type ChatBoostSourcePremium struct {
	UserID int64 `json:"user_id"` // Identifier of the user
}

func (t *ChatBoostSourcePremium) GetType() string { return "chatBoostSourcePremium" }

// PrepaidGiveaway — Describes a prepaid giveaway
type PrepaidGiveaway struct {
	ID JSONInt64 `json:"id"` // Unique identifier of the prepaid giveaway
	WinnerCount int32 `json:"winner_count"` // Number of users which will receive giveaway prize
	Prize *GiveawayPrize `json:"prize"` // Prize of the giveaway
	BoostCount int32 `json:"boost_count"` // The number of boosts received by the chat from the giveaway; for Telegram Star giveaways only
	PaymentDate int32 `json:"payment_date"` // Point in time (Unix timestamp) when the giveaway was paid
}

func (t *PrepaidGiveaway) GetType() string { return "prepaidGiveaway" }

// ChatBoostStatus — Describes current boost status of a chat
type ChatBoostStatus struct {
	BoostURL string `json:"boost_url"` // An HTTP URL, which can be used to boost the chat
	AppliedSlotIDs []int32 `json:"applied_slot_ids"` // Identifiers of boost slots of the current user applied to the chat
	Level int32 `json:"level"` // Current boost level of the chat
	GiftCodeBoostCount int32 `json:"gift_code_boost_count"` // The number of boosts received by the chat from created Telegram Premium gift codes and giveaways; always 0 if the current user isn't an administrator in the chat
	BoostCount int32 `json:"boost_count"` // The number of boosts received by the chat
	CurrentLevelBoostCount int32 `json:"current_level_boost_count"` // The number of boosts added to reach the current level
	NextLevelBoostCount int32 `json:"next_level_boost_count"` // The number of boosts needed to reach the next level; 0 if the next level isn't available
	PremiumMemberCount int32 `json:"premium_member_count"` // Approximate number of Telegram Premium subscribers joined the chat; always 0 if the current user isn't an administrator in the chat
	PremiumMemberPercentage float64 `json:"premium_member_percentage"` // A percentage of Telegram Premium subscribers joined the chat; always 0 if the current user isn't an administrator in the chat
	PrepaidGiveaways []*PrepaidGiveaway `json:"prepaid_giveaways"` // The list of prepaid giveaways available for the chat; only for chat administrators
}

func (t *ChatBoostStatus) GetType() string { return "chatBoostStatus" }

// ChatBoost — Describes a boost applied to a chat
type ChatBoost struct {
	ID string `json:"id"` // Unique identifier of the boost
	Count int32 `json:"count"` // The number of identical boosts applied
	Source *ChatBoostSource `json:"source"` // Source of the boost
	StartDate int32 `json:"start_date"` // Point in time (Unix timestamp) when the chat was boosted
	ExpirationDate int32 `json:"expiration_date"` // Point in time (Unix timestamp) when the boost will expire
}

func (t *ChatBoost) GetType() string { return "chatBoost" }

// FoundChatBoosts — Contains a list of boosts applied to a chat
type FoundChatBoosts struct {
	TotalCount int32 `json:"total_count"` // Total number of boosts applied to the chat
	Boosts []*ChatBoost `json:"boosts"` // List of boosts
	NextOffset string `json:"next_offset"` // The offset for the next request. If empty, then there are no more results
}

func (t *FoundChatBoosts) GetType() string { return "foundChatBoosts" }

// ChatBoostSlot — Describes a slot for chat boost
type ChatBoostSlot struct {
	SlotID int32 `json:"slot_id"` // Unique identifier of the slot
	CurrentlyBoostedChatID int64 `json:"currently_boosted_chat_id"` // Identifier of the currently boosted chat; 0 if none
	StartDate int32 `json:"start_date"` // Point in time (Unix timestamp) when the chat was boosted; 0 if none
	ExpirationDate int32 `json:"expiration_date"` // Point in time (Unix timestamp) when the boost will expire
	CooldownUntilDate int32 `json:"cooldown_until_date"` // Point in time (Unix timestamp) after which the boost can be used for another chat
}

func (t *ChatBoostSlot) GetType() string { return "chatBoostSlot" }

// ChatBoostSlots — Contains a list of chat boost slots @slots List of boost slots
type ChatBoostSlots struct {
	Slots []*ChatBoostSlot `json:"slots"`
}

func (t *ChatBoostSlots) GetType() string { return "chatBoostSlots" }

// ResendCodeReason — Describes the reason why a code needs to be re-sent
type ResendCodeReason struct {
}

func (t *ResendCodeReason) GetType() string { return "ResendCodeReason" }

// ResendCodeReasonUserRequest — The user requested to resend the code
type ResendCodeReasonUserRequest struct {
}

func (t *ResendCodeReasonUserRequest) GetType() string { return "resendCodeReasonUserRequest" }

// ResendCodeReasonVerificationFailed — The code is re-sent, because device verification has failed
type ResendCodeReasonVerificationFailed struct {
	ErrorMessage string `json:"error_message"` // Cause of the verification failure, for example, "PLAY_SERVICES_NOT_AVAILABLE", "APNS_RECEIVE_TIMEOUT", or "APNS_INIT_FAILED"
}

func (t *ResendCodeReasonVerificationFailed) GetType() string { return "resendCodeReasonVerificationFailed" }

// CallDiscardReason — Describes the reason why a call was discarded
type CallDiscardReason struct {
}

func (t *CallDiscardReason) GetType() string { return "CallDiscardReason" }

// CallDiscardReasonEmpty — The call wasn't discarded, or the reason is unknown
type CallDiscardReasonEmpty struct {
}

func (t *CallDiscardReasonEmpty) GetType() string { return "callDiscardReasonEmpty" }

// CallDiscardReasonMissed — The call was ended before the conversation started. It was canceled by the caller or missed by the other party
type CallDiscardReasonMissed struct {
}

func (t *CallDiscardReasonMissed) GetType() string { return "callDiscardReasonMissed" }

// CallDiscardReasonDeclined — The call was ended before the conversation started. It was declined by the other party
type CallDiscardReasonDeclined struct {
}

func (t *CallDiscardReasonDeclined) GetType() string { return "callDiscardReasonDeclined" }

// CallDiscardReasonDisconnected — The call was ended during the conversation because the users were disconnected
type CallDiscardReasonDisconnected struct {
}

func (t *CallDiscardReasonDisconnected) GetType() string { return "callDiscardReasonDisconnected" }

// CallDiscardReasonHungUp — The call was ended because one of the parties hung up
type CallDiscardReasonHungUp struct {
}

func (t *CallDiscardReasonHungUp) GetType() string { return "callDiscardReasonHungUp" }

// CallDiscardReasonUpgradeToGroupCall — The call was ended because it has been upgraded to a group call @invite_link Invite link for the group call
type CallDiscardReasonUpgradeToGroupCall struct {
	InviteLink string `json:"invite_link"`
}

func (t *CallDiscardReasonUpgradeToGroupCall) GetType() string { return "callDiscardReasonUpgradeToGroupCall" }

// CallProtocol — Specifies the supported call protocols
type CallProtocol struct {
	UdpP2p bool `json:"udp_p2p"` // True, if UDP peer-to-peer connections are supported
	UdpReflector bool `json:"udp_reflector"` // True, if connection through UDP reflectors is supported
	MinLayer int32 `json:"min_layer"` // The minimum supported API layer; use 65
	MaxLayer int32 `json:"max_layer"` // The maximum supported API layer; use 92
	LibraryVersions []string `json:"library_versions"` // List of supported tgcalls versions
}

func (t *CallProtocol) GetType() string { return "callProtocol" }

// CallServerType — Describes the type of call server
type CallServerType struct {
}

func (t *CallServerType) GetType() string { return "CallServerType" }

// CallServerTypeTelegramReflector — A Telegram call reflector @peer_tag A peer tag to be used with the reflector @is_tcp True, if the server uses TCP instead of UDP
type CallServerTypeTelegramReflector struct {
	PeerTag []byte `json:"peer_tag"`
	IsTcp bool `json:"is_tcp"`
}

func (t *CallServerTypeTelegramReflector) GetType() string { return "callServerTypeTelegramReflector" }

// CallServerTypeWebrtc — A WebRTC server
type CallServerTypeWebrtc struct {
	Username string `json:"username"` // Username to be used for authentication
	Password string `json:"password"` // Authentication password
	SupportsTurn bool `json:"supports_turn"` // True, if the server supports TURN
	SupportsStun bool `json:"supports_stun"` // True, if the server supports STUN
}

func (t *CallServerTypeWebrtc) GetType() string { return "callServerTypeWebrtc" }

// CallServer — Describes a server for relaying call data
type CallServer struct {
	ID JSONInt64 `json:"id"` // Server identifier
	IPAddress string `json:"ip_address"` // Server IPv4 address
	IPv6Address string `json:"ipv6_address"` // Server IPv6 address
	Port int32 `json:"port"` // Server port number
	Type *CallServerType `json:"type"` // Server type
}

func (t *CallServer) GetType() string { return "callServer" }

// CallID — Contains the call identifier @id Call identifier
type CallID struct {
	ID int32 `json:"id"`
}

func (t *CallID) GetType() string { return "callId" }

// GroupCallID — Contains the group call identifier @id Group call identifier
type GroupCallID struct {
	ID int32 `json:"id"`
}

func (t *GroupCallID) GetType() string { return "groupCallId" }

// InputCall — Describes a call
type InputCall struct {
}

func (t *InputCall) GetType() string { return "InputCall" }

// InputCallDiscarded — A just ended call @call_id Identifier of the call
type InputCallDiscarded struct {
	CallID int32 `json:"call_id"`
}

func (t *InputCallDiscarded) GetType() string { return "inputCallDiscarded" }

// InputCallFromMessage — A call from a message of the type messageCall with non-zero messageCall.unique_id
type InputCallFromMessage struct {
	ChatID int64 `json:"chat_id"` // Chat identifier of the message
	MessageID int64 `json:"message_id"` // Message identifier
}

func (t *InputCallFromMessage) GetType() string { return "inputCallFromMessage" }

// CallState — Describes the current call state
type CallState struct {
}

func (t *CallState) GetType() string { return "CallState" }

// CallStatePending — The call is pending, waiting to be accepted by a user @is_created True, if the call has already been created by the server @is_received True, if the call has already been received by the other party
type CallStatePending struct {
	IsCreated bool `json:"is_created"`
	IsReceived bool `json:"is_received"`
}

func (t *CallStatePending) GetType() string { return "callStatePending" }

// CallStateExchangingKeys — The call has been answered and encryption keys are being exchanged
type CallStateExchangingKeys struct {
}

func (t *CallStateExchangingKeys) GetType() string { return "callStateExchangingKeys" }

// CallStateReady — The call is ready to use
type CallStateReady struct {
	Protocol *CallProtocol `json:"protocol"` // Call protocols supported by the other call participant
	Servers []*CallServer `json:"servers"` // List of available call servers
	Config string `json:"config"` // A JSON-encoded call config
	EncryptionKey []byte `json:"encryption_key"` // Call encryption key
	Emojis []string `json:"emojis"` // Encryption key fingerprint represented as 4 emoji
	AllowP2p bool `json:"allow_p2p"` // True, if peer-to-peer connection is allowed by users privacy settings
	IsGroupCallSupported bool `json:"is_group_call_supported"` // True, if the other party supports upgrading of the call to a group call
	CustomParameters string `json:"custom_parameters"` // Custom JSON-encoded call parameters to be passed to tgcalls
}

func (t *CallStateReady) GetType() string { return "callStateReady" }

// CallStateHangingUp — The call is hanging up after discardCall has been called
type CallStateHangingUp struct {
}

func (t *CallStateHangingUp) GetType() string { return "callStateHangingUp" }

// CallStateDiscarded — The call has ended successfully
type CallStateDiscarded struct {
	Reason *CallDiscardReason `json:"reason"` // The reason why the call has ended
	NeedRating bool `json:"need_rating"` // True, if the call rating must be sent to the server
	NeedDebugInformation bool `json:"need_debug_information"` // True, if the call debug information must be sent to the server
	NeedLog bool `json:"need_log"` // True, if the call log must be sent to the server
}

func (t *CallStateDiscarded) GetType() string { return "callStateDiscarded" }

// CallStateError — The call has ended with an error @error Error. An error with the code 4005000 will be returned if an outgoing call is missed because of an expired timeout
type CallStateError struct {
	Error *Error `json:"error"`
}

func (t *CallStateError) GetType() string { return "callStateError" }

// GroupCallJoinParameters — Describes parameters used to join a group call
type GroupCallJoinParameters struct {
	AudioSourceID int32 `json:"audio_source_id"` // Audio channel synchronization source identifier; received from tgcalls
	Payload string `json:"payload"` // Group call join payload; received from tgcalls
	IsMuted bool `json:"is_muted"` // Pass true to join the call with muted microphone
	IsMyVideoEnabled bool `json:"is_my_video_enabled"` // Pass true if the user's video is enabled
}

func (t *GroupCallJoinParameters) GetType() string { return "groupCallJoinParameters" }

// GroupCallVideoQuality — Describes the quality of a group call video
type GroupCallVideoQuality struct {
}

func (t *GroupCallVideoQuality) GetType() string { return "GroupCallVideoQuality" }

// GroupCallVideoQualityThumbnail — The worst available video quality
type GroupCallVideoQualityThumbnail struct {
}

func (t *GroupCallVideoQualityThumbnail) GetType() string { return "groupCallVideoQualityThumbnail" }

// GroupCallVideoQualityMedium — The medium video quality
type GroupCallVideoQualityMedium struct {
}

func (t *GroupCallVideoQualityMedium) GetType() string { return "groupCallVideoQualityMedium" }

// GroupCallVideoQualityFull — The best available video quality
type GroupCallVideoQualityFull struct {
}

func (t *GroupCallVideoQualityFull) GetType() string { return "groupCallVideoQualityFull" }

// GroupCallStream — Describes an available stream in a video chat or a live story
type GroupCallStream struct {
	ChannelID int32 `json:"channel_id"` // Identifier of an audio/video channel
	Scale int32 `json:"scale"` // Scale of segment durations in the stream. The duration is 1000/(2**scale) milliseconds
	TimeOffset int64 `json:"time_offset"` // Point in time when the stream currently ends; Unix timestamp in milliseconds
}

func (t *GroupCallStream) GetType() string { return "groupCallStream" }

// GroupCallStreams — Represents a list of group call streams @streams A list of group call streams
type GroupCallStreams struct {
	Streams []*GroupCallStream `json:"streams"`
}

func (t *GroupCallStreams) GetType() string { return "groupCallStreams" }

// RtmpURL — Represents an RTMP URL @url The URL @stream_key Stream key
type RtmpURL struct {
	URL string `json:"url"`
	StreamKey string `json:"stream_key"`
}

func (t *RtmpURL) GetType() string { return "rtmpUrl" }

// GroupCallRecentSpeaker — Describes a recently speaking participant in a group call @participant_id Group call participant identifier @is_speaking True, is the user has spoken recently
type GroupCallRecentSpeaker struct {
	ParticipantID *MessageSender `json:"participant_id"`
	IsSpeaking bool `json:"is_speaking"`
}

func (t *GroupCallRecentSpeaker) GetType() string { return "groupCallRecentSpeaker" }

// GroupCall — Describes a group call
type GroupCall struct {
	ID int32 `json:"id"` // Group call identifier
	UniqueID JSONInt64 `json:"unique_id"` // Persistent unique group call identifier
	Title string `json:"title"` // Group call title; for video chats only
	InviteLink string `json:"invite_link"` // Invite link for the group call; for group calls that aren't bound to a chat. For video chats call getVideoChatInviteLink to get the link.
	PaidMessageStarCount int64 `json:"paid_message_star_count"` // The minimum number of Telegram Stars that must be paid by general participant for each sent message to the call; for live stories only
	ScheduledStartDate int32 `json:"scheduled_start_date"` // Point in time (Unix timestamp) when the group call is expected to be started by an administrator; 0 if it is already active or was ended; for video chats only
	EnabledStartNotification bool `json:"enabled_start_notification"` // True, if the group call is scheduled and the current user will receive a notification when the group call starts; for video chats only
	IsActive bool `json:"is_active"` // True, if the call is active
	IsVideoChat bool `json:"is_video_chat"` // True, if the call is bound to a chat
	IsLiveStory bool `json:"is_live_story"` // True, if the call is a live story of a chat
	IsRtmpStream bool `json:"is_rtmp_stream"` // True, if the call is an RTMP stream instead of an ordinary video chat; for video chats and live stories only
	IsJoined bool `json:"is_joined"` // True, if the call is joined
	NeedRejoin bool `json:"need_rejoin"` // True, if user was kicked from the call because of network loss and the call needs to be rejoined
	IsOwned bool `json:"is_owned"` // True, if the user is the owner of the call and can end the call, change volume level of other users, or ban users there; for group calls that aren't bound to a chat
	CanBeManaged bool `json:"can_be_managed"` // True, if the current user can manage the group call; for video chats and live stories only
	ParticipantCount int32 `json:"participant_count"` // Number of participants in the group call
	HasHiddenListeners bool `json:"has_hidden_listeners"` // True, if group call participants, which are muted, aren't returned in participant list; for video chats only
	LoadedAllParticipants bool `json:"loaded_all_participants"` // True, if all group call participants are loaded
	MessageSenderID *MessageSender `json:"message_sender_id"` // Message sender chosen to send messages to the group call; for live stories only; may be null if the call isn't a live story
	RecentSpeakers []*GroupCallRecentSpeaker `json:"recent_speakers"` // At most 3 recently speaking users in the group call
	IsMyVideoEnabled bool `json:"is_my_video_enabled"` // True, if the current user's video is enabled
	IsMyVideoPaused bool `json:"is_my_video_paused"` // True, if the current user's video is paused
	CanEnableVideo bool `json:"can_enable_video"` // True, if the current user can broadcast video or share screen
	MuteNewParticipants bool `json:"mute_new_participants"` // True, if only group call administrators can unmute new participants; for video chats only
	CanToggleMuteNewParticipants bool `json:"can_toggle_mute_new_participants"` // True, if the current user can enable or disable mute_new_participants setting; for video chats only
	CanSendMessages bool `json:"can_send_messages"` // True, if the current user can send messages to the group call
	AreMessagesAllowed bool `json:"are_messages_allowed"` // True, if sending of messages is allowed in the group call
	CanToggleAreMessagesAllowed bool `json:"can_toggle_are_messages_allowed"` // True, if the current user can enable or disable sending of messages in the group call
	CanDeleteMessages bool `json:"can_delete_messages"` // True, if the user can delete messages in the group call
	RecordDuration int32 `json:"record_duration"` // Duration of the ongoing group call recording, in seconds; 0 if none. An updateGroupCall update is not triggered when value of this field changes, but the same recording goes on
	IsVideoRecorded bool `json:"is_video_recorded"` // True, if a video file is being recorded for the call
	Duration int32 `json:"duration"` // Call duration, in seconds; for ended calls only
}

func (t *GroupCall) GetType() string { return "groupCall" }

// GroupCallVideoSourceGroup — Describes a group of video synchronization source identifiers @semantics The semantics of sources, one of "SIM" or "FID" @source_ids The list of synchronization source identifiers
type GroupCallVideoSourceGroup struct {
	Semantics string `json:"semantics"`
	SourceIDs []int32 `json:"source_ids"`
}

func (t *GroupCallVideoSourceGroup) GetType() string { return "groupCallVideoSourceGroup" }

// GroupCallParticipantVideoInfo — Contains information about a group call participant's video channel
type GroupCallParticipantVideoInfo struct {
	SourceGroups []*GroupCallVideoSourceGroup `json:"source_groups"` // List of synchronization source groups of the video
	EndpointID string `json:"endpoint_id"` // Video channel endpoint identifier
	IsPaused bool `json:"is_paused"` // True, if the video is paused. This flag needs to be ignored, if new video frames are received
}

func (t *GroupCallParticipantVideoInfo) GetType() string { return "groupCallParticipantVideoInfo" }

// GroupCallParticipant — Represents a group call participant
type GroupCallParticipant struct {
	ParticipantID *MessageSender `json:"participant_id"` // Identifier of the group call participant
	AudioSourceID int32 `json:"audio_source_id"` // User's audio channel synchronization source identifier
	ScreenSharingAudioSourceID int32 `json:"screen_sharing_audio_source_id"` // User's screen sharing audio channel synchronization source identifier
	VideoInfo *GroupCallParticipantVideoInfo `json:"video_info"` // Information about user's video channel; may be null if there is no active video
	ScreenSharingVideoInfo *GroupCallParticipantVideoInfo `json:"screen_sharing_video_info"` // Information about user's screen sharing video channel; may be null if there is no active screen sharing video
	Bio string `json:"bio"` // The participant user's bio or the participant chat's description
	IsCurrentUser bool `json:"is_current_user"` // True, if the participant is the current user
	IsSpeaking bool `json:"is_speaking"` // True, if the participant is speaking as set by setGroupCallParticipantIsSpeaking
	IsHandRaised bool `json:"is_hand_raised"` // True, if the participant hand is raised
	CanBeMutedForAllUsers bool `json:"can_be_muted_for_all_users"` // True, if the current user can mute the participant for all other group call participants
	CanBeUnmutedForAllUsers bool `json:"can_be_unmuted_for_all_users"` // True, if the current user can allow the participant to unmute themselves or unmute the participant (if the participant is the current user)
	CanBeMutedForCurrentUser bool `json:"can_be_muted_for_current_user"` // True, if the current user can mute the participant only for self
	CanBeUnmutedForCurrentUser bool `json:"can_be_unmuted_for_current_user"` // True, if the current user can unmute the participant for self
	IsMutedForAllUsers bool `json:"is_muted_for_all_users"` // True, if the participant is muted for all users
	IsMutedForCurrentUser bool `json:"is_muted_for_current_user"` // True, if the participant is muted for the current user
	CanUnmuteSelf bool `json:"can_unmute_self"` // True, if the participant is muted for all users, but can unmute themselves
	VolumeLevel int32 `json:"volume_level"` // Participant's volume level; 1-20000 in hundreds of percents
	Order string `json:"order"` // User's order in the group call participant list. Orders must be compared lexicographically. The bigger is order, the higher is user in the list. If order is empty, the user must be removed from the participant list
}

func (t *GroupCallParticipant) GetType() string { return "groupCallParticipant" }

// GroupCallParticipants — Contains identifiers of group call participants @total_count Total number of group call participants @participant_ids Identifiers of the participants
type GroupCallParticipants struct {
	TotalCount int32 `json:"total_count"`
	ParticipantIDs []*MessageSender `json:"participant_ids"`
}

func (t *GroupCallParticipants) GetType() string { return "groupCallParticipants" }

// GroupCallInfo — Contains information about a just created or just joined group call @group_call_id Identifier of the group call @join_payload Join response payload for tgcalls; empty if the call isn't joined
type GroupCallInfo struct {
	GroupCallID int32 `json:"group_call_id"`
	JoinPayload string `json:"join_payload"`
}

func (t *GroupCallInfo) GetType() string { return "groupCallInfo" }

// GroupCallMessage — Represents a message sent in a group call
type GroupCallMessage struct {
	MessageID int32 `json:"message_id"` // Unique message identifier within the group call
	SenderID *MessageSender `json:"sender_id"` // Identifier of the sender of the message
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the message was sent
	Text *FormattedText `json:"text"` // Text of the message. If empty, then the message is a paid reaction in a live story
	PaidMessageStarCount int64 `json:"paid_message_star_count"` // The number of Telegram Stars that were paid to send the message; for live stories only
	IsFromOwner bool `json:"is_from_owner"` // True, if the message is sent by the owner of the call and must be treated as a message of the maximum level; for live stories only
	CanBeDeleted bool `json:"can_be_deleted"` // True, if the message can be deleted by the current user; for live stories only
}

func (t *GroupCallMessage) GetType() string { return "groupCallMessage" }

// GroupCallMessageLevel — Represents a level of features for a message sent in a live story group call
type GroupCallMessageLevel struct {
	MinStarCount int64 `json:"min_star_count"` // The minimum number of Telegram Stars required to get features of the level
	PinDuration int32 `json:"pin_duration"` // The amount of time the message of this level will be pinned, in seconds
	MaxTextLength int32 `json:"max_text_length"` // The maximum allowed length of the message text
	MaxCustomEmojiCount int32 `json:"max_custom_emoji_count"` // The maximum allowed number of custom emoji in the message text
	FirstColor int32 `json:"first_color"` // The first color used to show the message text in the RGB format
	SecondColor int32 `json:"second_color"` // The second color used to show the message text in the RGB format
	BackgroundColor int32 `json:"background_color"` // Background color for the message the RGB format
}

func (t *GroupCallMessageLevel) GetType() string { return "groupCallMessageLevel" }

// InviteGroupCallParticipantResult — Describes result of group call participant invitation
type InviteGroupCallParticipantResult struct {
}

func (t *InviteGroupCallParticipantResult) GetType() string { return "InviteGroupCallParticipantResult" }

// InviteGroupCallParticipantResultUserPrivacyRestricted — The user can't be invited due to their privacy settings
type InviteGroupCallParticipantResultUserPrivacyRestricted struct {
}

func (t *InviteGroupCallParticipantResultUserPrivacyRestricted) GetType() string { return "inviteGroupCallParticipantResultUserPrivacyRestricted" }

// InviteGroupCallParticipantResultUserAlreadyParticipant — The user can't be invited because they are already a participant of the call
type InviteGroupCallParticipantResultUserAlreadyParticipant struct {
}

func (t *InviteGroupCallParticipantResultUserAlreadyParticipant) GetType() string { return "inviteGroupCallParticipantResultUserAlreadyParticipant" }

// InviteGroupCallParticipantResultUserWasBanned — The user can't be invited because they were banned by the owner of the call and can be invited back only by the owner of the group call
type InviteGroupCallParticipantResultUserWasBanned struct {
}

func (t *InviteGroupCallParticipantResultUserWasBanned) GetType() string { return "inviteGroupCallParticipantResultUserWasBanned" }

// InviteGroupCallParticipantResultSuccess — The user was invited and a service message of the type messageGroupCall was sent which can be used in declineGroupCallInvitation to cancel the invitation
type InviteGroupCallParticipantResultSuccess struct {
	ChatID int64 `json:"chat_id"` // Identifier of the chat with the invitation message
	MessageID int64 `json:"message_id"` // Identifier of the message
}

func (t *InviteGroupCallParticipantResultSuccess) GetType() string { return "inviteGroupCallParticipantResultSuccess" }

// GroupCallDataChannel — Describes data channel for a group call
type GroupCallDataChannel struct {
}

func (t *GroupCallDataChannel) GetType() string { return "GroupCallDataChannel" }

// GroupCallDataChannelMain — The main data channel for audio and video data
type GroupCallDataChannelMain struct {
}

func (t *GroupCallDataChannelMain) GetType() string { return "groupCallDataChannelMain" }

// GroupCallDataChannelScreenSharing — The data channel for screen sharing
type GroupCallDataChannelScreenSharing struct {
}

func (t *GroupCallDataChannelScreenSharing) GetType() string { return "groupCallDataChannelScreenSharing" }

// InputGroupCall — Describes a non-joined group call that isn't bound to a chat
type InputGroupCall struct {
}

func (t *InputGroupCall) GetType() string { return "InputGroupCall" }

// InputGroupCallLink — The group call is accessible through a link @link The link for the group call
type InputGroupCallLink struct {
	Link string `json:"link"`
}

func (t *InputGroupCallLink) GetType() string { return "inputGroupCallLink" }

// InputGroupCallMessage — The group call is accessible through a message of the type messageGroupCall
type InputGroupCallMessage struct {
	ChatID int64 `json:"chat_id"` // Identifier of the chat with the message
	MessageID int64 `json:"message_id"` // Identifier of the message of the type messageGroupCall
}

func (t *InputGroupCallMessage) GetType() string { return "inputGroupCallMessage" }

// CallProblem — Describes the exact type of problem with a call
type CallProblem struct {
}

func (t *CallProblem) GetType() string { return "CallProblem" }

// CallProblemEcho — The user heard their own voice
type CallProblemEcho struct {
}

func (t *CallProblemEcho) GetType() string { return "callProblemEcho" }

// CallProblemNoise — The user heard background noise
type CallProblemNoise struct {
}

func (t *CallProblemNoise) GetType() string { return "callProblemNoise" }

// CallProblemInterruptions — The other side kept disappearing
type CallProblemInterruptions struct {
}

func (t *CallProblemInterruptions) GetType() string { return "callProblemInterruptions" }

// CallProblemDistortedSpeech — The speech was distorted
type CallProblemDistortedSpeech struct {
}

func (t *CallProblemDistortedSpeech) GetType() string { return "callProblemDistortedSpeech" }

// CallProblemSilentLocal — The user couldn't hear the other side
type CallProblemSilentLocal struct {
}

func (t *CallProblemSilentLocal) GetType() string { return "callProblemSilentLocal" }

// CallProblemSilentRemote — The other side couldn't hear the user
type CallProblemSilentRemote struct {
}

func (t *CallProblemSilentRemote) GetType() string { return "callProblemSilentRemote" }

// CallProblemDropped — The call ended unexpectedly
type CallProblemDropped struct {
}

func (t *CallProblemDropped) GetType() string { return "callProblemDropped" }

// CallProblemDistortedVideo — The video was distorted
type CallProblemDistortedVideo struct {
}

func (t *CallProblemDistortedVideo) GetType() string { return "callProblemDistortedVideo" }

// CallProblemPixelatedVideo — The video was pixelated
type CallProblemPixelatedVideo struct {
}

func (t *CallProblemPixelatedVideo) GetType() string { return "callProblemPixelatedVideo" }

// Call — Describes a call
type Call struct {
	ID int32 `json:"id"` // Call identifier, not persistent
	UniqueID JSONInt64 `json:"unique_id"` // Persistent unique call identifier; 0 if isn't assigned yet by the server
	UserID int64 `json:"user_id"` // User identifier of the other call participant
	IsOutgoing bool `json:"is_outgoing"` // True, if the call is outgoing
	IsVideo bool `json:"is_video"` // True, if the call is a video call
	State *CallState `json:"state"` // Call state
}

func (t *Call) GetType() string { return "call" }

// FirebaseAuthenticationSettings — Contains settings for Firebase Authentication in the official applications
type FirebaseAuthenticationSettings struct {
}

func (t *FirebaseAuthenticationSettings) GetType() string { return "FirebaseAuthenticationSettings" }

// FirebaseAuthenticationSettingsAndroid — Settings for Firebase Authentication in the official Android application
type FirebaseAuthenticationSettingsAndroid struct {
}

func (t *FirebaseAuthenticationSettingsAndroid) GetType() string { return "firebaseAuthenticationSettingsAndroid" }

// FirebaseAuthenticationSettingsIos — Settings for Firebase Authentication in the official iOS application @device_token Device token from Apple Push Notification service @is_app_sandbox True, if App Sandbox is enabled
type FirebaseAuthenticationSettingsIos struct {
	DeviceToken string `json:"device_token"`
	IsAppSandbox bool `json:"is_app_sandbox"`
}

func (t *FirebaseAuthenticationSettingsIos) GetType() string { return "firebaseAuthenticationSettingsIos" }

// PhoneNumberAuthenticationSettings — Contains settings for the authentication of the user's phone number
type PhoneNumberAuthenticationSettings struct {
	AllowFlashCall bool `json:"allow_flash_call"` // Pass true if the authentication code may be sent via a flash call to the specified phone number
	AllowMissedCall bool `json:"allow_missed_call"` // Pass true if the authentication code may be sent via a missed call to the specified phone number
	IsCurrentPhoneNumber bool `json:"is_current_phone_number"` // Pass true if the authenticated phone number is used on the current device
	HasUnknownPhoneNumber bool `json:"has_unknown_phone_number"` // Pass true if there is a SIM card in the current device, but it is not possible to check whether phone number matches
	AllowSmsRetrieverAPI bool `json:"allow_sms_retriever_api"` // For official applications only. True, if the application can use Android SMS Retriever API (requires Google Play Services >= 10.2) to automatically receive the authentication code from the SMS. See https://developers.google.com/identity/sms-retriever/ for more details
	FirebaseAuthenticationSettings *FirebaseAuthenticationSettings `json:"firebase_authentication_settings"` // For official Android and iOS applications only; pass null otherwise. Settings for Firebase Authentication
	AuthenticationTokens []string `json:"authentication_tokens"` // List of up to 20 authentication tokens, recently received in updateOption("authentication_token") in previously logged out sessions; for setAuthenticationPhoneNumber only
}

func (t *PhoneNumberAuthenticationSettings) GetType() string { return "phoneNumberAuthenticationSettings" }

// AddedReaction — Represents a reaction applied to a message
type AddedReaction struct {
	Type *ReactionType `json:"type"` // Type of the reaction
	SenderID *MessageSender `json:"sender_id"` // Identifier of the chat member, applied the reaction
	IsOutgoing bool `json:"is_outgoing"` // True, if the reaction was added by the current user
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the reaction was added
}

func (t *AddedReaction) GetType() string { return "addedReaction" }

// AddedReactions — Represents a list of reactions added to a message @total_count The total number of found reactions @reactions The list of added reactions @next_offset The offset for the next request. If empty, then there are no more results
type AddedReactions struct {
	TotalCount int32 `json:"total_count"`
	Reactions []*AddedReaction `json:"reactions"`
	NextOffset string `json:"next_offset"`
}

func (t *AddedReactions) GetType() string { return "addedReactions" }

// AvailableReaction — Represents an available reaction @type Type of the reaction @needs_premium True, if Telegram Premium is needed to send the reaction
type AvailableReaction struct {
	Type *ReactionType `json:"type"`
	NeedsPremium bool `json:"needs_premium"`
}

func (t *AvailableReaction) GetType() string { return "availableReaction" }

// AvailableReactions — Represents a list of reactions that can be added to a message
type AvailableReactions struct {
	TopReactions []*AvailableReaction `json:"top_reactions"` // List of reactions to be shown at the top
	RecentReactions []*AvailableReaction `json:"recent_reactions"` // List of recently used reactions
	PopularReactions []*AvailableReaction `json:"popular_reactions"` // List of popular reactions
	AllowCustomEmoji bool `json:"allow_custom_emoji"` // True, if any custom emoji reaction can be added by Telegram Premium subscribers
	AreTags bool `json:"are_tags"` // True, if the reactions will be tags and the message can be found by them
	UnavailabilityReason *ReactionUnavailabilityReason `json:"unavailability_reason"` // The reason why the current user can't add reactions to the message, despite some other users can; may be null if none
}

func (t *AvailableReactions) GetType() string { return "availableReactions" }

// EmojiReaction — Contains information about an emoji reaction
type EmojiReaction struct {
	Emoji string `json:"emoji"` // Text representation of the reaction
	Title string `json:"title"` // Reaction title
	IsActive bool `json:"is_active"` // True, if the reaction can be added to new messages and enabled in chats
	StaticIcon *Sticker `json:"static_icon"` // Static icon for the reaction
	AppearAnimation *Sticker `json:"appear_animation"` // Appear animation for the reaction
	SelectAnimation *Sticker `json:"select_animation"` // Select animation for the reaction
	ActivateAnimation *Sticker `json:"activate_animation"` // Activate animation for the reaction
	EffectAnimation *Sticker `json:"effect_animation"` // Effect animation for the reaction
	AroundAnimation *Sticker `json:"around_animation"` // Around animation for the reaction; may be null
	CenterAnimation *Sticker `json:"center_animation"` // Center animation for the reaction; may be null
}

func (t *EmojiReaction) GetType() string { return "emojiReaction" }

// ReactionUnavailabilityReason — Describes why the current user can't add reactions to the message, despite some other users can
type ReactionUnavailabilityReason struct {
}

func (t *ReactionUnavailabilityReason) GetType() string { return "ReactionUnavailabilityReason" }

// ReactionUnavailabilityReasonAnonymousAdministrator — The user is an anonymous administrator in the supergroup, but isn't a creator of it, so they can't vote on behalf of the supergroup
type ReactionUnavailabilityReasonAnonymousAdministrator struct {
}

func (t *ReactionUnavailabilityReasonAnonymousAdministrator) GetType() string { return "reactionUnavailabilityReasonAnonymousAdministrator" }

// ReactionUnavailabilityReasonGuest — The user isn't a member of the supergroup and can't send messages and reactions there without joining
type ReactionUnavailabilityReasonGuest struct {
}

func (t *ReactionUnavailabilityReasonGuest) GetType() string { return "reactionUnavailabilityReasonGuest" }

// Animations — Represents a list of animations @animations List of animations
type Animations struct {
	Animations []*Animation `json:"animations"`
}

func (t *Animations) GetType() string { return "animations" }

// DiceStickers — Contains animated stickers which must be used for dice animation rendering
type DiceStickers struct {
}

func (t *DiceStickers) GetType() string { return "DiceStickers" }

// DiceStickersRegular — A regular animated sticker @sticker The animated sticker with the dice animation
type DiceStickersRegular struct {
	Sticker *Sticker `json:"sticker"`
}

func (t *DiceStickersRegular) GetType() string { return "diceStickersRegular" }

// DiceStickersSlotMachine — Animated stickers to be combined into a slot machine
type DiceStickersSlotMachine struct {
	Background *Sticker `json:"background"` // The animated sticker with the slot machine background. The background animation must start playing after all reel animations finish
	Lever *Sticker `json:"lever"` // The animated sticker with the lever animation. The lever animation must play once in the initial dice state
	LeftReel *Sticker `json:"left_reel"` // The animated sticker with the left reel
	CenterReel *Sticker `json:"center_reel"` // The animated sticker with the center reel
	RightReel *Sticker `json:"right_reel"` // The animated sticker with the right reel
}

func (t *DiceStickersSlotMachine) GetType() string { return "diceStickersSlotMachine" }

// ImportedContact — Describes a contact to import
type ImportedContact struct {
	PhoneNumber string `json:"phone_number"` // Phone number of the user
	FirstName string `json:"first_name"` // First name of the user; 1-64 characters
	LastName string `json:"last_name"` // Last name of the user; 0-64 characters
	Note *FormattedText `json:"note"` // Note to add about the user; 0-getOption("user_note_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed;
}

func (t *ImportedContact) GetType() string { return "importedContact" }

// ImportedContacts — Represents the result of an importContacts request
type ImportedContacts struct {
	UserIDs []int64 `json:"user_ids"` // User identifiers of the imported contacts in the same order as they were specified in the request; 0 if the contact is not yet a registered user
	ImporterCount []int32 `json:"importer_count"` // The number of users that imported the corresponding contact; 0 for already registered users or if unavailable
}

func (t *ImportedContacts) GetType() string { return "importedContacts" }

// SpeechRecognitionResult — Describes result of speech recognition in a voice note
type SpeechRecognitionResult struct {
}

func (t *SpeechRecognitionResult) GetType() string { return "SpeechRecognitionResult" }

// SpeechRecognitionResultPending — The speech recognition is ongoing @partial_text Partially recognized text
type SpeechRecognitionResultPending struct {
	PartialText string `json:"partial_text"`
}

func (t *SpeechRecognitionResultPending) GetType() string { return "speechRecognitionResultPending" }

// SpeechRecognitionResultText — The speech recognition successfully finished @text Recognized text
type SpeechRecognitionResultText struct {
	Text string `json:"text"`
}

func (t *SpeechRecognitionResultText) GetType() string { return "speechRecognitionResultText" }

// SpeechRecognitionResultError — The speech recognition failed @error Recognition error. An error with a message "MSG_VOICE_TOO_LONG" is returned when media duration is too big to be recognized
type SpeechRecognitionResultError struct {
	Error *Error `json:"error"`
}

func (t *SpeechRecognitionResultError) GetType() string { return "speechRecognitionResultError" }

// BusinessConnection — Describes a connection of the bot with a business account
type BusinessConnection struct {
	ID string `json:"id"` // Unique identifier of the connection
	UserID int64 `json:"user_id"` // Identifier of the business user who created the connection
	UserChatID int64 `json:"user_chat_id"` // Chat identifier of the private chat with the user
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the connection was established
	Rights *BusinessBotRights `json:"rights"` // Rights of the bot; may be null if the connection was disabled
	IsEnabled bool `json:"is_enabled"` // True, if the connection is enabled; false otherwise
}

func (t *BusinessConnection) GetType() string { return "businessConnection" }

// AttachmentMenuBotColor — Describes a color to highlight a bot added to attachment menu @light_color Color in the RGB format for light themes @dark_color Color in the RGB format for dark themes
type AttachmentMenuBotColor struct {
	LightColor int32 `json:"light_color"`
	DarkColor int32 `json:"dark_color"`
}

func (t *AttachmentMenuBotColor) GetType() string { return "attachmentMenuBotColor" }

// AttachmentMenuBot — Represents a bot, which can be added to attachment or side menu
type AttachmentMenuBot struct {
	BotUserID int64 `json:"bot_user_id"` // User identifier of the bot
	SupportsSelfChat bool `json:"supports_self_chat"` // True, if the bot supports opening from attachment menu in the chat with the bot
	SupportsUserChats bool `json:"supports_user_chats"` // True, if the bot supports opening from attachment menu in private chats with ordinary users
	SupportsBotChats bool `json:"supports_bot_chats"` // True, if the bot supports opening from attachment menu in private chats with other bots
	SupportsGroupChats bool `json:"supports_group_chats"` // True, if the bot supports opening from attachment menu in basic group and supergroup chats
	SupportsChannelChats bool `json:"supports_channel_chats"` // True, if the bot supports opening from attachment menu in channel chats
	RequestWriteAccess bool `json:"request_write_access"` // True, if the user must be asked for the permission to send messages to the bot
	IsAdded bool `json:"is_added"` // True, if the bot was explicitly added by the user. If the bot isn't added, then on the first bot launch toggleBotIsAddedToAttachmentMenu must be called and the bot must be added or removed
	ShowInAttachmentMenu bool `json:"show_in_attachment_menu"` // True, if the bot must be shown in the attachment menu
	ShowInSideMenu bool `json:"show_in_side_menu"` // True, if the bot must be shown in the side menu
	ShowDisclaimerInSideMenu bool `json:"show_disclaimer_in_side_menu"` // True, if a disclaimer, why the bot is shown in the side menu, is needed
	Name string `json:"name"` // Name for the bot in attachment menu
	NameColor *AttachmentMenuBotColor `json:"name_color"` // Color to highlight selected name of the bot if appropriate; may be null
	DefaultIcon *File `json:"default_icon"` // Default icon for the bot in SVG format; may be null
	IosStaticIcon *File `json:"ios_static_icon"` // Icon for the bot in SVG format for the official iOS app; may be null
	IosAnimatedIcon *File `json:"ios_animated_icon"` // Icon for the bot in TGS format for the official iOS app; may be null
	IosSideMenuIcon *File `json:"ios_side_menu_icon"` // Icon for the bot in PNG format for the official iOS app side menu; may be null
	AndroidIcon *File `json:"android_icon"` // Icon for the bot in TGS format for the official Android app; may be null
	AndroidSideMenuIcon *File `json:"android_side_menu_icon"` // Icon for the bot in SVG format for the official Android app side menu; may be null
	MacosIcon *File `json:"macos_icon"` // Icon for the bot in TGS format for the official native macOS app; may be null
	MacosSideMenuIcon *File `json:"macos_side_menu_icon"` // Icon for the bot in PNG format for the official macOS app side menu; may be null
	IconColor *AttachmentMenuBotColor `json:"icon_color"` // Color to highlight selected icon of the bot if appropriate; may be null
	WebAppPlaceholder *File `json:"web_app_placeholder"` // Default placeholder for opened Web Apps in SVG format; may be null
}

func (t *AttachmentMenuBot) GetType() string { return "attachmentMenuBot" }

// SentWebAppMessage — Information about the message sent by answerWebAppQuery @inline_message_id Identifier of the sent inline message, if known
type SentWebAppMessage struct {
	InlineMessageID string `json:"inline_message_id"`
}

func (t *SentWebAppMessage) GetType() string { return "sentWebAppMessage" }

// BotWriteAccessAllowReason — Describes a reason why a bot was allowed to write messages to the current user
type BotWriteAccessAllowReason struct {
}

func (t *BotWriteAccessAllowReason) GetType() string { return "BotWriteAccessAllowReason" }

// BotWriteAccessAllowReasonConnectedWebsite — The user connected a website by logging in using Telegram Login Widget on it @domain_name Domain name of the connected website
type BotWriteAccessAllowReasonConnectedWebsite struct {
	DomainName string `json:"domain_name"`
}

func (t *BotWriteAccessAllowReasonConnectedWebsite) GetType() string { return "botWriteAccessAllowReasonConnectedWebsite" }

// BotWriteAccessAllowReasonAddedToAttachmentMenu — The user added the bot to attachment or side menu using toggleBotIsAddedToAttachmentMenu
type BotWriteAccessAllowReasonAddedToAttachmentMenu struct {
}

func (t *BotWriteAccessAllowReasonAddedToAttachmentMenu) GetType() string { return "botWriteAccessAllowReasonAddedToAttachmentMenu" }

// BotWriteAccessAllowReasonLaunchedWebApp — The user launched a Web App using getWebAppLinkUrl @web_app Information about the Web App
type BotWriteAccessAllowReasonLaunchedWebApp struct {
	WebApp *WebApp `json:"web_app"`
}

func (t *BotWriteAccessAllowReasonLaunchedWebApp) GetType() string { return "botWriteAccessAllowReasonLaunchedWebApp" }

// BotWriteAccessAllowReasonAcceptedRequest — The user accepted bot's request to send messages with allowBotToSendMessages
type BotWriteAccessAllowReasonAcceptedRequest struct {
}

func (t *BotWriteAccessAllowReasonAcceptedRequest) GetType() string { return "botWriteAccessAllowReasonAcceptedRequest" }

// HTTPURL — Contains an HTTP URL @url The URL
type HTTPURL struct {
	URL string `json:"url"`
}

func (t *HTTPURL) GetType() string { return "httpUrl" }

// UserLink — Contains an HTTPS URL, which can be used to get information about a user @url The URL @expires_in Left time for which the link is valid, in seconds; 0 if the link is a public username link
type UserLink struct {
	URL string `json:"url"`
	ExpiresIn int32 `json:"expires_in"`
}

func (t *UserLink) GetType() string { return "userLink" }

// TargetChatTypes — Describes allowed types for the target chat
type TargetChatTypes struct {
	AllowUserChats bool `json:"allow_user_chats"` // True, if private chats with ordinary users are allowed
	AllowBotChats bool `json:"allow_bot_chats"` // True, if private chats with other bots are allowed
	AllowGroupChats bool `json:"allow_group_chats"` // True, if basic group and supergroup chats are allowed
	AllowChannelChats bool `json:"allow_channel_chats"` // True, if channel chats are allowed
}

func (t *TargetChatTypes) GetType() string { return "targetChatTypes" }

// TargetChat — Describes the target chat to be opened
type TargetChat struct {
}

func (t *TargetChat) GetType() string { return "TargetChat" }

// TargetChatCurrent — The currently opened chat and forum topic must be kept
type TargetChatCurrent struct {
}

func (t *TargetChatCurrent) GetType() string { return "targetChatCurrent" }

// TargetChatChosen — The chat needs to be chosen by the user among chats of the specified types @types Allowed types for the chat
type TargetChatChosen struct {
	Types *TargetChatTypes `json:"types"`
}

func (t *TargetChatChosen) GetType() string { return "targetChatChosen" }

// TargetChatInternalLink — The chat needs to be open with the provided internal link @link An internal link pointing to the chat
type TargetChatInternalLink struct {
	Link *InternalLinkType `json:"link"`
}

func (t *TargetChatInternalLink) GetType() string { return "targetChatInternalLink" }

// InputInlineQueryResult — Represents a single result of an inline query; for bots only
type InputInlineQueryResult struct {
}

func (t *InputInlineQueryResult) GetType() string { return "InputInlineQueryResult" }

// InputInlineQueryResultAnimation — Represents a link to an animated GIF or an animated (i.e., without sound) H.264/MPEG-4 AVC video
type InputInlineQueryResultAnimation struct {
	ID string `json:"id"` // Unique identifier of the query result
	Title string `json:"title"` // Title of the query result
	ThumbnailURL string `json:"thumbnail_url"` // URL of the result thumbnail (JPEG, GIF, or MPEG4), if it exists
	ThumbnailMimeType string `json:"thumbnail_mime_type"` // MIME type of the video thumbnail. If non-empty, must be one of "image/jpeg", "image/gif" and "video/mp4"
	VideoURL string `json:"video_url"` // The URL of the video file (file size must not exceed 1MB)
	VideoMimeType string `json:"video_mime_type"` // MIME type of the video file. Must be one of "image/gif" and "video/mp4"
	VideoDuration int32 `json:"video_duration"` // Duration of the video, in seconds
	VideoWidth int32 `json:"video_width"` // Width of the video
	VideoHeight int32 `json:"video_height"` // Height of the video
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageAnimation, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultAnimation) GetType() string { return "inputInlineQueryResultAnimation" }

// InputInlineQueryResultArticle — Represents a link to an article or web page
type InputInlineQueryResultArticle struct {
	ID string `json:"id"` // Unique identifier of the query result
	URL string `json:"url"` // URL of the result, if it exists
	Title string `json:"title"` // Title of the result
	Description string `json:"description"` // Represents a link to an article or web page
	ThumbnailURL string `json:"thumbnail_url"` // URL of the result thumbnail, if it exists
	ThumbnailWidth int32 `json:"thumbnail_width"` // Thumbnail width, if known
	ThumbnailHeight int32 `json:"thumbnail_height"` // Thumbnail height, if known
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultArticle) GetType() string { return "inputInlineQueryResultArticle" }

// InputInlineQueryResultAudio — Represents a link to an MP3 audio file
type InputInlineQueryResultAudio struct {
	ID string `json:"id"` // Unique identifier of the query result
	Title string `json:"title"` // Title of the audio file
	Performer string `json:"performer"` // Performer of the audio file
	AudioURL string `json:"audio_url"` // The URL of the audio file
	AudioDuration int32 `json:"audio_duration"` // Audio file duration, in seconds
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageAudio, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultAudio) GetType() string { return "inputInlineQueryResultAudio" }

// InputInlineQueryResultContact — Represents a user contact
type InputInlineQueryResultContact struct {
	ID string `json:"id"` // Unique identifier of the query result
	Contact *Contact `json:"contact"` // User contact
	ThumbnailURL string `json:"thumbnail_url"` // URL of the result thumbnail, if it exists
	ThumbnailWidth int32 `json:"thumbnail_width"` // Thumbnail width, if known
	ThumbnailHeight int32 `json:"thumbnail_height"` // Thumbnail height, if known
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultContact) GetType() string { return "inputInlineQueryResultContact" }

// InputInlineQueryResultDocument — Represents a link to a file
type InputInlineQueryResultDocument struct {
	ID string `json:"id"` // Unique identifier of the query result
	Title string `json:"title"` // Title of the resulting file
	Description string `json:"description"` // Represents a link to a file
	DocumentURL string `json:"document_url"` // URL of the file
	MimeType string `json:"mime_type"` // MIME type of the file content; only "application/pdf" and "application/zip" are currently allowed
	ThumbnailURL string `json:"thumbnail_url"` // The URL of the file thumbnail, if it exists
	ThumbnailWidth int32 `json:"thumbnail_width"` // Width of the thumbnail
	ThumbnailHeight int32 `json:"thumbnail_height"` // Height of the thumbnail
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageDocument, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultDocument) GetType() string { return "inputInlineQueryResultDocument" }

// InputInlineQueryResultGame — Represents a game
type InputInlineQueryResultGame struct {
	ID string `json:"id"` // Unique identifier of the query result
	GameShortName string `json:"game_short_name"` // Short name of the game
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
}

func (t *InputInlineQueryResultGame) GetType() string { return "inputInlineQueryResultGame" }

// InputInlineQueryResultLocation — Represents a point on the map
type InputInlineQueryResultLocation struct {
	ID string `json:"id"` // Unique identifier of the query result
	Location *Location `json:"location"` // Location result
	LivePeriod int32 `json:"live_period"` // Amount of time relative to the message sent time until the location can be updated, in seconds
	Title string `json:"title"` // Title of the result
	ThumbnailURL string `json:"thumbnail_url"` // URL of the result thumbnail, if it exists
	ThumbnailWidth int32 `json:"thumbnail_width"` // Thumbnail width, if known
	ThumbnailHeight int32 `json:"thumbnail_height"` // Thumbnail height, if known
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultLocation) GetType() string { return "inputInlineQueryResultLocation" }

// InputInlineQueryResultPhoto — Represents link to a JPEG image
type InputInlineQueryResultPhoto struct {
	ID string `json:"id"` // Unique identifier of the query result
	Title string `json:"title"` // Title of the result, if known
	Description string `json:"description"` // Represents link to a JPEG image
	ThumbnailURL string `json:"thumbnail_url"` // URL of the photo thumbnail, if it exists
	PhotoURL string `json:"photo_url"` // The URL of the JPEG photo (photo size must not exceed 5MB)
	PhotoWidth int32 `json:"photo_width"` // Width of the photo
	PhotoHeight int32 `json:"photo_height"` // Height of the photo
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessagePhoto, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultPhoto) GetType() string { return "inputInlineQueryResultPhoto" }

// InputInlineQueryResultSticker — Represents a link to a WEBP, TGS, or WEBM sticker
type InputInlineQueryResultSticker struct {
	ID string `json:"id"` // Unique identifier of the query result
	ThumbnailURL string `json:"thumbnail_url"` // URL of the sticker thumbnail, if it exists
	StickerURL string `json:"sticker_url"` // The URL of the WEBP, TGS, or WEBM sticker (sticker file size must not exceed 5MB)
	StickerWidth int32 `json:"sticker_width"` // Width of the sticker
	StickerHeight int32 `json:"sticker_height"` // Height of the sticker
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageSticker, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultSticker) GetType() string { return "inputInlineQueryResultSticker" }

// InputInlineQueryResultVenue — Represents information about a venue
type InputInlineQueryResultVenue struct {
	ID string `json:"id"` // Unique identifier of the query result
	Venue *Venue `json:"venue"` // Venue result
	ThumbnailURL string `json:"thumbnail_url"` // URL of the result thumbnail, if it exists
	ThumbnailWidth int32 `json:"thumbnail_width"` // Thumbnail width, if known
	ThumbnailHeight int32 `json:"thumbnail_height"` // Thumbnail height, if known
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultVenue) GetType() string { return "inputInlineQueryResultVenue" }

// InputInlineQueryResultVideo — Represents a link to a page containing an embedded video player or a video file
type InputInlineQueryResultVideo struct {
	ID string `json:"id"` // Unique identifier of the query result
	Title string `json:"title"` // Title of the result
	Description string `json:"description"` // Represents a link to a page containing an embedded video player or a video file
	ThumbnailURL string `json:"thumbnail_url"` // The URL of the video thumbnail (JPEG), if it exists
	VideoURL string `json:"video_url"` // URL of the embedded video player or video file
	MimeType string `json:"mime_type"` // MIME type of the content of the video URL, only "text/html" or "video/mp4" are currently supported
	VideoWidth int32 `json:"video_width"` // Width of the video
	VideoHeight int32 `json:"video_height"` // Height of the video
	VideoDuration int32 `json:"video_duration"` // Video duration, in seconds
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageVideo, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultVideo) GetType() string { return "inputInlineQueryResultVideo" }

// InputInlineQueryResultVoiceNote — Represents a link to an opus-encoded audio file within an OGG container, single channel audio
type InputInlineQueryResultVoiceNote struct {
	ID string `json:"id"` // Unique identifier of the query result
	Title string `json:"title"` // Title of the voice note
	VoiceNoteURL string `json:"voice_note_url"` // The URL of the voice note file
	VoiceNoteDuration int32 `json:"voice_note_duration"` // Duration of the voice note, in seconds
	ReplyMarkup *ReplyMarkup `json:"reply_markup"` // The message reply markup; pass null if none. Must be of type replyMarkupInlineKeyboard or null
	InputMessageContent *InputMessageContent `json:"input_message_content"` // The content of the message to be sent. Must be one of the following types: inputMessageText, inputMessageVoiceNote, inputMessageInvoice, inputMessageLocation, inputMessageVenue or inputMessageContact
}

func (t *InputInlineQueryResultVoiceNote) GetType() string { return "inputInlineQueryResultVoiceNote" }

// InlineQueryResult — Represents a single result of an inline query
type InlineQueryResult struct {
}

func (t *InlineQueryResult) GetType() string { return "InlineQueryResult" }

// InlineQueryResultArticle — Represents a link to an article or web page
type InlineQueryResultArticle struct {
	ID string `json:"id"` // Unique identifier of the query result
	URL string `json:"url"` // URL of the result, if it exists
	Title string `json:"title"` // Title of the result
	Description string `json:"description"` // Represents a link to an article or web page
	Thumbnail *Thumbnail `json:"thumbnail"` // Result thumbnail in JPEG format; may be null
}

func (t *InlineQueryResultArticle) GetType() string { return "inlineQueryResultArticle" }

// InlineQueryResultContact — Represents a user contact
type InlineQueryResultContact struct {
	ID string `json:"id"` // Unique identifier of the query result
	Contact *Contact `json:"contact"` // A user contact
	Thumbnail *Thumbnail `json:"thumbnail"` // Result thumbnail in JPEG format; may be null
}

func (t *InlineQueryResultContact) GetType() string { return "inlineQueryResultContact" }

// InlineQueryResultLocation — Represents a point on the map
type InlineQueryResultLocation struct {
	ID string `json:"id"` // Unique identifier of the query result
	Location *Location `json:"location"` // Location result
	Title string `json:"title"` // Title of the result
	Thumbnail *Thumbnail `json:"thumbnail"` // Result thumbnail in JPEG format; may be null
}

func (t *InlineQueryResultLocation) GetType() string { return "inlineQueryResultLocation" }

// InlineQueryResultVenue — Represents information about a venue
type InlineQueryResultVenue struct {
	ID string `json:"id"` // Unique identifier of the query result
	Venue *Venue `json:"venue"` // Venue result
	Thumbnail *Thumbnail `json:"thumbnail"` // Result thumbnail in JPEG format; may be null
}

func (t *InlineQueryResultVenue) GetType() string { return "inlineQueryResultVenue" }

// InlineQueryResultGame — Represents information about a game
type InlineQueryResultGame struct {
	ID string `json:"id"` // Unique identifier of the query result
	Game *Game `json:"game"` // Game result
}

func (t *InlineQueryResultGame) GetType() string { return "inlineQueryResultGame" }

// InlineQueryResultAnimation — Represents an animation file
type InlineQueryResultAnimation struct {
	ID string `json:"id"` // Unique identifier of the query result
	Animation *Animation `json:"animation"` // Animation file
	Title string `json:"title"` // Animation title
}

func (t *InlineQueryResultAnimation) GetType() string { return "inlineQueryResultAnimation" }

// InlineQueryResultAudio — Represents an audio file
type InlineQueryResultAudio struct {
	ID string `json:"id"` // Unique identifier of the query result
	Audio *Audio `json:"audio"` // Audio file
}

func (t *InlineQueryResultAudio) GetType() string { return "inlineQueryResultAudio" }

// InlineQueryResultDocument — Represents a document
type InlineQueryResultDocument struct {
	ID string `json:"id"` // Unique identifier of the query result
	Document *Document `json:"document"` // Document
	Title string `json:"title"` // Document title
	Description string `json:"description"` // Represents a document
}

func (t *InlineQueryResultDocument) GetType() string { return "inlineQueryResultDocument" }

// InlineQueryResultPhoto — Represents a photo
type InlineQueryResultPhoto struct {
	ID string `json:"id"` // Unique identifier of the query result
	Photo *Photo `json:"photo"` // Photo
	Title string `json:"title"` // Title of the result, if known
	Description string `json:"description"` // Represents a photo
}

func (t *InlineQueryResultPhoto) GetType() string { return "inlineQueryResultPhoto" }

// InlineQueryResultSticker — Represents a sticker
type InlineQueryResultSticker struct {
	ID string `json:"id"` // Unique identifier of the query result
	Sticker *Sticker `json:"sticker"` // Sticker
}

func (t *InlineQueryResultSticker) GetType() string { return "inlineQueryResultSticker" }

// InlineQueryResultVideo — Represents a video
type InlineQueryResultVideo struct {
	ID string `json:"id"` // Unique identifier of the query result
	Video *Video `json:"video"` // Video
	Title string `json:"title"` // Title of the video
	Description string `json:"description"` // Represents a video
}

func (t *InlineQueryResultVideo) GetType() string { return "inlineQueryResultVideo" }

// InlineQueryResultVoiceNote — Represents a voice note
type InlineQueryResultVoiceNote struct {
	ID string `json:"id"` // Unique identifier of the query result
	VoiceNote *VoiceNote `json:"voice_note"` // Voice note
	Title string `json:"title"` // Title of the voice note
}

func (t *InlineQueryResultVoiceNote) GetType() string { return "inlineQueryResultVoiceNote" }

// InlineQueryResultsButtonType — Represents type of button in results of inline query
type InlineQueryResultsButtonType struct {
}

func (t *InlineQueryResultsButtonType) GetType() string { return "InlineQueryResultsButtonType" }

// InlineQueryResultsButtonTypeStartBot — Describes the button that opens a private chat with the bot and sends a start message to the bot with the given parameter @parameter The parameter for the bot start message
type InlineQueryResultsButtonTypeStartBot struct {
	Parameter string `json:"parameter"`
}

func (t *InlineQueryResultsButtonTypeStartBot) GetType() string { return "inlineQueryResultsButtonTypeStartBot" }

// InlineQueryResultsButtonTypeWebApp — Describes the button that opens a Web App by calling getWebAppUrl @url An HTTP URL to pass to getWebAppUrl
type InlineQueryResultsButtonTypeWebApp struct {
	URL string `json:"url"`
}

func (t *InlineQueryResultsButtonTypeWebApp) GetType() string { return "inlineQueryResultsButtonTypeWebApp" }

// InlineQueryResultsButton — Represents a button to be shown above inline query results @text The text of the button @type Type of the button
type InlineQueryResultsButton struct {
	Text string `json:"text"`
	Type *InlineQueryResultsButtonType `json:"type"`
}

func (t *InlineQueryResultsButton) GetType() string { return "inlineQueryResultsButton" }

// InlineQueryResults — Represents the results of the inline query. Use sendInlineQueryResultMessage to send the result of the query
type InlineQueryResults struct {
	InlineQueryID JSONInt64 `json:"inline_query_id"` // Unique identifier of the inline query
	Button *InlineQueryResultsButton `json:"button"` // Button to be shown above inline query results; may be null
	Results []*InlineQueryResult `json:"results"` // Results of the query
	NextOffset string `json:"next_offset"` // The offset for the next request. If empty, then there are no more results
}

func (t *InlineQueryResults) GetType() string { return "inlineQueryResults" }

// PreparedInlineMessageID — Represents an inline message that can be sent via the bot
type PreparedInlineMessageID struct {
	ID string `json:"id"` // Unique identifier for the message
	ExpirationDate int32 `json:"expiration_date"` // Point in time (Unix timestamp) when the message can't be used anymore
}

func (t *PreparedInlineMessageID) GetType() string { return "preparedInlineMessageId" }

// PreparedInlineMessage — Represents a ready to send inline message. Use sendInlineQueryResultMessage to send the message
type PreparedInlineMessage struct {
	InlineQueryID JSONInt64 `json:"inline_query_id"` // Unique identifier of the inline query to pass to sendInlineQueryResultMessage
	Result *InlineQueryResult `json:"result"` // Resulted inline message of the query
	ChatTypes *TargetChatTypes `json:"chat_types"` // Types of the chats to which the message can be sent
}

func (t *PreparedInlineMessage) GetType() string { return "preparedInlineMessage" }

// CallbackQueryPayload — Represents a payload of a callback query
type CallbackQueryPayload struct {
}

func (t *CallbackQueryPayload) GetType() string { return "CallbackQueryPayload" }

// CallbackQueryPayloadData — The payload for a general callback button @data Data that was attached to the callback button
type CallbackQueryPayloadData struct {
	Data []byte `json:"data"`
}

func (t *CallbackQueryPayloadData) GetType() string { return "callbackQueryPayloadData" }

// CallbackQueryPayloadDataWithPassword — The payload for a callback button requiring password @password The 2-step verification password for the current user @data Data that was attached to the callback button
type CallbackQueryPayloadDataWithPassword struct {
	Password string `json:"password"`
	Data []byte `json:"data"`
}

func (t *CallbackQueryPayloadDataWithPassword) GetType() string { return "callbackQueryPayloadDataWithPassword" }

// CallbackQueryPayloadGame — The payload for a game callback button @game_short_name A short name of the game that was attached to the callback button
type CallbackQueryPayloadGame struct {
	GameShortName string `json:"game_short_name"`
}

func (t *CallbackQueryPayloadGame) GetType() string { return "callbackQueryPayloadGame" }

// CallbackQueryAnswer — Contains a bot's answer to a callback query @text Text of the answer @show_alert True, if an alert must be shown to the user instead of a toast notification @url URL to be opened
type CallbackQueryAnswer struct {
	Text string `json:"text"`
	ShowAlert bool `json:"show_alert"`
	URL string `json:"url"`
}

func (t *CallbackQueryAnswer) GetType() string { return "callbackQueryAnswer" }

// CustomRequestResult — Contains the result of a custom request @result A JSON-serialized result
type CustomRequestResult struct {
	Result string `json:"result"`
}

func (t *CustomRequestResult) GetType() string { return "customRequestResult" }

// GameHighScore — Contains one row of the game high score table @position Position in the high score table @user_id User identifier @score User score
type GameHighScore struct {
	Position int32 `json:"position"`
	UserID int64 `json:"user_id"`
	Score int32 `json:"score"`
}

func (t *GameHighScore) GetType() string { return "gameHighScore" }

// GameHighScores — Contains a list of game high scores @scores A list of game high scores
type GameHighScores struct {
	Scores []*GameHighScore `json:"scores"`
}

func (t *GameHighScores) GetType() string { return "gameHighScores" }

// ChatEventAction — Represents a chat event
type ChatEventAction struct {
}

func (t *ChatEventAction) GetType() string { return "ChatEventAction" }

// ChatEventMessageEdited — A message was edited @old_message The original message before the edit @new_message The message after it was edited
type ChatEventMessageEdited struct {
	OldMessage *Message `json:"old_message"`
	NewMessage *Message `json:"new_message"`
}

func (t *ChatEventMessageEdited) GetType() string { return "chatEventMessageEdited" }

// ChatEventMessageDeleted — A message was deleted @message Deleted message @can_report_anti_spam_false_positive True, if the message deletion can be reported via reportSupergroupAntiSpamFalsePositive
type ChatEventMessageDeleted struct {
	Message *Message `json:"message"`
	CanReportAntiSpamFalsePositive bool `json:"can_report_anti_spam_false_positive"`
}

func (t *ChatEventMessageDeleted) GetType() string { return "chatEventMessageDeleted" }

// ChatEventMessagePinned — A message was pinned @message Pinned message
type ChatEventMessagePinned struct {
	Message *Message `json:"message"`
}

func (t *ChatEventMessagePinned) GetType() string { return "chatEventMessagePinned" }

// ChatEventMessageUnpinned — A message was unpinned @message Unpinned message
type ChatEventMessageUnpinned struct {
	Message *Message `json:"message"`
}

func (t *ChatEventMessageUnpinned) GetType() string { return "chatEventMessageUnpinned" }

// ChatEventPollStopped — A poll in a message was stopped @message The message with the poll
type ChatEventPollStopped struct {
	Message *Message `json:"message"`
}

func (t *ChatEventPollStopped) GetType() string { return "chatEventPollStopped" }

// ChatEventMemberJoined — A new member joined the chat
type ChatEventMemberJoined struct {
}

func (t *ChatEventMemberJoined) GetType() string { return "chatEventMemberJoined" }

// ChatEventMemberJoinedByInviteLink — A new member joined the chat via an invite link @invite_link Invite link used to join the chat @via_chat_folder_invite_link True, if the user has joined the chat using an invite link for a chat folder
type ChatEventMemberJoinedByInviteLink struct {
	InviteLink *ChatInviteLink `json:"invite_link"`
	ViaChatFolderInviteLink bool `json:"via_chat_folder_invite_link"`
}

func (t *ChatEventMemberJoinedByInviteLink) GetType() string { return "chatEventMemberJoinedByInviteLink" }

// ChatEventMemberJoinedByRequest — A new member was accepted to the chat by an administrator @approver_user_id User identifier of the chat administrator, approved user join request @invite_link Invite link used to join the chat; may be null
type ChatEventMemberJoinedByRequest struct {
	ApproverUserID int64 `json:"approver_user_id"`
	InviteLink *ChatInviteLink `json:"invite_link"`
}

func (t *ChatEventMemberJoinedByRequest) GetType() string { return "chatEventMemberJoinedByRequest" }

// ChatEventMemberInvited — A new chat member was invited @user_id New member user identifier @status New member status
type ChatEventMemberInvited struct {
	UserID int64 `json:"user_id"`
	Status *ChatMemberStatus `json:"status"`
}

func (t *ChatEventMemberInvited) GetType() string { return "chatEventMemberInvited" }

// ChatEventMemberLeft — A member left the chat
type ChatEventMemberLeft struct {
}

func (t *ChatEventMemberLeft) GetType() string { return "chatEventMemberLeft" }

// ChatEventMemberPromoted — A chat member has gained/lost administrator status, or the list of their administrator privileges has changed @user_id Affected chat member user identifier @old_status Previous status of the chat member @new_status New status of the chat member
type ChatEventMemberPromoted struct {
	UserID int64 `json:"user_id"`
	OldStatus *ChatMemberStatus `json:"old_status"`
	NewStatus *ChatMemberStatus `json:"new_status"`
}

func (t *ChatEventMemberPromoted) GetType() string { return "chatEventMemberPromoted" }

// ChatEventMemberRestricted — A chat member was restricted/unrestricted or banned/unbanned, or the list of their restrictions has changed @member_id Affected chat member identifier @old_status Previous status of the chat member @new_status New status of the chat member
type ChatEventMemberRestricted struct {
	MemberID *MessageSender `json:"member_id"`
	OldStatus *ChatMemberStatus `json:"old_status"`
	NewStatus *ChatMemberStatus `json:"new_status"`
}

func (t *ChatEventMemberRestricted) GetType() string { return "chatEventMemberRestricted" }

// ChatEventMemberTagChanged — A chat member tag has been changed @user_id Affected chat member user identifier @old_tag Previous tag of the chat member @new_tag New tag of the chat member
type ChatEventMemberTagChanged struct {
	UserID int64 `json:"user_id"`
	OldTag string `json:"old_tag"`
	NewTag string `json:"new_tag"`
}

func (t *ChatEventMemberTagChanged) GetType() string { return "chatEventMemberTagChanged" }

// ChatEventMemberSubscriptionExtended — A chat member extended their subscription to the chat @user_id Affected chat member user identifier @old_status Previous status of the chat member @new_status New status of the chat member
type ChatEventMemberSubscriptionExtended struct {
	UserID int64 `json:"user_id"`
	OldStatus *ChatMemberStatus `json:"old_status"`
	NewStatus *ChatMemberStatus `json:"new_status"`
}

func (t *ChatEventMemberSubscriptionExtended) GetType() string { return "chatEventMemberSubscriptionExtended" }

// ChatEventAvailableReactionsChanged — The chat available reactions were changed @old_available_reactions Previous chat available reactions @new_available_reactions New chat available reactions
type ChatEventAvailableReactionsChanged struct {
	OldAvailableReactions *ChatAvailableReactions `json:"old_available_reactions"`
	NewAvailableReactions *ChatAvailableReactions `json:"new_available_reactions"`
}

func (t *ChatEventAvailableReactionsChanged) GetType() string { return "chatEventAvailableReactionsChanged" }

// ChatEventBackgroundChanged — The chat background was changed @old_background Previous background; may be null if none @new_background New background; may be null if none
type ChatEventBackgroundChanged struct {
	OldBackground *ChatBackground `json:"old_background"`
	NewBackground *ChatBackground `json:"new_background"`
}

func (t *ChatEventBackgroundChanged) GetType() string { return "chatEventBackgroundChanged" }

// ChatEventDescriptionChanged — The chat description was changed @old_description Previous chat description @new_description New chat description
type ChatEventDescriptionChanged struct {
	OldDescription string `json:"old_description"`
	NewDescription string `json:"new_description"`
}

func (t *ChatEventDescriptionChanged) GetType() string { return "chatEventDescriptionChanged" }

// ChatEventEmojiStatusChanged — The chat emoji status was changed @old_emoji_status Previous emoji status; may be null if none @new_emoji_status New emoji status; may be null if none
type ChatEventEmojiStatusChanged struct {
	OldEmojiStatus *EmojiStatus `json:"old_emoji_status"`
	NewEmojiStatus *EmojiStatus `json:"new_emoji_status"`
}

func (t *ChatEventEmojiStatusChanged) GetType() string { return "chatEventEmojiStatusChanged" }

// ChatEventLinkedChatChanged — The linked chat of a supergroup was changed @old_linked_chat_id Previous supergroup linked chat identifier @new_linked_chat_id New supergroup linked chat identifier
type ChatEventLinkedChatChanged struct {
	OldLinkedChatID int64 `json:"old_linked_chat_id"`
	NewLinkedChatID int64 `json:"new_linked_chat_id"`
}

func (t *ChatEventLinkedChatChanged) GetType() string { return "chatEventLinkedChatChanged" }

// ChatEventLocationChanged — The supergroup location was changed @old_location Previous location; may be null @new_location New location; may be null
type ChatEventLocationChanged struct {
	OldLocation *ChatLocation `json:"old_location"`
	NewLocation *ChatLocation `json:"new_location"`
}

func (t *ChatEventLocationChanged) GetType() string { return "chatEventLocationChanged" }

// ChatEventMessageAutoDeleteTimeChanged — The message auto-delete timer was changed @old_message_auto_delete_time Previous value of message_auto_delete_time @new_message_auto_delete_time New value of message_auto_delete_time
type ChatEventMessageAutoDeleteTimeChanged struct {
	OldMessageAutoDeleteTime int32 `json:"old_message_auto_delete_time"`
	NewMessageAutoDeleteTime int32 `json:"new_message_auto_delete_time"`
}

func (t *ChatEventMessageAutoDeleteTimeChanged) GetType() string { return "chatEventMessageAutoDeleteTimeChanged" }

// ChatEventPermissionsChanged — The chat permissions were changed @old_permissions Previous chat permissions @new_permissions New chat permissions
type ChatEventPermissionsChanged struct {
	OldPermissions *ChatPermissions `json:"old_permissions"`
	NewPermissions *ChatPermissions `json:"new_permissions"`
}

func (t *ChatEventPermissionsChanged) GetType() string { return "chatEventPermissionsChanged" }

// ChatEventPhotoChanged — The chat photo was changed @old_photo Previous chat photo value; may be null @new_photo New chat photo value; may be null
type ChatEventPhotoChanged struct {
	OldPhoto *ChatPhoto `json:"old_photo"`
	NewPhoto *ChatPhoto `json:"new_photo"`
}

func (t *ChatEventPhotoChanged) GetType() string { return "chatEventPhotoChanged" }

// ChatEventSlowModeDelayChanged — The slow_mode_delay setting of a supergroup was changed @old_slow_mode_delay Previous value of slow_mode_delay, in seconds @new_slow_mode_delay New value of slow_mode_delay, in seconds
type ChatEventSlowModeDelayChanged struct {
	OldSlowModeDelay int32 `json:"old_slow_mode_delay"`
	NewSlowModeDelay int32 `json:"new_slow_mode_delay"`
}

func (t *ChatEventSlowModeDelayChanged) GetType() string { return "chatEventSlowModeDelayChanged" }

// ChatEventStickerSetChanged — The supergroup sticker set was changed @old_sticker_set_id Previous identifier of the chat sticker set; 0 if none @new_sticker_set_id New identifier of the chat sticker set; 0 if none
type ChatEventStickerSetChanged struct {
	OldStickerSetID JSONInt64 `json:"old_sticker_set_id"`
	NewStickerSetID JSONInt64 `json:"new_sticker_set_id"`
}

func (t *ChatEventStickerSetChanged) GetType() string { return "chatEventStickerSetChanged" }

// ChatEventCustomEmojiStickerSetChanged — The supergroup sticker set with allowed custom emoji was changed @old_sticker_set_id Previous identifier of the chat sticker set; 0 if none @new_sticker_set_id New identifier of the chat sticker set; 0 if none
type ChatEventCustomEmojiStickerSetChanged struct {
	OldStickerSetID JSONInt64 `json:"old_sticker_set_id"`
	NewStickerSetID JSONInt64 `json:"new_sticker_set_id"`
}

func (t *ChatEventCustomEmojiStickerSetChanged) GetType() string { return "chatEventCustomEmojiStickerSetChanged" }

// ChatEventTitleChanged — The chat title was changed @old_title Previous chat title @new_title New chat title
type ChatEventTitleChanged struct {
	OldTitle string `json:"old_title"`
	NewTitle string `json:"new_title"`
}

func (t *ChatEventTitleChanged) GetType() string { return "chatEventTitleChanged" }

// ChatEventUsernameChanged — The chat editable username was changed @old_username Previous chat username @new_username New chat username
type ChatEventUsernameChanged struct {
	OldUsername string `json:"old_username"`
	NewUsername string `json:"new_username"`
}

func (t *ChatEventUsernameChanged) GetType() string { return "chatEventUsernameChanged" }

// ChatEventActiveUsernamesChanged — The chat active usernames were changed @old_usernames Previous list of active usernames @new_usernames New list of active usernames
type ChatEventActiveUsernamesChanged struct {
	OldUsernames []string `json:"old_usernames"`
	NewUsernames []string `json:"new_usernames"`
}

func (t *ChatEventActiveUsernamesChanged) GetType() string { return "chatEventActiveUsernamesChanged" }

// ChatEventAccentColorChanged — The chat accent color or background custom emoji were changed
type ChatEventAccentColorChanged struct {
	OldAccentColorID int32 `json:"old_accent_color_id"` // Previous identifier of chat accent color
	OldBackgroundCustomEmojiID JSONInt64 `json:"old_background_custom_emoji_id"` // Previous identifier of the custom emoji; 0 if none
	NewAccentColorID int32 `json:"new_accent_color_id"` // New identifier of chat accent color
	NewBackgroundCustomEmojiID JSONInt64 `json:"new_background_custom_emoji_id"` // New identifier of the custom emoji; 0 if none
}

func (t *ChatEventAccentColorChanged) GetType() string { return "chatEventAccentColorChanged" }

// ChatEventProfileAccentColorChanged — The chat's profile accent color or profile background custom emoji were changed
type ChatEventProfileAccentColorChanged struct {
	OldProfileAccentColorID int32 `json:"old_profile_accent_color_id"` // Previous identifier of chat's profile accent color; -1 if none
	OldProfileBackgroundCustomEmojiID JSONInt64 `json:"old_profile_background_custom_emoji_id"` // Previous identifier of the custom emoji; 0 if none
	NewProfileAccentColorID int32 `json:"new_profile_accent_color_id"` // New identifier of chat's profile accent color; -1 if none
	NewProfileBackgroundCustomEmojiID JSONInt64 `json:"new_profile_background_custom_emoji_id"` // New identifier of the custom emoji; 0 if none
}

func (t *ChatEventProfileAccentColorChanged) GetType() string { return "chatEventProfileAccentColorChanged" }

// ChatEventHasProtectedContentToggled — The has_protected_content setting of a channel was toggled @has_protected_content New value of has_protected_content
type ChatEventHasProtectedContentToggled struct {
	HasProtectedContent bool `json:"has_protected_content"`
}

func (t *ChatEventHasProtectedContentToggled) GetType() string { return "chatEventHasProtectedContentToggled" }

// ChatEventInvitesToggled — The can_invite_users permission of a supergroup chat was toggled @can_invite_users New value of can_invite_users permission
type ChatEventInvitesToggled struct {
	CanInviteUsers bool `json:"can_invite_users"`
}

func (t *ChatEventInvitesToggled) GetType() string { return "chatEventInvitesToggled" }

// ChatEventIsAllHistoryAvailableToggled — The is_all_history_available setting of a supergroup was toggled @is_all_history_available New value of is_all_history_available
type ChatEventIsAllHistoryAvailableToggled struct {
	IsAllHistoryAvailable bool `json:"is_all_history_available"`
}

func (t *ChatEventIsAllHistoryAvailableToggled) GetType() string { return "chatEventIsAllHistoryAvailableToggled" }

// ChatEventHasAggressiveAntiSpamEnabledToggled — The has_aggressive_anti_spam_enabled setting of a supergroup was toggled @has_aggressive_anti_spam_enabled New value of has_aggressive_anti_spam_enabled
type ChatEventHasAggressiveAntiSpamEnabledToggled struct {
	HasAggressiveAntiSpamEnabled bool `json:"has_aggressive_anti_spam_enabled"`
}

func (t *ChatEventHasAggressiveAntiSpamEnabledToggled) GetType() string { return "chatEventHasAggressiveAntiSpamEnabledToggled" }

// ChatEventSignMessagesToggled — The sign_messages setting of a channel was toggled @sign_messages New value of sign_messages
type ChatEventSignMessagesToggled struct {
	SignMessages bool `json:"sign_messages"`
}

func (t *ChatEventSignMessagesToggled) GetType() string { return "chatEventSignMessagesToggled" }

