// Code generated by go-tdlib codegen. DO NOT EDIT.
package tdapi

// InputCredentials — Contains information about the payment method chosen by the user
type InputCredentials struct {
}

func (t *InputCredentials) GetType() string { return "InputCredentials" }

// InputCredentialsSaved — Applies if a user chooses some previously saved payment credentials. To use their previously saved credentials, the user must have a valid temporary password @saved_credentials_id Identifier of the saved credentials
type InputCredentialsSaved struct {
	SavedCredentialsID string `json:"saved_credentials_id"`
}

func (t *InputCredentialsSaved) GetType() string { return "inputCredentialsSaved" }

// InputCredentialsNew — Applies if a user enters new credentials on a payment provider website @data JSON-encoded data with the credential identifier from the payment provider @allow_save True, if the credential identifier can be saved on the server side
type InputCredentialsNew struct {
	Data string `json:"data"`
	AllowSave bool `json:"allow_save"`
}

func (t *InputCredentialsNew) GetType() string { return "inputCredentialsNew" }

// InputCredentialsApplePay — Applies if a user enters new credentials using Apple Pay @data JSON-encoded data with the credential identifier
type InputCredentialsApplePay struct {
	Data string `json:"data"`
}

func (t *InputCredentialsApplePay) GetType() string { return "inputCredentialsApplePay" }

// InputCredentialsGooglePay — Applies if a user enters new credentials using Google Pay @data JSON-encoded data with the credential identifier
type InputCredentialsGooglePay struct {
	Data string `json:"data"`
}

func (t *InputCredentialsGooglePay) GetType() string { return "inputCredentialsGooglePay" }

// PaymentProvider — Contains information about a payment provider
type PaymentProvider struct {
}

func (t *PaymentProvider) GetType() string { return "PaymentProvider" }

// PaymentProviderSmartGlocal — Smart Glocal payment provider @public_token Public payment token @tokenize_url URL for sending card tokenization requests
type PaymentProviderSmartGlocal struct {
	PublicToken string `json:"public_token"`
	TokenizeURL string `json:"tokenize_url"`
}

func (t *PaymentProviderSmartGlocal) GetType() string { return "paymentProviderSmartGlocal" }

// PaymentProviderStripe — Stripe payment provider
type PaymentProviderStripe struct {
	PublishableKey string `json:"publishable_key"` // Stripe API publishable key
	NeedCountry bool `json:"need_country"` // True, if the user country must be provided
	NeedPostalCode bool `json:"need_postal_code"` // True, if the user ZIP/postal code must be provided
	NeedCardholderName bool `json:"need_cardholder_name"` // True, if the cardholder name must be provided
}

func (t *PaymentProviderStripe) GetType() string { return "paymentProviderStripe" }

// PaymentProviderOther — Some other payment provider, for which a web payment form must be shown @url Payment form URL
type PaymentProviderOther struct {
	URL string `json:"url"`
}

func (t *PaymentProviderOther) GetType() string { return "paymentProviderOther" }

// PaymentOption — Describes an additional payment option @title Title for the payment option @url Payment form URL to be opened in a web view
type PaymentOption struct {
	Title string `json:"title"`
	URL string `json:"url"`
}

func (t *PaymentOption) GetType() string { return "paymentOption" }

// PaymentFormType — Describes type of payment form
type PaymentFormType struct {
}

func (t *PaymentFormType) GetType() string { return "PaymentFormType" }

// PaymentFormTypeRegular — The payment form is for a regular payment
type PaymentFormTypeRegular struct {
	Invoice *Invoice `json:"invoice"` // Full information about the invoice
	PaymentProviderUserID int64 `json:"payment_provider_user_id"` // User identifier of the payment provider bot
	PaymentProvider *PaymentProvider `json:"payment_provider"` // Information about the payment provider
	AdditionalPaymentOptions []*PaymentOption `json:"additional_payment_options"` // The list of additional payment options
	SavedOrderInfo *OrderInfo `json:"saved_order_info"` // Saved server-side order information; may be null
	SavedCredentials []*SavedCredentials `json:"saved_credentials"` // The list of saved payment credentials
	CanSaveCredentials bool `json:"can_save_credentials"` // True, if the user can choose to save credentials
	NeedPassword bool `json:"need_password"` // True, if the user will be able to save credentials, if sets up a 2-step verification password
}

func (t *PaymentFormTypeRegular) GetType() string { return "paymentFormTypeRegular" }

// PaymentFormTypeStars — The payment form is for a payment in Telegram Stars @star_count Number of Telegram Stars that will be paid
type PaymentFormTypeStars struct {
	StarCount int64 `json:"star_count"`
}

func (t *PaymentFormTypeStars) GetType() string { return "paymentFormTypeStars" }

// PaymentFormTypeStarSubscription — The payment form is for a payment in Telegram Stars for subscription @pricing Information about subscription plan
type PaymentFormTypeStarSubscription struct {
	Pricing *StarSubscriptionPricing `json:"pricing"`
}

func (t *PaymentFormTypeStarSubscription) GetType() string { return "paymentFormTypeStarSubscription" }

// PaymentForm — Contains information about an invoice payment form
type PaymentForm struct {
	ID JSONInt64 `json:"id"` // The payment form identifier
	Type *PaymentFormType `json:"type"` // Type of the payment form
	SellerBotUserID int64 `json:"seller_bot_user_id"` // User identifier of the seller bot
	ProductInfo *ProductInfo `json:"product_info"` // Information about the product
}

func (t *PaymentForm) GetType() string { return "paymentForm" }

// ValidatedOrderInfo — Contains a temporary identifier of validated order information, which is stored for one hour, and the available shipping options @order_info_id Temporary identifier of the order information @shipping_options Available shipping options
type ValidatedOrderInfo struct {
	OrderInfoID string `json:"order_info_id"`
	ShippingOptions []*ShippingOption `json:"shipping_options"`
}

func (t *ValidatedOrderInfo) GetType() string { return "validatedOrderInfo" }

// PaymentResult — Contains the result of a payment request @success True, if the payment request was successful; otherwise, the verification_url will be non-empty @verification_url URL for additional payment credentials verification
type PaymentResult struct {
	Success bool `json:"success"`
	VerificationURL string `json:"verification_url"`
}

func (t *PaymentResult) GetType() string { return "paymentResult" }

// PaymentReceiptType — Describes type of successful payment
type PaymentReceiptType struct {
}

func (t *PaymentReceiptType) GetType() string { return "PaymentReceiptType" }

// PaymentReceiptTypeRegular — The payment was done using a third-party payment provider
type PaymentReceiptTypeRegular struct {
	PaymentProviderUserID int64 `json:"payment_provider_user_id"` // User identifier of the payment provider bot
	Invoice *Invoice `json:"invoice"` // Information about the invoice
	OrderInfo *OrderInfo `json:"order_info"` // Order information; may be null
	ShippingOption *ShippingOption `json:"shipping_option"` // Chosen shipping option; may be null
	CredentialsTitle string `json:"credentials_title"` // Title of the saved credentials chosen by the buyer
	TipAmount int64 `json:"tip_amount"` // The amount of tip chosen by the buyer in the smallest units of the currency
}

func (t *PaymentReceiptTypeRegular) GetType() string { return "paymentReceiptTypeRegular" }

// PaymentReceiptTypeStars — The payment was done using Telegram Stars
type PaymentReceiptTypeStars struct {
	StarCount int64 `json:"star_count"` // Number of Telegram Stars that were paid
	TransactionID string `json:"transaction_id"` // Unique identifier of the transaction that can be used to dispute it
}

func (t *PaymentReceiptTypeStars) GetType() string { return "paymentReceiptTypeStars" }

// PaymentReceipt — Contains information about a successful payment
type PaymentReceipt struct {
	ProductInfo *ProductInfo `json:"product_info"` // Information about the product
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the payment was made
	SellerBotUserID int64 `json:"seller_bot_user_id"` // User identifier of the seller bot
	Type *PaymentReceiptType `json:"type"` // Type of the payment receipt
}

func (t *PaymentReceipt) GetType() string { return "paymentReceipt" }

// InputInvoice — Describes an invoice to process
type InputInvoice struct {
}

func (t *InputInvoice) GetType() string { return "InputInvoice" }

// InputInvoiceMessage — An invoice from a message of the type messageInvoice or paid media purchase from messagePaidMedia
type InputInvoiceMessage struct {
	ChatID int64 `json:"chat_id"` // Chat identifier of the message
	MessageID int64 `json:"message_id"` // Message identifier. Use messageProperties.can_be_paid to check whether the message can be used in the method
}

func (t *InputInvoiceMessage) GetType() string { return "inputInvoiceMessage" }

// InputInvoiceName — An invoice from a link of the type internalLinkTypeInvoice @name Name of the invoice
type InputInvoiceName struct {
	Name string `json:"name"`
}

func (t *InputInvoiceName) GetType() string { return "inputInvoiceName" }

// InputInvoiceTelegram — An invoice for a payment toward Telegram; must not be used in the in-store apps @purpose Transaction purpose
type InputInvoiceTelegram struct {
	Purpose *TelegramPaymentPurpose `json:"purpose"`
}

func (t *InputInvoiceTelegram) GetType() string { return "inputInvoiceTelegram" }

// PaidMedia — Describes a paid media
type PaidMedia struct {
}

func (t *PaidMedia) GetType() string { return "PaidMedia" }

// PaidMediaPreview — The media is hidden until the invoice is paid
type PaidMediaPreview struct {
	Width int32 `json:"width"` // Media width; 0 if unknown
	Height int32 `json:"height"` // Media height; 0 if unknown
	Duration int32 `json:"duration"` // Media duration, in seconds; 0 if unknown
	Minithumbnail *Minithumbnail `json:"minithumbnail"` // Media minithumbnail; may be null
}

func (t *PaidMediaPreview) GetType() string { return "paidMediaPreview" }

// PaidMediaPhoto — The media is a photo @photo The photo
type PaidMediaPhoto struct {
	Photo *Photo `json:"photo"`
}

func (t *PaidMediaPhoto) GetType() string { return "paidMediaPhoto" }

// PaidMediaVideo — The media is a video
type PaidMediaVideo struct {
	Video *Video `json:"video"` // The video
	Cover *Photo `json:"cover"` // Cover of the video; may be null if none
	StartTimestamp int32 `json:"start_timestamp"` // Timestamp from which the video playing must start, in seconds
}

func (t *PaidMediaVideo) GetType() string { return "paidMediaVideo" }

// PaidMediaUnsupported — The media is unsupported
type PaidMediaUnsupported struct {
}

func (t *PaidMediaUnsupported) GetType() string { return "paidMediaUnsupported" }

// GiveawayParameters — Describes parameters of a giveaway
type GiveawayParameters struct {
	BoostedChatID int64 `json:"boosted_chat_id"` // Identifier of the supergroup or channel chat, which will be automatically boosted by the winners of the giveaway for duration of the Telegram Premium subscription,
	AdditionalChatIDs []int64 `json:"additional_chat_ids"` // Identifiers of other supergroup or channel chats that must be subscribed by the users to be eligible for the giveaway. There can be up to getOption("giveaway_additional_chat_count_max") additional chats
	WinnersSelectionDate int32 `json:"winners_selection_date"` // Point in time (Unix timestamp) when the giveaway is expected to be performed; must be 60-getOption("giveaway_duration_max") seconds in the future in scheduled giveaways
	OnlyNewMembers bool `json:"only_new_members"` // True, if only new members of the chats will be eligible for the giveaway
	HasPublicWinners bool `json:"has_public_winners"` // True, if the list of winners of the giveaway will be available to everyone
	CountryCodes []string `json:"country_codes"` // The list of two-letter ISO 3166-1 alpha-2 codes of countries, users from which will be eligible for the giveaway. If empty, then all users can participate in the giveaway.
	PrizeDescription string `json:"prize_description"` // Additional description of the giveaway prize; 0-128 characters
}

func (t *GiveawayParameters) GetType() string { return "giveawayParameters" }

// DatedFile — File with the date it was uploaded @file The file @date Point in time (Unix timestamp) when the file was uploaded
type DatedFile struct {
	File *File `json:"file"`
	Date int32 `json:"date"`
}

func (t *DatedFile) GetType() string { return "datedFile" }

// PassportElementType — Contains the type of Telegram Passport element
type PassportElementType struct {
}

func (t *PassportElementType) GetType() string { return "PassportElementType" }

// PassportElementTypePersonalDetails — A Telegram Passport element containing the user's personal details
type PassportElementTypePersonalDetails struct {
}

func (t *PassportElementTypePersonalDetails) GetType() string { return "passportElementTypePersonalDetails" }

// PassportElementTypePassport — A Telegram Passport element containing the user's passport
type PassportElementTypePassport struct {
}

func (t *PassportElementTypePassport) GetType() string { return "passportElementTypePassport" }

// PassportElementTypeDriverLicense — A Telegram Passport element containing the user's driver license
type PassportElementTypeDriverLicense struct {
}

func (t *PassportElementTypeDriverLicense) GetType() string { return "passportElementTypeDriverLicense" }

// PassportElementTypeIDentityCard — A Telegram Passport element containing the user's identity card
type PassportElementTypeIDentityCard struct {
}

func (t *PassportElementTypeIDentityCard) GetType() string { return "passportElementTypeIdentityCard" }

// PassportElementTypeInternalPassport — A Telegram Passport element containing the user's internal passport
type PassportElementTypeInternalPassport struct {
}

func (t *PassportElementTypeInternalPassport) GetType() string { return "passportElementTypeInternalPassport" }

// PassportElementTypeAddress — A Telegram Passport element containing the user's address
type PassportElementTypeAddress struct {
}

func (t *PassportElementTypeAddress) GetType() string { return "passportElementTypeAddress" }

// PassportElementTypeUtilityBill — A Telegram Passport element containing the user's utility bill
type PassportElementTypeUtilityBill struct {
}

func (t *PassportElementTypeUtilityBill) GetType() string { return "passportElementTypeUtilityBill" }

// PassportElementTypeBankStatement — A Telegram Passport element containing the user's bank statement
type PassportElementTypeBankStatement struct {
}

func (t *PassportElementTypeBankStatement) GetType() string { return "passportElementTypeBankStatement" }

// PassportElementTypeRentalAgreement — A Telegram Passport element containing the user's rental agreement
type PassportElementTypeRentalAgreement struct {
}

func (t *PassportElementTypeRentalAgreement) GetType() string { return "passportElementTypeRentalAgreement" }

// PassportElementTypePassportRegistration — A Telegram Passport element containing the registration page of the user's passport
type PassportElementTypePassportRegistration struct {
}

func (t *PassportElementTypePassportRegistration) GetType() string { return "passportElementTypePassportRegistration" }

// PassportElementTypeTemporaryRegistration — A Telegram Passport element containing the user's temporary registration
type PassportElementTypeTemporaryRegistration struct {
}

func (t *PassportElementTypeTemporaryRegistration) GetType() string { return "passportElementTypeTemporaryRegistration" }

// PassportElementTypePhoneNumber — A Telegram Passport element containing the user's phone number
type PassportElementTypePhoneNumber struct {
}

func (t *PassportElementTypePhoneNumber) GetType() string { return "passportElementTypePhoneNumber" }

// PassportElementTypeEmailAddress — A Telegram Passport element containing the user's email address
type PassportElementTypeEmailAddress struct {
}

func (t *PassportElementTypeEmailAddress) GetType() string { return "passportElementTypeEmailAddress" }

// Date — Represents a date according to the Gregorian calendar @day Day of the month; 1-31 @month Month; 1-12 @year Year; 1-9999
type Date struct {
	Day int32 `json:"day"`
	Month int32 `json:"month"`
	Year int32 `json:"year"`
}

func (t *Date) GetType() string { return "date" }

// PersonalDetails — Contains the user's personal details
type PersonalDetails struct {
	FirstName string `json:"first_name"` // First name of the user written in English; 1-255 characters
	MiddleName string `json:"middle_name"` // Middle name of the user written in English; 0-255 characters
	LastName string `json:"last_name"` // Last name of the user written in English; 1-255 characters
	NativeFirstName string `json:"native_first_name"` // Native first name of the user; 1-255 characters
	NativeMiddleName string `json:"native_middle_name"` // Native middle name of the user; 0-255 characters
	NativeLastName string `json:"native_last_name"` // Native last name of the user; 1-255 characters
	Birthdate *Date `json:"birthdate"` // Birthdate of the user
	Gender string `json:"gender"` // Gender of the user, "male" or "female"
	CountryCode string `json:"country_code"` // A two-letter ISO 3166-1 alpha-2 country code of the user's country
	ResidenceCountryCode string `json:"residence_country_code"` // A two-letter ISO 3166-1 alpha-2 country code of the user's residence country
}

func (t *PersonalDetails) GetType() string { return "personalDetails" }

// IDentityDocument — An identity document
type IDentityDocument struct {
	Number string `json:"number"` // Document number; 1-24 characters
	ExpirationDate *Date `json:"expiration_date"` // Document expiration date; may be null if not applicable
	FrontSide *DatedFile `json:"front_side"` // Front side of the document
	ReverseSide *DatedFile `json:"reverse_side"` // Reverse side of the document; only for driver license and identity card; may be null
	Selfie *DatedFile `json:"selfie"` // Selfie with the document; may be null
	Translation []*DatedFile `json:"translation"` // List of files containing a certified English translation of the document
}

func (t *IDentityDocument) GetType() string { return "identityDocument" }

// InputIDentityDocument — An identity document to be saved to Telegram Passport
type InputIDentityDocument struct {
	Number string `json:"number"` // Document number; 1-24 characters
	ExpirationDate *Date `json:"expiration_date"` // Document expiration date; pass null if not applicable
	FrontSide *InputFile `json:"front_side"` // Front side of the document
	ReverseSide *InputFile `json:"reverse_side"` // Reverse side of the document; only for driver license and identity card; pass null otherwise
	Selfie *InputFile `json:"selfie"` // Selfie with the document; pass null if unavailable
	Translation []*InputFile `json:"translation"` // List of files containing a certified English translation of the document
}

func (t *InputIDentityDocument) GetType() string { return "inputIdentityDocument" }

// PersonalDocument — A personal document, containing some information about a user @files List of files containing the pages of the document @translation List of files containing a certified English translation of the document
type PersonalDocument struct {
	Files []*DatedFile `json:"files"`
	Translation []*DatedFile `json:"translation"`
}

func (t *PersonalDocument) GetType() string { return "personalDocument" }

// InputPersonalDocument — A personal document to be saved to Telegram Passport @files List of files containing the pages of the document @translation List of files containing a certified English translation of the document
type InputPersonalDocument struct {
	Files []*InputFile `json:"files"`
	Translation []*InputFile `json:"translation"`
}

func (t *InputPersonalDocument) GetType() string { return "inputPersonalDocument" }

// PassportElement — Contains information about a Telegram Passport element
type PassportElement struct {
}

func (t *PassportElement) GetType() string { return "PassportElement" }

// PassportElementPersonalDetails — A Telegram Passport element containing the user's personal details @personal_details Personal details of the user
type PassportElementPersonalDetails struct {
	PersonalDetails *PersonalDetails `json:"personal_details"`
}

func (t *PassportElementPersonalDetails) GetType() string { return "passportElementPersonalDetails" }

// PassportElementPassport — A Telegram Passport element containing the user's passport @passport Passport
type PassportElementPassport struct {
	Passport *IDentityDocument `json:"passport"`
}

func (t *PassportElementPassport) GetType() string { return "passportElementPassport" }

// PassportElementDriverLicense — A Telegram Passport element containing the user's driver license @driver_license Driver license
type PassportElementDriverLicense struct {
	DriverLicense *IDentityDocument `json:"driver_license"`
}

func (t *PassportElementDriverLicense) GetType() string { return "passportElementDriverLicense" }

// PassportElementIDentityCard — A Telegram Passport element containing the user's identity card @identity_card Identity card
type PassportElementIDentityCard struct {
	IDentityCard *IDentityDocument `json:"identity_card"`
}

func (t *PassportElementIDentityCard) GetType() string { return "passportElementIdentityCard" }

// PassportElementInternalPassport — A Telegram Passport element containing the user's internal passport @internal_passport Internal passport
type PassportElementInternalPassport struct {
	InternalPassport *IDentityDocument `json:"internal_passport"`
}

func (t *PassportElementInternalPassport) GetType() string { return "passportElementInternalPassport" }

// PassportElementAddress — A Telegram Passport element containing the user's address @address Address
type PassportElementAddress struct {
	Address *Address `json:"address"`
}

func (t *PassportElementAddress) GetType() string { return "passportElementAddress" }

// PassportElementUtilityBill — A Telegram Passport element containing the user's utility bill @utility_bill Utility bill
type PassportElementUtilityBill struct {
	UtilityBill *PersonalDocument `json:"utility_bill"`
}

func (t *PassportElementUtilityBill) GetType() string { return "passportElementUtilityBill" }

// PassportElementBankStatement — A Telegram Passport element containing the user's bank statement @bank_statement Bank statement
type PassportElementBankStatement struct {
	BankStatement *PersonalDocument `json:"bank_statement"`
}

func (t *PassportElementBankStatement) GetType() string { return "passportElementBankStatement" }

// PassportElementRentalAgreement — A Telegram Passport element containing the user's rental agreement @rental_agreement Rental agreement
type PassportElementRentalAgreement struct {
	RentalAgreement *PersonalDocument `json:"rental_agreement"`
}

func (t *PassportElementRentalAgreement) GetType() string { return "passportElementRentalAgreement" }

// PassportElementPassportRegistration — A Telegram Passport element containing the user's passport registration pages @passport_registration Passport registration pages
type PassportElementPassportRegistration struct {
	PassportRegistration *PersonalDocument `json:"passport_registration"`
}

func (t *PassportElementPassportRegistration) GetType() string { return "passportElementPassportRegistration" }

// PassportElementTemporaryRegistration — A Telegram Passport element containing the user's temporary registration @temporary_registration Temporary registration
type PassportElementTemporaryRegistration struct {
	TemporaryRegistration *PersonalDocument `json:"temporary_registration"`
}

func (t *PassportElementTemporaryRegistration) GetType() string { return "passportElementTemporaryRegistration" }

// PassportElementPhoneNumber — A Telegram Passport element containing the user's phone number @phone_number Phone number
type PassportElementPhoneNumber struct {
	PhoneNumber string `json:"phone_number"`
}

func (t *PassportElementPhoneNumber) GetType() string { return "passportElementPhoneNumber" }

// PassportElementEmailAddress — A Telegram Passport element containing the user's email address @email_address Email address
type PassportElementEmailAddress struct {
	EmailAddress string `json:"email_address"`
}

func (t *PassportElementEmailAddress) GetType() string { return "passportElementEmailAddress" }

// InputPassportElement — Contains information about a Telegram Passport element to be saved
type InputPassportElement struct {
}

func (t *InputPassportElement) GetType() string { return "InputPassportElement" }

// InputPassportElementPersonalDetails — A Telegram Passport element to be saved containing the user's personal details @personal_details Personal details of the user
type InputPassportElementPersonalDetails struct {
	PersonalDetails *PersonalDetails `json:"personal_details"`
}

func (t *InputPassportElementPersonalDetails) GetType() string { return "inputPassportElementPersonalDetails" }

// InputPassportElementPassport — A Telegram Passport element to be saved containing the user's passport @passport The passport to be saved
type InputPassportElementPassport struct {
	Passport *InputIDentityDocument `json:"passport"`
}

func (t *InputPassportElementPassport) GetType() string { return "inputPassportElementPassport" }

// InputPassportElementDriverLicense — A Telegram Passport element to be saved containing the user's driver license @driver_license The driver license to be saved
type InputPassportElementDriverLicense struct {
	DriverLicense *InputIDentityDocument `json:"driver_license"`
}

func (t *InputPassportElementDriverLicense) GetType() string { return "inputPassportElementDriverLicense" }

// InputPassportElementIDentityCard — A Telegram Passport element to be saved containing the user's identity card @identity_card The identity card to be saved
type InputPassportElementIDentityCard struct {
	IDentityCard *InputIDentityDocument `json:"identity_card"`
}

func (t *InputPassportElementIDentityCard) GetType() string { return "inputPassportElementIdentityCard" }

// InputPassportElementInternalPassport — A Telegram Passport element to be saved containing the user's internal passport @internal_passport The internal passport to be saved
type InputPassportElementInternalPassport struct {
	InternalPassport *InputIDentityDocument `json:"internal_passport"`
}

func (t *InputPassportElementInternalPassport) GetType() string { return "inputPassportElementInternalPassport" }

// InputPassportElementAddress — A Telegram Passport element to be saved containing the user's address @address The address to be saved
type InputPassportElementAddress struct {
	Address *Address `json:"address"`
}

func (t *InputPassportElementAddress) GetType() string { return "inputPassportElementAddress" }

// InputPassportElementUtilityBill — A Telegram Passport element to be saved containing the user's utility bill @utility_bill The utility bill to be saved
type InputPassportElementUtilityBill struct {
	UtilityBill *InputPersonalDocument `json:"utility_bill"`
}

func (t *InputPassportElementUtilityBill) GetType() string { return "inputPassportElementUtilityBill" }

// InputPassportElementBankStatement — A Telegram Passport element to be saved containing the user's bank statement @bank_statement The bank statement to be saved
type InputPassportElementBankStatement struct {
	BankStatement *InputPersonalDocument `json:"bank_statement"`
}

func (t *InputPassportElementBankStatement) GetType() string { return "inputPassportElementBankStatement" }

// InputPassportElementRentalAgreement — A Telegram Passport element to be saved containing the user's rental agreement @rental_agreement The rental agreement to be saved
type InputPassportElementRentalAgreement struct {
	RentalAgreement *InputPersonalDocument `json:"rental_agreement"`
}

func (t *InputPassportElementRentalAgreement) GetType() string { return "inputPassportElementRentalAgreement" }

// InputPassportElementPassportRegistration — A Telegram Passport element to be saved containing the user's passport registration @passport_registration The passport registration page to be saved
type InputPassportElementPassportRegistration struct {
	PassportRegistration *InputPersonalDocument `json:"passport_registration"`
}

func (t *InputPassportElementPassportRegistration) GetType() string { return "inputPassportElementPassportRegistration" }

// InputPassportElementTemporaryRegistration — A Telegram Passport element to be saved containing the user's temporary registration @temporary_registration The temporary registration document to be saved
type InputPassportElementTemporaryRegistration struct {
	TemporaryRegistration *InputPersonalDocument `json:"temporary_registration"`
}

func (t *InputPassportElementTemporaryRegistration) GetType() string { return "inputPassportElementTemporaryRegistration" }

// InputPassportElementPhoneNumber — A Telegram Passport element to be saved containing the user's phone number @phone_number The phone number to be saved
type InputPassportElementPhoneNumber struct {
	PhoneNumber string `json:"phone_number"`
}

func (t *InputPassportElementPhoneNumber) GetType() string { return "inputPassportElementPhoneNumber" }

// InputPassportElementEmailAddress — A Telegram Passport element to be saved containing the user's email address @email_address The email address to be saved
type InputPassportElementEmailAddress struct {
	EmailAddress string `json:"email_address"`
}

func (t *InputPassportElementEmailAddress) GetType() string { return "inputPassportElementEmailAddress" }

// PassportElements — Contains information about saved Telegram Passport elements @elements Telegram Passport elements
type PassportElements struct {
	Elements []*PassportElement `json:"elements"`
}

func (t *PassportElements) GetType() string { return "passportElements" }

// PassportElementErrorSource — Contains the description of an error in a Telegram Passport element
type PassportElementErrorSource struct {
}

func (t *PassportElementErrorSource) GetType() string { return "PassportElementErrorSource" }

// PassportElementErrorSourceUnspecified — The element contains an error in an unspecified place. The error will be considered resolved when new data is added
type PassportElementErrorSourceUnspecified struct {
}

func (t *PassportElementErrorSourceUnspecified) GetType() string { return "passportElementErrorSourceUnspecified" }

// PassportElementErrorSourceDataField — One of the data fields contains an error. The error will be considered resolved when the value of the field changes @field_name Field name
type PassportElementErrorSourceDataField struct {
	FieldName string `json:"field_name"`
}

func (t *PassportElementErrorSourceDataField) GetType() string { return "passportElementErrorSourceDataField" }

// PassportElementErrorSourceFrontSide — The front side of the document contains an error. The error will be considered resolved when the file with the front side changes
type PassportElementErrorSourceFrontSide struct {
}

func (t *PassportElementErrorSourceFrontSide) GetType() string { return "passportElementErrorSourceFrontSide" }

// PassportElementErrorSourceReverseSide — The reverse side of the document contains an error. The error will be considered resolved when the file with the reverse side changes
type PassportElementErrorSourceReverseSide struct {
}

func (t *PassportElementErrorSourceReverseSide) GetType() string { return "passportElementErrorSourceReverseSide" }

// PassportElementErrorSourceSelfie — The selfie with the document contains an error. The error will be considered resolved when the file with the selfie changes
type PassportElementErrorSourceSelfie struct {
}

func (t *PassportElementErrorSourceSelfie) GetType() string { return "passportElementErrorSourceSelfie" }

// PassportElementErrorSourceTranslationFile — One of files with the translation of the document contains an error. The error will be considered resolved when the file changes @file_index Index of a file with the error
type PassportElementErrorSourceTranslationFile struct {
	FileIndex int32 `json:"file_index"`
}

func (t *PassportElementErrorSourceTranslationFile) GetType() string { return "passportElementErrorSourceTranslationFile" }

// PassportElementErrorSourceTranslationFiles — The translation of the document contains an error. The error will be considered resolved when the list of translation files changes
type PassportElementErrorSourceTranslationFiles struct {
}

func (t *PassportElementErrorSourceTranslationFiles) GetType() string { return "passportElementErrorSourceTranslationFiles" }

// PassportElementErrorSourceFile — The file contains an error. The error will be considered resolved when the file changes @file_index Index of a file with the error
type PassportElementErrorSourceFile struct {
	FileIndex int32 `json:"file_index"`
}

func (t *PassportElementErrorSourceFile) GetType() string { return "passportElementErrorSourceFile" }

// PassportElementErrorSourceFiles — The list of attached files contains an error. The error will be considered resolved when the list of files changes
type PassportElementErrorSourceFiles struct {
}

func (t *PassportElementErrorSourceFiles) GetType() string { return "passportElementErrorSourceFiles" }

// PassportElementError — Contains the description of an error in a Telegram Passport element @type Type of the Telegram Passport element which has the error @message Error message @source Error source
type PassportElementError struct {
	Type *PassportElementType `json:"type"`
	Message string `json:"message"`
	Source *PassportElementErrorSource `json:"source"`
}

func (t *PassportElementError) GetType() string { return "passportElementError" }

// PassportSuitableElement — Contains information about a Telegram Passport element that was requested by a service
type PassportSuitableElement struct {
	Type *PassportElementType `json:"type"` // Type of the element
	IsSelfieRequired bool `json:"is_selfie_required"` // True, if a selfie is required with the identity document
	IsTranslationRequired bool `json:"is_translation_required"` // True, if a certified English translation is required with the document
	IsNativeNameRequired bool `json:"is_native_name_required"` // True, if personal details must include the user's name in the language of their country of residence
}

func (t *PassportSuitableElement) GetType() string { return "passportSuitableElement" }

// PassportRequiredElement — Contains a description of the required Telegram Passport element that was requested by a service @suitable_elements List of Telegram Passport elements any of which is enough to provide
type PassportRequiredElement struct {
	SuitableElements []*PassportSuitableElement `json:"suitable_elements"`
}

func (t *PassportRequiredElement) GetType() string { return "passportRequiredElement" }

// PassportAuthorizationForm — Contains information about a Telegram Passport authorization form that was requested
type PassportAuthorizationForm struct {
	ID int32 `json:"id"` // Unique identifier of the authorization form
	RequiredElements []*PassportRequiredElement `json:"required_elements"` // Telegram Passport elements that must be provided to complete the form
	PrivacyPolicyURL string `json:"privacy_policy_url"` // URL for the privacy policy of the service; may be empty
}

func (t *PassportAuthorizationForm) GetType() string { return "passportAuthorizationForm" }

// PassportElementsWithErrors — Contains information about a Telegram Passport elements and corresponding errors @elements Telegram Passport elements @errors Errors in the elements that are already available
type PassportElementsWithErrors struct {
	Elements []*PassportElement `json:"elements"`
	Errors []*PassportElementError `json:"errors"`
}

func (t *PassportElementsWithErrors) GetType() string { return "passportElementsWithErrors" }

// EncryptedCredentials — Contains encrypted Telegram Passport data credentials @data The encrypted credentials @hash The decrypted data hash @secret Secret for data decryption, encrypted with the service's public key
type EncryptedCredentials struct {
	Data []byte `json:"data"`
	Hash []byte `json:"hash"`
	Secret []byte `json:"secret"`
}

func (t *EncryptedCredentials) GetType() string { return "encryptedCredentials" }

// EncryptedPassportElement — Contains information about an encrypted Telegram Passport element; for bots only
type EncryptedPassportElement struct {
	Type *PassportElementType `json:"type"` // Type of Telegram Passport element
	Data []byte `json:"data"` // Encrypted JSON-encoded data about the user
	FrontSide *DatedFile `json:"front_side"` // The front side of an identity document
	ReverseSide *DatedFile `json:"reverse_side"` // The reverse side of an identity document; may be null
	Selfie *DatedFile `json:"selfie"` // Selfie with the document; may be null
	Translation []*DatedFile `json:"translation"` // List of files containing a certified English translation of the document
	Files []*DatedFile `json:"files"` // List of attached files
	Value string `json:"value"` // Unencrypted data, phone number or email address
	Hash string `json:"hash"` // Hash of the entire element
}

func (t *EncryptedPassportElement) GetType() string { return "encryptedPassportElement" }

// InputPassportElementErrorSource — Contains the description of an error in a Telegram Passport element; for bots only
type InputPassportElementErrorSource struct {
}

func (t *InputPassportElementErrorSource) GetType() string { return "InputPassportElementErrorSource" }

// InputPassportElementErrorSourceUnspecified — The element contains an error in an unspecified place. The error will be considered resolved when new data is added @element_hash Current hash of the entire element
type InputPassportElementErrorSourceUnspecified struct {
	ElementHash []byte `json:"element_hash"`
}

func (t *InputPassportElementErrorSourceUnspecified) GetType() string { return "inputPassportElementErrorSourceUnspecified" }

// InputPassportElementErrorSourceDataField — A data field contains an error. The error is considered resolved when the field's value changes @field_name Field name @data_hash Current data hash
type InputPassportElementErrorSourceDataField struct {
	FieldName string `json:"field_name"`
	DataHash []byte `json:"data_hash"`
}

func (t *InputPassportElementErrorSourceDataField) GetType() string { return "inputPassportElementErrorSourceDataField" }

// InputPassportElementErrorSourceFrontSide — The front side of the document contains an error. The error is considered resolved when the file with the front side of the document changes @file_hash Current hash of the file containing the front side
type InputPassportElementErrorSourceFrontSide struct {
	FileHash []byte `json:"file_hash"`
}

func (t *InputPassportElementErrorSourceFrontSide) GetType() string { return "inputPassportElementErrorSourceFrontSide" }

// InputPassportElementErrorSourceReverseSide — The reverse side of the document contains an error. The error is considered resolved when the file with the reverse side of the document changes @file_hash Current hash of the file containing the reverse side
type InputPassportElementErrorSourceReverseSide struct {
	FileHash []byte `json:"file_hash"`
}

func (t *InputPassportElementErrorSourceReverseSide) GetType() string { return "inputPassportElementErrorSourceReverseSide" }

// InputPassportElementErrorSourceSelfie — The selfie contains an error. The error is considered resolved when the file with the selfie changes @file_hash Current hash of the file containing the selfie
type InputPassportElementErrorSourceSelfie struct {
	FileHash []byte `json:"file_hash"`
}

func (t *InputPassportElementErrorSourceSelfie) GetType() string { return "inputPassportElementErrorSourceSelfie" }

// InputPassportElementErrorSourceTranslationFile — One of the files containing the translation of the document contains an error. The error is considered resolved when the file with the translation changes @file_hash Current hash of the file containing the translation
type InputPassportElementErrorSourceTranslationFile struct {
	FileHash []byte `json:"file_hash"`
}

func (t *InputPassportElementErrorSourceTranslationFile) GetType() string { return "inputPassportElementErrorSourceTranslationFile" }

// InputPassportElementErrorSourceTranslationFiles — The translation of the document contains an error. The error is considered resolved when the list of files changes @file_hashes Current hashes of all files with the translation
type InputPassportElementErrorSourceTranslationFiles struct {
	FileHashes [][]byte `json:"file_hashes"`
}

func (t *InputPassportElementErrorSourceTranslationFiles) GetType() string { return "inputPassportElementErrorSourceTranslationFiles" }

// InputPassportElementErrorSourceFile — The file contains an error. The error is considered resolved when the file changes @file_hash Current hash of the file which has the error
type InputPassportElementErrorSourceFile struct {
	FileHash []byte `json:"file_hash"`
}

func (t *InputPassportElementErrorSourceFile) GetType() string { return "inputPassportElementErrorSourceFile" }

// InputPassportElementErrorSourceFiles — The list of attached files contains an error. The error is considered resolved when the file list changes @file_hashes Current hashes of all attached files
type InputPassportElementErrorSourceFiles struct {
	FileHashes [][]byte `json:"file_hashes"`
}

func (t *InputPassportElementErrorSourceFiles) GetType() string { return "inputPassportElementErrorSourceFiles" }

// InputPassportElementError — Contains the description of an error in a Telegram Passport element; for bots only @type Type of Telegram Passport element that has the error @message Error message @source Error source
type InputPassportElementError struct {
	Type *PassportElementType `json:"type"`
	Message string `json:"message"`
	Source *InputPassportElementErrorSource `json:"source"`
}

func (t *InputPassportElementError) GetType() string { return "inputPassportElementError" }

// MessageContent — Contains the content of a message
type MessageContent struct {
}

func (t *MessageContent) GetType() string { return "MessageContent" }

// MessageText — A text message
type MessageText struct {
	Text *FormattedText `json:"text"` // Text of the message
	LinkPreview *LinkPreview `json:"link_preview"` // A link preview attached to the message; may be null
	LinkPreviewOptions *LinkPreviewOptions `json:"link_preview_options"` // Options which were used for generation of the link preview; may be null if default options were used
}

func (t *MessageText) GetType() string { return "messageText" }

// MessageAnimation — An animation message (GIF-style).
type MessageAnimation struct {
	Animation *Animation `json:"animation"` // The animation description
	Caption *FormattedText `json:"caption"` // Animation caption
	ShowCaptionAboveMedia bool `json:"show_caption_above_media"` // True, if the caption must be shown above the animation; otherwise, the caption must be shown below the animation
	HasSpoiler bool `json:"has_spoiler"` // True, if the animation preview must be covered by a spoiler animation
	IsSecret bool `json:"is_secret"` // True, if the animation thumbnail must be blurred and the animation must be shown only while tapped
}

func (t *MessageAnimation) GetType() string { return "messageAnimation" }

// MessageAudio — An audio message @audio The audio description @caption Audio caption
type MessageAudio struct {
	Audio *Audio `json:"audio"`
	Caption *FormattedText `json:"caption"`
}

func (t *MessageAudio) GetType() string { return "messageAudio" }

// MessageDocument — A document message (general file) @document The document description @caption Document caption
type MessageDocument struct {
	Document *Document `json:"document"`
	Caption *FormattedText `json:"caption"`
}

func (t *MessageDocument) GetType() string { return "messageDocument" }

// MessagePaidMedia — A message with paid media
type MessagePaidMedia struct {
	StarCount int64 `json:"star_count"` // Number of Telegram Stars needed to buy access to the media in the message
	Media []*PaidMedia `json:"media"` // Information about the media
	Caption *FormattedText `json:"caption"` // Media caption
	ShowCaptionAboveMedia bool `json:"show_caption_above_media"` // True, if the caption must be shown above the media; otherwise, the caption must be shown below the media
}

func (t *MessagePaidMedia) GetType() string { return "messagePaidMedia" }

// MessagePhoto — A photo message
type MessagePhoto struct {
	Photo *Photo `json:"photo"` // The photo
	Caption *FormattedText `json:"caption"` // Photo caption
	ShowCaptionAboveMedia bool `json:"show_caption_above_media"` // True, if the caption must be shown above the photo; otherwise, the caption must be shown below the photo
	HasSpoiler bool `json:"has_spoiler"` // True, if the photo preview must be covered by a spoiler animation
	IsSecret bool `json:"is_secret"` // True, if the photo must be blurred and must be shown only while tapped
}

func (t *MessagePhoto) GetType() string { return "messagePhoto" }

// MessageSticker — A sticker message @sticker The sticker description @is_premium True, if premium animation of the sticker must be played
type MessageSticker struct {
	Sticker *Sticker `json:"sticker"`
	IsPremium bool `json:"is_premium"`
}

func (t *MessageSticker) GetType() string { return "messageSticker" }

// MessageVideo — A video message
type MessageVideo struct {
	Video *Video `json:"video"` // The video description
	AlternativeVideos []*AlternativeVideo `json:"alternative_videos"` // Alternative qualities of the video
	Storyboards []*VideoStoryboard `json:"storyboards"` // Available storyboards for the video
	Cover *Photo `json:"cover"` // Cover of the video; may be null if none
	StartTimestamp int32 `json:"start_timestamp"` // Timestamp from which the video playing must start, in seconds
	Caption *FormattedText `json:"caption"` // Video caption
	ShowCaptionAboveMedia bool `json:"show_caption_above_media"` // True, if the caption must be shown above the video; otherwise, the caption must be shown below the video
	HasSpoiler bool `json:"has_spoiler"` // True, if the video preview must be covered by a spoiler animation
	IsSecret bool `json:"is_secret"` // True, if the video thumbnail must be blurred and the video must be shown only while tapped
}

func (t *MessageVideo) GetType() string { return "messageVideo" }

// MessageVideoNote — A video note message @video_note The video note description @is_viewed True, if at least one of the recipients has viewed the video note @is_secret True, if the video note thumbnail must be blurred and the video note must be shown only while tapped
type MessageVideoNote struct {
	VideoNote *VideoNote `json:"video_note"`
	IsViewed bool `json:"is_viewed"`
	IsSecret bool `json:"is_secret"`
}

func (t *MessageVideoNote) GetType() string { return "messageVideoNote" }

// MessageVoiceNote — A voice note message @voice_note The voice note description @caption Voice note caption @is_listened True, if at least one of the recipients has listened to the voice note
type MessageVoiceNote struct {
	VoiceNote *VoiceNote `json:"voice_note"`
	Caption *FormattedText `json:"caption"`
	IsListened bool `json:"is_listened"`
}

func (t *MessageVoiceNote) GetType() string { return "messageVoiceNote" }

// MessageExpiredPhoto — A self-destructed photo message
type MessageExpiredPhoto struct {
}

func (t *MessageExpiredPhoto) GetType() string { return "messageExpiredPhoto" }

// MessageExpiredVideo — A self-destructed video message
type MessageExpiredVideo struct {
}

func (t *MessageExpiredVideo) GetType() string { return "messageExpiredVideo" }

// MessageExpiredVideoNote — A self-destructed video note message
type MessageExpiredVideoNote struct {
}

func (t *MessageExpiredVideoNote) GetType() string { return "messageExpiredVideoNote" }

// MessageExpiredVoiceNote — A self-destructed voice note message
type MessageExpiredVoiceNote struct {
}

func (t *MessageExpiredVoiceNote) GetType() string { return "messageExpiredVoiceNote" }

// MessageLocation — A message with a location
type MessageLocation struct {
	Location *Location `json:"location"` // The location description
	LivePeriod int32 `json:"live_period"` // Time relative to the message send date, for which the location can be updated, in seconds; if 0x7FFFFFFF, then location can be updated forever
	ExpiresIn int32 `json:"expires_in"` // Left time for which the location can be updated, in seconds. If 0, then the location can't be updated anymore. The update updateMessageContent is not sent when this field changes
	Heading int32 `json:"heading"` // For live locations, a direction in which the location moves, in degrees; 1-360. If 0 the direction is unknown
	ProximityAlertRadius int32 `json:"proximity_alert_radius"` // For live locations, a maximum distance to another chat member for proximity alerts, in meters (0-100000). 0 if the notification is disabled. Available only to the message sender
}

func (t *MessageLocation) GetType() string { return "messageLocation" }

// MessageVenue — A message with information about a venue @venue The venue description
type MessageVenue struct {
	Venue *Venue `json:"venue"`
}

func (t *MessageVenue) GetType() string { return "messageVenue" }

// MessageContact — A message with a user contact @contact The contact description
type MessageContact struct {
	Contact *Contact `json:"contact"`
}

func (t *MessageContact) GetType() string { return "messageContact" }

// MessageAnimatedEmoji — A message with an animated emoji @animated_emoji The animated emoji @emoji The corresponding emoji
type MessageAnimatedEmoji struct {
	AnimatedEmoji *AnimatedEmoji `json:"animated_emoji"`
	Emoji string `json:"emoji"`
}

func (t *MessageAnimatedEmoji) GetType() string { return "messageAnimatedEmoji" }

// MessageDice — A dice message. The dice value is randomly generated by the server
type MessageDice struct {
	InitialState *DiceStickers `json:"initial_state"` // The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
	FinalState *DiceStickers `json:"final_state"` // The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
	Emoji string `json:"emoji"` // Emoji on which the dice throw animation is based
	Value int32 `json:"value"` // The dice value. If the value is 0, then the dice don't have final state yet
	SuccessAnimationFrameNumber int32 `json:"success_animation_frame_number"` // Number of frame after which a success animation like a shower of confetti needs to be shown on updateMessageSendSucceeded
}

func (t *MessageDice) GetType() string { return "messageDice" }

// MessageGame — A message with a game @game The game description
type MessageGame struct {
	Game *Game `json:"game"`
}

func (t *MessageGame) GetType() string { return "messageGame" }

// MessagePoll — A message with a poll @poll The poll description
type MessagePoll struct {
	Poll *Poll `json:"poll"`
}

func (t *MessagePoll) GetType() string { return "messagePoll" }

// MessageStakeDice — A stake dice message. The dice value is randomly generated by the server
type MessageStakeDice struct {
	InitialState *DiceStickers `json:"initial_state"` // The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
	FinalState *DiceStickers `json:"final_state"` // The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known
	Value int32 `json:"value"` // The dice value. If the value is 0, then the dice don't have final state yet
	StakeToncoinAmount int64 `json:"stake_toncoin_amount"` // The Toncoin amount that was staked; in the smallest units of the currency
	PrizeToncoinAmount int64 `json:"prize_toncoin_amount"` // The Toncoin amount that was gained from the roll; in the smallest units of the currency; -1 if the dice don't have final state yet
}

func (t *MessageStakeDice) GetType() string { return "messageStakeDice" }

// MessageStory — A message with a forwarded story
type MessageStory struct {
	StoryPosterChatID int64 `json:"story_poster_chat_id"` // Identifier of the chat that posted the story
	StoryID int32 `json:"story_id"` // Story identifier
	ViaMention bool `json:"via_mention"` // True, if the story was automatically forwarded because of a mention of the user
}

func (t *MessageStory) GetType() string { return "messageStory" }

// MessageChecklist — A message with a checklist @list The checklist description
type MessageChecklist struct {
	List *Checklist `json:"list"`
}

func (t *MessageChecklist) GetType() string { return "messageChecklist" }

// MessageInvoice — A message with an invoice from a bot. Use getInternalLink with internalLinkTypeBotStart to share the invoice
type MessageInvoice struct {
	ProductInfo *ProductInfo `json:"product_info"` // Information about the product
	Currency string `json:"currency"` // Currency for the product price
	TotalAmount int64 `json:"total_amount"` // Product total price in the smallest units of the currency
	StartParameter string `json:"start_parameter"` // Unique invoice bot start_parameter to be passed to getInternalLink
	IsTest bool `json:"is_test"` // True, if the invoice is a test invoice
	NeedShippingAddress bool `json:"need_shipping_address"` // True, if the shipping address must be specified
	ReceiptMessageID int64 `json:"receipt_message_id"` // The identifier of the message with the receipt, after the product has been purchased
	PaidMedia *PaidMedia `json:"paid_media"` // Extended media attached to the invoice; may be null if none
	PaidMediaCaption *FormattedText `json:"paid_media_caption"` // Extended media caption; may be null if none
}

func (t *MessageInvoice) GetType() string { return "messageInvoice" }

// MessageCall — A message with information about an ended call
type MessageCall struct {
	UniqueID JSONInt64 `json:"unique_id"` // Persistent unique call identifier; 0 for calls from other devices, which can't be passed as inputCallFromMessage
	IsVideo bool `json:"is_video"` // True, if the call was a video call
	DiscardReason *CallDiscardReason `json:"discard_reason"` // Reason why the call was discarded
	Duration int32 `json:"duration"` // Call duration, in seconds
}

func (t *MessageCall) GetType() string { return "messageCall" }

// MessageGroupCall — A message with information about a group call not bound to a chat. If the message is incoming, the call isn't active, isn't missed, and has no duration,
type MessageGroupCall struct {
	UniqueID JSONInt64 `json:"unique_id"` // Persistent unique group call identifier
	IsActive bool `json:"is_active"` // True, if the call is active, i.e. the called user joined the call
	WasMissed bool `json:"was_missed"` // True, if the called user missed or declined the call
	IsVideo bool `json:"is_video"` // True, if the call is a video call
	Duration int32 `json:"duration"` // Call duration, in seconds; for left calls only
	OtherParticipantIDs []*MessageSender `json:"other_participant_ids"` // Identifiers of some other call participants
}

func (t *MessageGroupCall) GetType() string { return "messageGroupCall" }

// MessageVideoChatScheduled — A new video chat was scheduled @group_call_id Identifier of the video chat. The video chat can be received through the method getGroupCall @start_date Point in time (Unix timestamp) when the group call is expected to be started by an administrator
type MessageVideoChatScheduled struct {
	GroupCallID int32 `json:"group_call_id"`
	StartDate int32 `json:"start_date"`
}

func (t *MessageVideoChatScheduled) GetType() string { return "messageVideoChatScheduled" }

// MessageVideoChatStarted — A newly created video chat @group_call_id Identifier of the video chat. The video chat can be received through the method getGroupCall
type MessageVideoChatStarted struct {
	GroupCallID int32 `json:"group_call_id"`
}

func (t *MessageVideoChatStarted) GetType() string { return "messageVideoChatStarted" }

// MessageVideoChatEnded — A message with information about an ended video chat @duration Call duration, in seconds
type MessageVideoChatEnded struct {
	Duration int32 `json:"duration"`
}

func (t *MessageVideoChatEnded) GetType() string { return "messageVideoChatEnded" }

// MessageInviteVideoChatParticipants — A message with information about an invitation to a video chat @group_call_id Identifier of the video chat. The video chat can be received through the method getGroupCall @user_ids Invited user identifiers
type MessageInviteVideoChatParticipants struct {
	GroupCallID int32 `json:"group_call_id"`
	UserIDs []int64 `json:"user_ids"`
}

func (t *MessageInviteVideoChatParticipants) GetType() string { return "messageInviteVideoChatParticipants" }

// MessageBasicGroupChatCreate — A newly created basic group @title Title of the basic group @member_user_ids User identifiers of members in the basic group
type MessageBasicGroupChatCreate struct {
	Title string `json:"title"`
	MemberUserIDs []int64 `json:"member_user_ids"`
}

func (t *MessageBasicGroupChatCreate) GetType() string { return "messageBasicGroupChatCreate" }

// MessageSupergroupChatCreate — A newly created supergroup or channel @title Title of the supergroup or channel
type MessageSupergroupChatCreate struct {
	Title string `json:"title"`
}

func (t *MessageSupergroupChatCreate) GetType() string { return "messageSupergroupChatCreate" }

// MessageChatChangeTitle — An updated chat title @title New chat title
type MessageChatChangeTitle struct {
	Title string `json:"title"`
}

func (t *MessageChatChangeTitle) GetType() string { return "messageChatChangeTitle" }

// MessageChatChangePhoto — An updated chat photo @photo New chat photo
type MessageChatChangePhoto struct {
	Photo *ChatPhoto `json:"photo"`
}

func (t *MessageChatChangePhoto) GetType() string { return "messageChatChangePhoto" }

// MessageChatDeletePhoto — A deleted chat photo
type MessageChatDeletePhoto struct {
}

func (t *MessageChatDeletePhoto) GetType() string { return "messageChatDeletePhoto" }

// MessageChatOwnerLeft — The owner of the chat has left @new_owner_user_id Identifier of the user who will become the new owner of the chat if the previous owner isn't return; 0 if none
type MessageChatOwnerLeft struct {
	NewOwnerUserID int64 `json:"new_owner_user_id"`
}

func (t *MessageChatOwnerLeft) GetType() string { return "messageChatOwnerLeft" }

// MessageChatOwnerChanged — The owner of the chat has changed @new_owner_user_id Identifier of the user who is the new owner of the chat
type MessageChatOwnerChanged struct {
	NewOwnerUserID int64 `json:"new_owner_user_id"`
}

func (t *MessageChatOwnerChanged) GetType() string { return "messageChatOwnerChanged" }

// MessageChatHasProtectedContentToggled — Chat has_protected_content setting was changed or request to change it was rejected
type MessageChatHasProtectedContentToggled struct {
	RequestMessageID int64 `json:"request_message_id"` // Identifier of the message with the request to change the setting; can be an identifier of a deleted message or 0
	OldHasProtectedContent bool `json:"old_has_protected_content"` // Previous value of the setting
	NewHasProtectedContent bool `json:"new_has_protected_content"` // New value of the setting
}

func (t *MessageChatHasProtectedContentToggled) GetType() string { return "messageChatHasProtectedContentToggled" }

// MessageChatHasProtectedContentDisableRequested — Chat has_protected_content setting was requested to be disabled @is_expired True, if the request has expired
type MessageChatHasProtectedContentDisableRequested struct {
	IsExpired bool `json:"is_expired"`
}

func (t *MessageChatHasProtectedContentDisableRequested) GetType() string { return "messageChatHasProtectedContentDisableRequested" }

// MessageChatAddMembers — New chat members were added @member_user_ids User identifiers of the new members
type MessageChatAddMembers struct {
	MemberUserIDs []int64 `json:"member_user_ids"`
}

func (t *MessageChatAddMembers) GetType() string { return "messageChatAddMembers" }

// MessageChatJoinByLink — A new member joined the chat via an invite link
type MessageChatJoinByLink struct {
}

func (t *MessageChatJoinByLink) GetType() string { return "messageChatJoinByLink" }

// MessageChatJoinByRequest — A new member was accepted to the chat by an administrator
type MessageChatJoinByRequest struct {
}

func (t *MessageChatJoinByRequest) GetType() string { return "messageChatJoinByRequest" }

// MessageChatDeleteMember — A chat member was deleted @user_id User identifier of the deleted chat member
type MessageChatDeleteMember struct {
	UserID int64 `json:"user_id"`
}

func (t *MessageChatDeleteMember) GetType() string { return "messageChatDeleteMember" }

// MessageChatUpgradeTo — A basic group was upgraded to a supergroup and was deactivated as the result @supergroup_id Identifier of the supergroup to which the basic group was upgraded
type MessageChatUpgradeTo struct {
	SupergroupID int64 `json:"supergroup_id"`
}

func (t *MessageChatUpgradeTo) GetType() string { return "messageChatUpgradeTo" }

// MessageChatUpgradeFrom — A supergroup has been created from a basic group @title Title of the newly created supergroup @basic_group_id The identifier of the original basic group
type MessageChatUpgradeFrom struct {
	Title string `json:"title"`
	BasicGroupID int64 `json:"basic_group_id"`
}

func (t *MessageChatUpgradeFrom) GetType() string { return "messageChatUpgradeFrom" }

// MessagePinMessage — A message has been pinned @message_id Identifier of the pinned message, can be an identifier of a deleted message or 0
type MessagePinMessage struct {
	MessageID int64 `json:"message_id"`
}

func (t *MessagePinMessage) GetType() string { return "messagePinMessage" }

// MessageScreenshotTaken — A screenshot of a message in the chat has been taken
type MessageScreenshotTaken struct {
}

func (t *MessageScreenshotTaken) GetType() string { return "messageScreenshotTaken" }

// MessageChatSetBackground — A new background was set in the chat
type MessageChatSetBackground struct {
	OldBackgroundMessageID int64 `json:"old_background_message_id"` // Identifier of the message with a previously set same background; 0 if none. Can be an identifier of a deleted message
	Background *ChatBackground `json:"background"` // The new background
	OnlyForSelf bool `json:"only_for_self"` // True, if the background was set only for self
}

func (t *MessageChatSetBackground) GetType() string { return "messageChatSetBackground" }

// MessageChatSetTheme — A theme in the chat has been changed @theme New theme for the chat; may be null if chat theme was reset to the default one
type MessageChatSetTheme struct {
	Theme *ChatTheme `json:"theme"`
}

func (t *MessageChatSetTheme) GetType() string { return "messageChatSetTheme" }

// MessageChatSetMessageAutoDeleteTime — The auto-delete or self-destruct timer for messages in the chat has been changed @message_auto_delete_time New value auto-delete or self-destruct time, in seconds; 0 if disabled @from_user_id If not 0, a user identifier, which default setting was automatically applied
type MessageChatSetMessageAutoDeleteTime struct {
	MessageAutoDeleteTime int32 `json:"message_auto_delete_time"`
	FromUserID int64 `json:"from_user_id"`
}

func (t *MessageChatSetMessageAutoDeleteTime) GetType() string { return "messageChatSetMessageAutoDeleteTime" }

// MessageChatBoost — The chat was boosted by the sender of the message @boost_count Number of times the chat was boosted
type MessageChatBoost struct {
	BoostCount int32 `json:"boost_count"`
}

func (t *MessageChatBoost) GetType() string { return "messageChatBoost" }

// MessageForumTopicCreated — A forum topic has been created
type MessageForumTopicCreated struct {
	Name string `json:"name"` // Name of the topic
	IsNameImplicit bool `json:"is_name_implicit"` // True, if the name of the topic wasn't added explicitly
	Icon *ForumTopicIcon `json:"icon"` // Icon of the topic
}

func (t *MessageForumTopicCreated) GetType() string { return "messageForumTopicCreated" }

// MessageForumTopicEdited — A forum topic has been edited
type MessageForumTopicEdited struct {
	Name string `json:"name"` // If non-empty, the new name of the topic
	EditIconCustomEmojiID bool `json:"edit_icon_custom_emoji_id"` // True, if icon's custom_emoji_id is changed
	IconCustomEmojiID JSONInt64 `json:"icon_custom_emoji_id"` // New unique identifier of the custom emoji shown on the topic icon; 0 if none. Must be ignored if edit_icon_custom_emoji_id is false
}

func (t *MessageForumTopicEdited) GetType() string { return "messageForumTopicEdited" }

// MessageForumTopicIsClosedToggled — A forum topic has been closed or opened @is_closed True, if the topic was closed; otherwise, the topic was reopened
type MessageForumTopicIsClosedToggled struct {
	IsClosed bool `json:"is_closed"`
}

func (t *MessageForumTopicIsClosedToggled) GetType() string { return "messageForumTopicIsClosedToggled" }

// MessageForumTopicIsHiddenToggled — A General forum topic has been hidden or unhidden @is_hidden True, if the topic was hidden; otherwise, the topic was unhidden
type MessageForumTopicIsHiddenToggled struct {
	IsHidden bool `json:"is_hidden"`
}

func (t *MessageForumTopicIsHiddenToggled) GetType() string { return "messageForumTopicIsHiddenToggled" }

// MessageSuggestProfilePhoto — A profile photo was suggested to a user in a private chat @photo The suggested chat photo. Use the method setProfilePhoto with inputChatPhotoPrevious to apply the photo
type MessageSuggestProfilePhoto struct {
	Photo *ChatPhoto `json:"photo"`
}

func (t *MessageSuggestProfilePhoto) GetType() string { return "messageSuggestProfilePhoto" }

// MessageSuggestBirthdate — A birthdate was suggested to be set @birthdate The suggested birthdate. Use the method setBirthdate to apply the birthdate
type MessageSuggestBirthdate struct {
	Birthdate *Birthdate `json:"birthdate"`
}

func (t *MessageSuggestBirthdate) GetType() string { return "messageSuggestBirthdate" }

// MessageCustomServiceAction — A non-standard action has happened in the chat @text Message text to be shown in the chat
type MessageCustomServiceAction struct {
	Text string `json:"text"`
}

func (t *MessageCustomServiceAction) GetType() string { return "messageCustomServiceAction" }

// MessageGameScore — A new high score was achieved in a game @game_message_id Identifier of the message with the game, can be an identifier of a deleted message @game_id Identifier of the game; may be different from the games presented in the message with the game @score New score
type MessageGameScore struct {
	GameMessageID int64 `json:"game_message_id"`
	GameID JSONInt64 `json:"game_id"`
	Score int32 `json:"score"`
}

func (t *MessageGameScore) GetType() string { return "messageGameScore" }

// MessagePaymentSuccessful — A payment has been sent to a bot or a business account
type MessagePaymentSuccessful struct {
	InvoiceChatID int64 `json:"invoice_chat_id"` // Identifier of the chat, containing the corresponding invoice message
	InvoiceMessageID int64 `json:"invoice_message_id"` // Identifier of the message with the corresponding invoice; may be 0 or an identifier of a deleted message
	Currency string `json:"currency"` // Currency for the price of the product
	TotalAmount int64 `json:"total_amount"` // Total price for the product, in the smallest units of the currency
	SubscriptionUntilDate int32 `json:"subscription_until_date"` // Point in time (Unix timestamp) when the subscription will expire; 0 if unknown or the payment isn't recurring
	IsRecurring bool `json:"is_recurring"` // True, if this is a recurring payment
	IsFirstRecurring bool `json:"is_first_recurring"` // True, if this is the first recurring payment
	InvoiceName string `json:"invoice_name"` // Name of the invoice; may be empty if unknown
}

func (t *MessagePaymentSuccessful) GetType() string { return "messagePaymentSuccessful" }

// MessagePaymentSuccessfulBot — A payment has been received by the bot or the business account
type MessagePaymentSuccessfulBot struct {
	Currency string `json:"currency"` // Currency for price of the product
	TotalAmount int64 `json:"total_amount"` // Total price for the product, in the smallest units of the currency
	SubscriptionUntilDate int32 `json:"subscription_until_date"` // Point in time (Unix timestamp) when the subscription will expire; 0 if unknown or the payment isn't recurring
	IsRecurring bool `json:"is_recurring"` // True, if this is a recurring payment
	IsFirstRecurring bool `json:"is_first_recurring"` // True, if this is the first recurring payment
	InvoicePayload []byte `json:"invoice_payload"` // Invoice payload
	ShippingOptionID string `json:"shipping_option_id"` // Identifier of the shipping option chosen by the user; may be empty if not applicable; for bots only
	OrderInfo *OrderInfo `json:"order_info"` // Information about the order; may be null; for bots only
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"` // Telegram payment identifier
	ProviderPaymentChargeID string `json:"provider_payment_charge_id"` // Provider payment identifier
}

func (t *MessagePaymentSuccessfulBot) GetType() string { return "messagePaymentSuccessfulBot" }

// MessagePaymentRefunded — A payment has been refunded
type MessagePaymentRefunded struct {
	OwnerID *MessageSender `json:"owner_id"` // Identifier of the previous owner of the Telegram Stars that refunds them
	Currency string `json:"currency"` // Currency for the price of the product
	TotalAmount int64 `json:"total_amount"` // Total price for the product, in the smallest units of the currency
	InvoicePayload []byte `json:"invoice_payload"` // Invoice payload; only for bots
	TelegramPaymentChargeID string `json:"telegram_payment_charge_id"` // Telegram payment identifier
	ProviderPaymentChargeID string `json:"provider_payment_charge_id"` // Provider payment identifier
}

func (t *MessagePaymentRefunded) GetType() string { return "messagePaymentRefunded" }

// MessageGiftedPremium — Telegram Premium was gifted to a user
type MessageGiftedPremium struct {
	GifterUserID int64 `json:"gifter_user_id"` // The identifier of a user who gifted Telegram Premium; 0 if the gift was anonymous or is outgoing
	ReceiverUserID int64 `json:"receiver_user_id"` // The identifier of a user who received Telegram Premium; 0 if the gift is incoming
	Text *FormattedText `json:"text"` // Message added to the gifted Telegram Premium by the sender
	Currency string `json:"currency"` // Currency for the paid amount
	Amount int64 `json:"amount"` // The paid amount, in the smallest units of the currency
	Cryptocurrency string `json:"cryptocurrency"` // Cryptocurrency used to pay for the gift; may be empty if none
	CryptocurrencyAmount JSONInt64 `json:"cryptocurrency_amount"` // The paid amount, in the smallest units of the cryptocurrency; 0 if none
	MonthCount int32 `json:"month_count"` // Number of months the Telegram Premium subscription will be active after code activation; 0 if the number of months isn't integer
	DayCount int32 `json:"day_count"` // Number of days the Telegram Premium subscription will be active
	Sticker *Sticker `json:"sticker"` // A sticker to be shown in the message; may be null if unknown
}

func (t *MessageGiftedPremium) GetType() string { return "messageGiftedPremium" }

// MessagePremiumGiftCode — A Telegram Premium gift code was created for the user
type MessagePremiumGiftCode struct {
	CreatorID *MessageSender `json:"creator_id"` // Identifier of a chat or a user who created the gift code; may be null if unknown
	Text *FormattedText `json:"text"` // Message added to the gift
	IsFromGiveaway bool `json:"is_from_giveaway"` // True, if the gift code was created for a giveaway
	IsUnclaimed bool `json:"is_unclaimed"` // True, if the winner for the corresponding Telegram Premium subscription wasn't chosen
	Currency string `json:"currency"` // Currency for the paid amount; empty if unknown
	Amount int64 `json:"amount"` // The paid amount, in the smallest units of the currency; 0 if unknown
	Cryptocurrency string `json:"cryptocurrency"` // Cryptocurrency used to pay for the gift; may be empty if none or unknown
	CryptocurrencyAmount JSONInt64 `json:"cryptocurrency_amount"` // The paid amount, in the smallest units of the cryptocurrency; 0 if unknown
	MonthCount int32 `json:"month_count"` // Number of months the Telegram Premium subscription will be active after code activation; 0 if the number of months isn't integer
	DayCount int32 `json:"day_count"` // Number of days the Telegram Premium subscription will be active after code activation
	Sticker *Sticker `json:"sticker"` // A sticker to be shown in the message; may be null if unknown
	Code string `json:"code"` // The gift code
}

func (t *MessagePremiumGiftCode) GetType() string { return "messagePremiumGiftCode" }

// MessageGiveawayCreated — A giveaway was created for the chat. Use telegramPaymentPurposePremiumGiveaway, storePaymentPurposePremiumGiveaway, telegramPaymentPurposeStarGiveaway, or storePaymentPurposeStarGiveaway to create a giveaway
type MessageGiveawayCreated struct {
	StarCount int64 `json:"star_count"` // Number of Telegram Stars that will be shared by winners of the giveaway; 0 for Telegram Premium giveaways
}

func (t *MessageGiveawayCreated) GetType() string { return "messageGiveawayCreated" }

// MessageGiveaway — A giveaway
type MessageGiveaway struct {
	Parameters *GiveawayParameters `json:"parameters"` // Giveaway parameters
	WinnerCount int32 `json:"winner_count"` // Number of users which will receive Telegram Premium subscription gift codes
	Prize *GiveawayPrize `json:"prize"` // Prize of the giveaway
	Sticker *Sticker `json:"sticker"` // A sticker to be shown in the message; may be null if unknown
}

func (t *MessageGiveaway) GetType() string { return "messageGiveaway" }

// MessageGiveawayCompleted — A giveaway without public winners has been completed for the chat
type MessageGiveawayCompleted struct {
	GiveawayMessageID int64 `json:"giveaway_message_id"` // Identifier of the message with the giveaway; may be 0 or an identifier of a deleted message
	WinnerCount int32 `json:"winner_count"` // Number of winners in the giveaway
	IsStarGiveaway bool `json:"is_star_giveaway"` // True, if the giveaway is a Telegram Star giveaway
	UnclaimedPrizeCount int32 `json:"unclaimed_prize_count"` // Number of undistributed prizes; for Telegram Premium giveaways only
}

func (t *MessageGiveawayCompleted) GetType() string { return "messageGiveawayCompleted" }

// MessageGiveawayWinners — A giveaway with public winners has been completed for the chat
type MessageGiveawayWinners struct {
	BoostedChatID int64 `json:"boosted_chat_id"` // Identifier of the supergroup or channel chat, which was automatically boosted by the winners of the giveaway
	GiveawayMessageID int64 `json:"giveaway_message_id"` // Identifier of the message with the giveaway in the boosted chat
	AdditionalChatCount int32 `json:"additional_chat_count"` // Number of other chats that participated in the giveaway
	ActualWinnersSelectionDate int32 `json:"actual_winners_selection_date"` // Point in time (Unix timestamp) when the winners were selected. May be bigger than winners selection date specified in parameters of the giveaway
	OnlyNewMembers bool `json:"only_new_members"` // True, if only new members of the chats were eligible for the giveaway
	WasRefunded bool `json:"was_refunded"` // True, if the giveaway was canceled and was fully refunded
	Prize *GiveawayPrize `json:"prize"` // Prize of the giveaway
	PrizeDescription string `json:"prize_description"` // Additional description of the giveaway prize
	WinnerCount int32 `json:"winner_count"` // Total number of winners in the giveaway
	WinnerUserIDs []int64 `json:"winner_user_ids"` // Up to 100 user identifiers of the winners of the giveaway
	UnclaimedPrizeCount int32 `json:"unclaimed_prize_count"` // Number of undistributed prizes; for Telegram Premium giveaways only
}

func (t *MessageGiveawayWinners) GetType() string { return "messageGiveawayWinners" }

// MessageGiftedStars — Telegram Stars were gifted to a user
type MessageGiftedStars struct {
	GifterUserID int64 `json:"gifter_user_id"` // The identifier of a user who gifted Telegram Stars; 0 if the gift was anonymous or is outgoing
	ReceiverUserID int64 `json:"receiver_user_id"` // The identifier of a user who received Telegram Stars; 0 if the gift is incoming
	Currency string `json:"currency"` // Currency for the paid amount
	Amount int64 `json:"amount"` // The paid amount, in the smallest units of the currency
	Cryptocurrency string `json:"cryptocurrency"` // Cryptocurrency used to pay for the gift; may be empty if none
	CryptocurrencyAmount JSONInt64 `json:"cryptocurrency_amount"` // The paid amount, in the smallest units of the cryptocurrency; 0 if none
	StarCount int64 `json:"star_count"` // Number of Telegram Stars that were gifted
	TransactionID string `json:"transaction_id"` // Identifier of the transaction for Telegram Stars purchase; for receiver only
	Sticker *Sticker `json:"sticker"` // A sticker to be shown in the message; may be null if unknown
}

func (t *MessageGiftedStars) GetType() string { return "messageGiftedStars" }

// MessageGiftedTon — Toncoins were gifted to a user
type MessageGiftedTon struct {
	GifterUserID int64 `json:"gifter_user_id"` // The identifier of a user who gifted Toncoins; 0 if the gift was anonymous or is outgoing
	ReceiverUserID int64 `json:"receiver_user_id"` // The identifier of a user who received Toncoins; 0 if the gift is incoming
	TonAmount int64 `json:"ton_amount"` // The received Toncoin amount, in the smallest units of the cryptocurrency
	TransactionID string `json:"transaction_id"` // Identifier of the transaction for Toncoin credit; for receiver only
	Sticker *Sticker `json:"sticker"` // A sticker to be shown in the message; may be null if unknown
}

func (t *MessageGiftedTon) GetType() string { return "messageGiftedTon" }

// MessageGiveawayPrizeStars — A Telegram Stars were received by the current user from a giveaway
type MessageGiveawayPrizeStars struct {
	StarCount int64 `json:"star_count"` // Number of Telegram Stars that were received
	TransactionID string `json:"transaction_id"` // Identifier of the transaction for Telegram Stars credit
	BoostedChatID int64 `json:"boosted_chat_id"` // Identifier of the supergroup or channel chat, which was automatically boosted by the winners of the giveaway
	GiveawayMessageID int64 `json:"giveaway_message_id"` // Identifier of the message with the giveaway in the boosted chat; may be 0 or an identifier of a deleted message
	IsUnclaimed bool `json:"is_unclaimed"` // True, if the corresponding winner wasn't chosen and the Telegram Stars were received by the owner of the boosted chat
	Sticker *Sticker `json:"sticker"` // A sticker to be shown in the message; may be null if unknown
}

func (t *MessageGiveawayPrizeStars) GetType() string { return "messageGiveawayPrizeStars" }

// MessageGift — A regular gift was received or sent by the current user, or the current user was notified about a channel gift
type MessageGift struct {
	Gift *Gift `json:"gift"` // The gift
	SenderID *MessageSender `json:"sender_id"` // Sender of the gift; may be null for outgoing messages about prepaid upgrade of gifts from unknown users
	ReceiverID *MessageSender `json:"receiver_id"` // Receiver of the gift
	ReceivedGiftID string `json:"received_gift_id"` // Unique identifier of the received gift for the current user; only for the receiver of the gift
	Text *FormattedText `json:"text"` // Message added to the gift
	UniqueGiftNumber int32 `json:"unique_gift_number"` // Unique number of the gift among gifts upgraded from the same gift after upgrade; 0 if yet unassigned
	SellStarCount int64 `json:"sell_star_count"` // Number of Telegram Stars that can be claimed by the receiver instead of the regular gift; 0 if the gift can't be sold by the receiver
	PrepaidUpgradeStarCount int64 `json:"prepaid_upgrade_star_count"` // Number of Telegram Stars that were paid by the sender for the ability to upgrade the gift
	IsUpgradeSeparate bool `json:"is_upgrade_separate"` // True, if the upgrade was bought after the gift was sent. In this case, prepaid upgrade cost must not be added to the gift cost
	IsFromAuction bool `json:"is_from_auction"` // True, if the message is a notification about a gift won on an auction
	IsPrivate bool `json:"is_private"` // True, if the sender and gift text are shown only to the gift receiver; otherwise, everyone will be able to see them
	IsSaved bool `json:"is_saved"` // True, if the gift is displayed on the user's or the channel's profile page; only for the receiver of the gift
	IsPrepaidUpgrade bool `json:"is_prepaid_upgrade"` // True, if the message is about prepaid upgrade of the gift by another user
	CanBeUpgraded bool `json:"can_be_upgraded"` // True, if the gift can be upgraded to a unique gift; only for the receiver of the gift
	WasConverted bool `json:"was_converted"` // True, if the gift was converted to Telegram Stars; only for the receiver of the gift
	WasUpgraded bool `json:"was_upgraded"` // True, if the gift was upgraded to a unique gift
	WasRefunded bool `json:"was_refunded"` // True, if the gift was refunded and isn't available anymore
	UpgradedReceivedGiftID string `json:"upgraded_received_gift_id"` // Identifier of the corresponding upgraded gift; may be empty if unknown. Use getReceivedGift to get information about the gift
	PrepaidUpgradeHash string `json:"prepaid_upgrade_hash"` // If non-empty, then the user can pay for an upgrade of the gift using buyGiftUpgrade
}

func (t *MessageGift) GetType() string { return "messageGift" }

// MessageUpgradedGift — An upgraded gift was received or sent by the current user, or the current user was notified about a channel gift
type MessageUpgradedGift struct {
	Gift *UpgradedGift `json:"gift"` // The gift
	SenderID *MessageSender `json:"sender_id"` // Sender of the gift; may be null for anonymous gifts
	ReceiverID *MessageSender `json:"receiver_id"` // Receiver of the gift
	Origin *UpgradedGiftOrigin `json:"origin"` // Origin of the upgraded gift
	ReceivedGiftID string `json:"received_gift_id"` // Unique identifier of the received gift for the current user; only for the receiver of the gift
	IsSaved bool `json:"is_saved"` // True, if the gift is displayed on the user's or the channel's profile page; only for the receiver of the gift
	CanBeTransferred bool `json:"can_be_transferred"` // True, if the gift can be transferred to another owner; only for the receiver of the gift
	WasTransferred bool `json:"was_transferred"` // True, if the gift has already been transferred to another owner; only for the receiver of the gift
	TransferStarCount int64 `json:"transfer_star_count"` // Number of Telegram Stars that must be paid to transfer the upgraded gift; only for the receiver of the gift
	DropOriginalDetailsStarCount int64 `json:"drop_original_details_star_count"` // Number of Telegram Stars that must be paid to drop original details of the upgraded gift; 0 if not available; only for the receiver of the gift
	NextTransferDate int32 `json:"next_transfer_date"` // Point in time (Unix timestamp) when the gift can be transferred to another owner; can be in the past; 0 if the gift can be transferred immediately or transfer isn't possible; only for the receiver of the gift
	NextResaleDate int32 `json:"next_resale_date"` // Point in time (Unix timestamp) when the gift can be resold to another user; can be in the past; 0 if the gift can't be resold; only for the receiver of the gift
	ExportDate int32 `json:"export_date"` // Point in time (Unix timestamp) when the gift can be transferred to the TON blockchain as an NFT; can be in the past; 0 if NFT export isn't possible; only for the receiver of the gift
	CraftDate int32 `json:"craft_date"` // Point in time (Unix timestamp) when the gift can be used to craft another gift can be in the past; only for the receiver of the gift
}

func (t *MessageUpgradedGift) GetType() string { return "messageUpgradedGift" }

// MessageRefundedUpgradedGift — A gift which purchase, upgrade or transfer were refunded
type MessageRefundedUpgradedGift struct {
	Gift *Gift `json:"gift"` // The gift
	SenderID *MessageSender `json:"sender_id"` // Sender of the gift
	ReceiverID *MessageSender `json:"receiver_id"` // Receiver of the gift
	Origin *UpgradedGiftOrigin `json:"origin"` // Origin of the upgraded gift
}

func (t *MessageRefundedUpgradedGift) GetType() string { return "messageRefundedUpgradedGift" }

// MessageUpgradedGiftPurchaseOffer — An offer to purchase an upgraded gift was sent or received
type MessageUpgradedGiftPurchaseOffer struct {
	Gift *UpgradedGift `json:"gift"` // The gift
	State *GiftPurchaseOfferState `json:"state"` // State of the offer
	Price *GiftResalePrice `json:"price"` // The proposed price
	ExpirationDate int32 `json:"expiration_date"` // Point in time (Unix timestamp) when the offer will expire or has expired
}

func (t *MessageUpgradedGiftPurchaseOffer) GetType() string { return "messageUpgradedGiftPurchaseOffer" }

// MessageUpgradedGiftPurchaseOfferRejected — An offer to purchase a gift was rejected or expired
type MessageUpgradedGiftPurchaseOfferRejected struct {
	Gift *UpgradedGift `json:"gift"` // The gift
	Price *GiftResalePrice `json:"price"` // The proposed price
	OfferMessageID int64 `json:"offer_message_id"` // Identifier of the message with purchase offer which was rejected or expired; may be 0 or an identifier of a deleted message
	WasExpired bool `json:"was_expired"` // True, if the offer has expired; otherwise, the offer was explicitly rejected
}

func (t *MessageUpgradedGiftPurchaseOfferRejected) GetType() string { return "messageUpgradedGiftPurchaseOfferRejected" }

// MessagePaidMessagesRefunded — Paid messages were refunded @message_count The number of refunded messages @star_count The number of refunded Telegram Stars
type MessagePaidMessagesRefunded struct {
	MessageCount int32 `json:"message_count"`
	StarCount int64 `json:"star_count"`
}

func (t *MessagePaidMessagesRefunded) GetType() string { return "messagePaidMessagesRefunded" }

// MessagePaidMessagePriceChanged — A price for paid messages was changed in the supergroup chat @paid_message_star_count The new number of Telegram Stars that must be paid by non-administrator users of the supergroup chat for each sent message
type MessagePaidMessagePriceChanged struct {
	PaidMessageStarCount int64 `json:"paid_message_star_count"`
}

func (t *MessagePaidMessagePriceChanged) GetType() string { return "messagePaidMessagePriceChanged" }

// MessageDirectMessagePriceChanged — A price for direct messages was changed in the channel chat
type MessageDirectMessagePriceChanged struct {
	IsEnabled bool `json:"is_enabled"` // True, if direct messages group was enabled for the channel; false otherwise
	PaidMessageStarCount int64 `json:"paid_message_star_count"` // The new number of Telegram Stars that must be paid by non-administrator users of the channel chat for each message sent to the direct messages group;
}

func (t *MessageDirectMessagePriceChanged) GetType() string { return "messageDirectMessagePriceChanged" }

// MessageChecklistTasksDone — Some tasks from a checklist were marked as done or not done
type MessageChecklistTasksDone struct {
	ChecklistMessageID int64 `json:"checklist_message_id"` // Identifier of the message with the checklist; may be 0 or an identifier of a deleted message
	MarkedAsDoneTaskIDs []int32 `json:"marked_as_done_task_ids"` // Identifiers of tasks that were marked as done
	MarkedAsNotDoneTaskIDs []int32 `json:"marked_as_not_done_task_ids"` // Identifiers of tasks that were marked as not done
}

func (t *MessageChecklistTasksDone) GetType() string { return "messageChecklistTasksDone" }

// MessageChecklistTasksAdded — Some tasks were added to a checklist
type MessageChecklistTasksAdded struct {
	ChecklistMessageID int64 `json:"checklist_message_id"` // Identifier of the message with the checklist; may be 0 or an identifier of a deleted message
	Tasks []*ChecklistTask `json:"tasks"` // List of tasks added to the checklist
}

func (t *MessageChecklistTasksAdded) GetType() string { return "messageChecklistTasksAdded" }

// MessageSuggestedPostApprovalFailed — Approval of suggested post has failed, because the user which proposed the post had no enough funds
type MessageSuggestedPostApprovalFailed struct {
	SuggestedPostMessageID int64 `json:"suggested_post_message_id"` // Identifier of the message with the suggested post; may be 0 or an identifier of a deleted message
	Price *SuggestedPostPrice `json:"price"` // Price of the suggested post
}

func (t *MessageSuggestedPostApprovalFailed) GetType() string { return "messageSuggestedPostApprovalFailed" }

// MessageSuggestedPostApproved — A suggested post was approved
type MessageSuggestedPostApproved struct {
	SuggestedPostMessageID int64 `json:"suggested_post_message_id"` // Identifier of the message with the suggested post; may be 0 or an identifier of a deleted message
	Price *SuggestedPostPrice `json:"price"` // Price of the suggested post; may be null if the post is non-paid
	SendDate int32 `json:"send_date"` // Point in time (Unix timestamp) when the post is expected to be published
}

func (t *MessageSuggestedPostApproved) GetType() string { return "messageSuggestedPostApproved" }

// MessageSuggestedPostDeclined — A suggested post was declined
type MessageSuggestedPostDeclined struct {
	SuggestedPostMessageID int64 `json:"suggested_post_message_id"` // Identifier of the message with the suggested post; may be 0 or an identifier of a deleted message
	Comment string `json:"comment"` // Comment added by administrator of the channel when the post was declined
}

func (t *MessageSuggestedPostDeclined) GetType() string { return "messageSuggestedPostDeclined" }

// MessageSuggestedPostPaid — A suggested post was published for getOption("suggested_post_lifetime_min") seconds and payment for the post was received
type MessageSuggestedPostPaid struct {
	SuggestedPostMessageID int64 `json:"suggested_post_message_id"` // Identifier of the message with the suggested post; may be 0 or an identifier of a deleted message
	StarAmount *StarAmount `json:"star_amount"` // The amount of received Telegram Stars
	TonAmount int64 `json:"ton_amount"` // The amount of received Toncoins; in the smallest units of the cryptocurrency
}

func (t *MessageSuggestedPostPaid) GetType() string { return "messageSuggestedPostPaid" }

// MessageSuggestedPostRefunded — A suggested post was refunded
type MessageSuggestedPostRefunded struct {
	SuggestedPostMessageID int64 `json:"suggested_post_message_id"` // Identifier of the message with the suggested post; may be 0 or an identifier of a deleted message
	Reason *SuggestedPostRefundReason `json:"reason"` // Reason of the refund
}

func (t *MessageSuggestedPostRefunded) GetType() string { return "messageSuggestedPostRefunded" }

// MessageContactRegistered — A contact has registered with Telegram
type MessageContactRegistered struct {
}

func (t *MessageContactRegistered) GetType() string { return "messageContactRegistered" }

// MessageUsersShared — The current user shared users, which were requested by the bot @users The shared users @button_id Identifier of the keyboard button with the request
type MessageUsersShared struct {
	Users []*SharedUser `json:"users"`
	ButtonID int32 `json:"button_id"`
}

func (t *MessageUsersShared) GetType() string { return "messageUsersShared" }

// MessageChatShared — The current user shared a chat, which was requested by the bot @chat The shared chat @button_id Identifier of the keyboard button with the request
type MessageChatShared struct {
	Chat *SharedChat `json:"chat"`
	ButtonID int32 `json:"button_id"`
}

func (t *MessageChatShared) GetType() string { return "messageChatShared" }

