// Code generated by go-tdlib codegen. DO NOT EDIT.
package tdapi

// ChatEventShowMessageSenderToggled — The show_message_sender setting of a channel was toggled @show_message_sender New value of show_message_sender
type ChatEventShowMessageSenderToggled struct {
	ShowMessageSender bool `json:"show_message_sender"`
}

func (t *ChatEventShowMessageSenderToggled) GetType() string { return "chatEventShowMessageSenderToggled" }

// ChatEventAutomaticTranslationToggled — The has_automatic_translation setting of a channel was toggled @has_automatic_translation New value of has_automatic_translation
type ChatEventAutomaticTranslationToggled struct {
	HasAutomaticTranslation bool `json:"has_automatic_translation"`
}

func (t *ChatEventAutomaticTranslationToggled) GetType() string { return "chatEventAutomaticTranslationToggled" }

// ChatEventInviteLinkEdited — A chat invite link was edited @old_invite_link Previous information about the invite link @new_invite_link New information about the invite link
type ChatEventInviteLinkEdited struct {
	OldInviteLink *ChatInviteLink `json:"old_invite_link"`
	NewInviteLink *ChatInviteLink `json:"new_invite_link"`
}

func (t *ChatEventInviteLinkEdited) GetType() string { return "chatEventInviteLinkEdited" }

// ChatEventInviteLinkRevoked — A chat invite link was revoked @invite_link The invite link
type ChatEventInviteLinkRevoked struct {
	InviteLink *ChatInviteLink `json:"invite_link"`
}

func (t *ChatEventInviteLinkRevoked) GetType() string { return "chatEventInviteLinkRevoked" }

// ChatEventInviteLinkDeleted — A revoked chat invite link was deleted @invite_link The invite link
type ChatEventInviteLinkDeleted struct {
	InviteLink *ChatInviteLink `json:"invite_link"`
}

func (t *ChatEventInviteLinkDeleted) GetType() string { return "chatEventInviteLinkDeleted" }

// ChatEventVideoChatCreated — A video chat was created @group_call_id Identifier of the video chat. The video chat can be received through the method getGroupCall
type ChatEventVideoChatCreated struct {
	GroupCallID int32 `json:"group_call_id"`
}

func (t *ChatEventVideoChatCreated) GetType() string { return "chatEventVideoChatCreated" }

// ChatEventVideoChatEnded — A video chat was ended @group_call_id Identifier of the video chat. The video chat can be received through the method getGroupCall
type ChatEventVideoChatEnded struct {
	GroupCallID int32 `json:"group_call_id"`
}

func (t *ChatEventVideoChatEnded) GetType() string { return "chatEventVideoChatEnded" }

// ChatEventVideoChatMuteNewParticipantsToggled — The mute_new_participants setting of a video chat was toggled @mute_new_participants New value of the mute_new_participants setting
type ChatEventVideoChatMuteNewParticipantsToggled struct {
	MuteNewParticipants bool `json:"mute_new_participants"`
}

func (t *ChatEventVideoChatMuteNewParticipantsToggled) GetType() string { return "chatEventVideoChatMuteNewParticipantsToggled" }

// ChatEventVideoChatParticipantIsMutedToggled — A video chat participant was muted or unmuted @participant_id Identifier of the affected group call participant @is_muted New value of is_muted
type ChatEventVideoChatParticipantIsMutedToggled struct {
	ParticipantID *MessageSender `json:"participant_id"`
	IsMuted bool `json:"is_muted"`
}

func (t *ChatEventVideoChatParticipantIsMutedToggled) GetType() string { return "chatEventVideoChatParticipantIsMutedToggled" }

// ChatEventVideoChatParticipantVolumeLevelChanged — A video chat participant volume level was changed @participant_id Identifier of the affected group call participant @volume_level New value of volume_level; 1-20000 in hundreds of percents
type ChatEventVideoChatParticipantVolumeLevelChanged struct {
	ParticipantID *MessageSender `json:"participant_id"`
	VolumeLevel int32 `json:"volume_level"`
}

func (t *ChatEventVideoChatParticipantVolumeLevelChanged) GetType() string { return "chatEventVideoChatParticipantVolumeLevelChanged" }

// ChatEventIsForumToggled — The is_forum setting of a channel was toggled @is_forum New value of is_forum
type ChatEventIsForumToggled struct {
	IsForum bool `json:"is_forum"`
}

func (t *ChatEventIsForumToggled) GetType() string { return "chatEventIsForumToggled" }

// ChatEventForumTopicCreated — A new forum topic was created @topic_info Information about the topic
type ChatEventForumTopicCreated struct {
	TopicInfo *ForumTopicInfo `json:"topic_info"`
}

func (t *ChatEventForumTopicCreated) GetType() string { return "chatEventForumTopicCreated" }

// ChatEventForumTopicEdited — A forum topic was edited @old_topic_info Old information about the topic @new_topic_info New information about the topic
type ChatEventForumTopicEdited struct {
	OldTopicInfo *ForumTopicInfo `json:"old_topic_info"`
	NewTopicInfo *ForumTopicInfo `json:"new_topic_info"`
}

func (t *ChatEventForumTopicEdited) GetType() string { return "chatEventForumTopicEdited" }

// ChatEventForumTopicToggleIsClosed — A forum topic was closed or reopened @topic_info New information about the topic
type ChatEventForumTopicToggleIsClosed struct {
	TopicInfo *ForumTopicInfo `json:"topic_info"`
}

func (t *ChatEventForumTopicToggleIsClosed) GetType() string { return "chatEventForumTopicToggleIsClosed" }

// ChatEventForumTopicToggleIsHidden — The General forum topic was hidden or unhidden @topic_info New information about the topic
type ChatEventForumTopicToggleIsHidden struct {
	TopicInfo *ForumTopicInfo `json:"topic_info"`
}

func (t *ChatEventForumTopicToggleIsHidden) GetType() string { return "chatEventForumTopicToggleIsHidden" }

// ChatEventForumTopicDeleted — A forum topic was deleted @topic_info Information about the topic
type ChatEventForumTopicDeleted struct {
	TopicInfo *ForumTopicInfo `json:"topic_info"`
}

func (t *ChatEventForumTopicDeleted) GetType() string { return "chatEventForumTopicDeleted" }

// ChatEventForumTopicPinned — A pinned forum topic was changed @old_topic_info Information about the old pinned topic; may be null @new_topic_info Information about the new pinned topic; may be null
type ChatEventForumTopicPinned struct {
	OldTopicInfo *ForumTopicInfo `json:"old_topic_info"`
	NewTopicInfo *ForumTopicInfo `json:"new_topic_info"`
}

func (t *ChatEventForumTopicPinned) GetType() string { return "chatEventForumTopicPinned" }

// ChatEvent — Represents a chat event
type ChatEvent struct {
	ID JSONInt64 `json:"id"` // Chat event identifier
	Date int32 `json:"date"` // Point in time (Unix timestamp) when the event happened
	MemberID *MessageSender `json:"member_id"` // Identifier of the user or chat who performed the action
	Action *ChatEventAction `json:"action"` // The action
}

func (t *ChatEvent) GetType() string { return "chatEvent" }

// ChatEvents — Contains a list of chat events @events List of events
type ChatEvents struct {
	Events []*ChatEvent `json:"events"`
}

func (t *ChatEvents) GetType() string { return "chatEvents" }

// ChatEventLogFilters — Represents a set of filters used to obtain a chat event log
type ChatEventLogFilters struct {
	MessageEdits bool `json:"message_edits"` // True, if message edits need to be returned
	MessageDeletions bool `json:"message_deletions"` // True, if message deletions need to be returned
	MessagePins bool `json:"message_pins"` // True, if pin/unpin events need to be returned
	MemberJoins bool `json:"member_joins"` // True, if members joining events need to be returned
	MemberLeaves bool `json:"member_leaves"` // True, if members leaving events need to be returned
	MemberInvites bool `json:"member_invites"` // True, if invited member events need to be returned
	MemberPromotions bool `json:"member_promotions"` // True, if member promotion/demotion events need to be returned
	MemberRestrictions bool `json:"member_restrictions"` // True, if member restricted/unrestricted/banned/unbanned events need to be returned
	MemberTagChanges bool `json:"member_tag_changes"` // True, if member tag and custom title change events need to be returned
	InfoChanges bool `json:"info_changes"` // True, if changes in chat information need to be returned
	SettingChanges bool `json:"setting_changes"` // True, if changes in chat settings need to be returned
	InviteLinkChanges bool `json:"invite_link_changes"` // True, if changes to invite links need to be returned
	VideoChatChanges bool `json:"video_chat_changes"` // True, if video chat actions need to be returned
	ForumChanges bool `json:"forum_changes"` // True, if forum-related actions need to be returned
	SubscriptionExtensions bool `json:"subscription_extensions"` // True, if subscription extensions need to be returned
}

func (t *ChatEventLogFilters) GetType() string { return "chatEventLogFilters" }

// LanguagePackStringValue — Represents the value of a string in a language pack
type LanguagePackStringValue struct {
}

func (t *LanguagePackStringValue) GetType() string { return "LanguagePackStringValue" }

// LanguagePackStringValueOrdinary — An ordinary language pack string @value String value
type LanguagePackStringValueOrdinary struct {
	Value string `json:"value"`
}

func (t *LanguagePackStringValueOrdinary) GetType() string { return "languagePackStringValueOrdinary" }

// LanguagePackStringValuePluralized — A language pack string which has different forms based on the number of some object it mentions. See https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html for more information
type LanguagePackStringValuePluralized struct {
	ZeroValue string `json:"zero_value"` // Value for zero objects
	OneValue string `json:"one_value"` // Value for one object
	TwoValue string `json:"two_value"` // Value for two objects
	FewValue string `json:"few_value"` // Value for few objects
	ManyValue string `json:"many_value"` // Value for many objects
	OtherValue string `json:"other_value"` // Default value
}

func (t *LanguagePackStringValuePluralized) GetType() string { return "languagePackStringValuePluralized" }

// LanguagePackStringValueDeleted — A deleted language pack string, the value must be taken from the built-in English language pack
type LanguagePackStringValueDeleted struct {
}

func (t *LanguagePackStringValueDeleted) GetType() string { return "languagePackStringValueDeleted" }

// LanguagePackString — Represents one language pack string @key String key @value String value; pass null if the string needs to be taken from the built-in English language pack
type LanguagePackString struct {
	Key string `json:"key"`
	Value *LanguagePackStringValue `json:"value"`
}

func (t *LanguagePackString) GetType() string { return "languagePackString" }

// LanguagePackStrings — Contains a list of language pack strings @strings A list of language pack strings
type LanguagePackStrings struct {
	Strings []*LanguagePackString `json:"strings"`
}

func (t *LanguagePackStrings) GetType() string { return "languagePackStrings" }

// LanguagePackInfo — Contains information about a language pack
type LanguagePackInfo struct {
	ID string `json:"id"` // Unique language pack identifier
	BaseLanguagePackID string `json:"base_language_pack_id"` // Identifier of a base language pack; may be empty. If a string is missed in the language pack, then it must be fetched from base language pack. Unsupported in custom language packs
	Name string `json:"name"` // Language name
	NativeName string `json:"native_name"` // Name of the language in that language
	PluralCode string `json:"plural_code"` // A language code to be used to apply plural forms. See https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html for more information
	IsOfficial bool `json:"is_official"` // True, if the language pack is official
	IsRtl bool `json:"is_rtl"` // True, if the language pack strings are RTL
	IsBeta bool `json:"is_beta"` // True, if the language pack is a beta language pack
	IsInstalled bool `json:"is_installed"` // True, if the language pack is installed by the current user
	TotalStringCount int32 `json:"total_string_count"` // Total number of non-deleted strings from the language pack
	TranslatedStringCount int32 `json:"translated_string_count"` // Total number of translated strings from the language pack
	LocalStringCount int32 `json:"local_string_count"` // Total number of non-deleted strings from the language pack available locally
	TranslationURL string `json:"translation_url"` // Link to language translation interface; empty for custom local language packs
}

func (t *LanguagePackInfo) GetType() string { return "languagePackInfo" }

// LocalizationTargetInfo — Contains information about the current localization target @language_packs List of available language packs for this application
type LocalizationTargetInfo struct {
	LanguagePacks []*LanguagePackInfo `json:"language_packs"`
}

func (t *LocalizationTargetInfo) GetType() string { return "localizationTargetInfo" }

// PremiumLimitType — Describes type of limit, increased for Premium users
type PremiumLimitType struct {
}

func (t *PremiumLimitType) GetType() string { return "PremiumLimitType" }

// PremiumLimitTypeSupergroupCount — The maximum number of joined supergroups and channels
type PremiumLimitTypeSupergroupCount struct {
}

func (t *PremiumLimitTypeSupergroupCount) GetType() string { return "premiumLimitTypeSupergroupCount" }

// PremiumLimitTypePinnedChatCount — The maximum number of pinned chats in the main chat list
type PremiumLimitTypePinnedChatCount struct {
}

func (t *PremiumLimitTypePinnedChatCount) GetType() string { return "premiumLimitTypePinnedChatCount" }

// PremiumLimitTypeCreatedPublicChatCount — The maximum number of created public chats
type PremiumLimitTypeCreatedPublicChatCount struct {
}

func (t *PremiumLimitTypeCreatedPublicChatCount) GetType() string { return "premiumLimitTypeCreatedPublicChatCount" }

// PremiumLimitTypeSavedAnimationCount — The maximum number of saved animations
type PremiumLimitTypeSavedAnimationCount struct {
}

func (t *PremiumLimitTypeSavedAnimationCount) GetType() string { return "premiumLimitTypeSavedAnimationCount" }

// PremiumLimitTypeFavoriteStickerCount — The maximum number of favorite stickers
type PremiumLimitTypeFavoriteStickerCount struct {
}

func (t *PremiumLimitTypeFavoriteStickerCount) GetType() string { return "premiumLimitTypeFavoriteStickerCount" }

// PremiumLimitTypeChatFolderCount — The maximum number of chat folders
type PremiumLimitTypeChatFolderCount struct {
}

func (t *PremiumLimitTypeChatFolderCount) GetType() string { return "premiumLimitTypeChatFolderCount" }

// PremiumLimitTypeChatFolderChosenChatCount — The maximum number of pinned and always included, or always excluded chats in a chat folder
type PremiumLimitTypeChatFolderChosenChatCount struct {
}

func (t *PremiumLimitTypeChatFolderChosenChatCount) GetType() string { return "premiumLimitTypeChatFolderChosenChatCount" }

// PremiumLimitTypePinnedArchivedChatCount — The maximum number of pinned chats in the archive chat list
type PremiumLimitTypePinnedArchivedChatCount struct {
}

func (t *PremiumLimitTypePinnedArchivedChatCount) GetType() string { return "premiumLimitTypePinnedArchivedChatCount" }

// PremiumLimitTypePinnedSavedMessagesTopicCount — The maximum number of pinned Saved Messages topics
type PremiumLimitTypePinnedSavedMessagesTopicCount struct {
}

func (t *PremiumLimitTypePinnedSavedMessagesTopicCount) GetType() string { return "premiumLimitTypePinnedSavedMessagesTopicCount" }

// PremiumLimitTypeCaptionLength — The maximum length of sent media caption
type PremiumLimitTypeCaptionLength struct {
}

func (t *PremiumLimitTypeCaptionLength) GetType() string { return "premiumLimitTypeCaptionLength" }

// PremiumLimitTypeBioLength — The maximum length of the user's bio
type PremiumLimitTypeBioLength struct {
}

func (t *PremiumLimitTypeBioLength) GetType() string { return "premiumLimitTypeBioLength" }

// PremiumLimitTypeChatFolderInviteLinkCount — The maximum number of invite links for a chat folder
type PremiumLimitTypeChatFolderInviteLinkCount struct {
}

func (t *PremiumLimitTypeChatFolderInviteLinkCount) GetType() string { return "premiumLimitTypeChatFolderInviteLinkCount" }

// PremiumLimitTypeShareableChatFolderCount — The maximum number of added shareable chat folders
type PremiumLimitTypeShareableChatFolderCount struct {
}

func (t *PremiumLimitTypeShareableChatFolderCount) GetType() string { return "premiumLimitTypeShareableChatFolderCount" }

// PremiumLimitTypeActiveStoryCount — The maximum number of active stories
type PremiumLimitTypeActiveStoryCount struct {
}

func (t *PremiumLimitTypeActiveStoryCount) GetType() string { return "premiumLimitTypeActiveStoryCount" }

// PremiumLimitTypeWeeklyPostedStoryCount — The maximum number of stories posted per week
type PremiumLimitTypeWeeklyPostedStoryCount struct {
}

func (t *PremiumLimitTypeWeeklyPostedStoryCount) GetType() string { return "premiumLimitTypeWeeklyPostedStoryCount" }

// PremiumLimitTypeMonthlyPostedStoryCount — The maximum number of stories posted per month
type PremiumLimitTypeMonthlyPostedStoryCount struct {
}

func (t *PremiumLimitTypeMonthlyPostedStoryCount) GetType() string { return "premiumLimitTypeMonthlyPostedStoryCount" }

// PremiumLimitTypeStoryCaptionLength — The maximum length of captions of posted stories
type PremiumLimitTypeStoryCaptionLength struct {
}

func (t *PremiumLimitTypeStoryCaptionLength) GetType() string { return "premiumLimitTypeStoryCaptionLength" }

// PremiumLimitTypeStorySuggestedReactionAreaCount — The maximum number of suggested reaction areas on a story
type PremiumLimitTypeStorySuggestedReactionAreaCount struct {
}

func (t *PremiumLimitTypeStorySuggestedReactionAreaCount) GetType() string { return "premiumLimitTypeStorySuggestedReactionAreaCount" }

// PremiumLimitTypeSimilarChatCount — The maximum number of received similar chats
type PremiumLimitTypeSimilarChatCount struct {
}

func (t *PremiumLimitTypeSimilarChatCount) GetType() string { return "premiumLimitTypeSimilarChatCount" }

// PremiumFeature — Describes a feature available to Premium users
type PremiumFeature struct {
}

func (t *PremiumFeature) GetType() string { return "PremiumFeature" }

// PremiumFeatureIncreasedLimits — Increased limits
type PremiumFeatureIncreasedLimits struct {
}

func (t *PremiumFeatureIncreasedLimits) GetType() string { return "premiumFeatureIncreasedLimits" }

// PremiumFeatureIncreasedUploadFileSize — Increased maximum upload file size
type PremiumFeatureIncreasedUploadFileSize struct {
}

func (t *PremiumFeatureIncreasedUploadFileSize) GetType() string { return "premiumFeatureIncreasedUploadFileSize" }

// PremiumFeatureImprovedDownloadSpeed — Improved download speed
type PremiumFeatureImprovedDownloadSpeed struct {
}

func (t *PremiumFeatureImprovedDownloadSpeed) GetType() string { return "premiumFeatureImprovedDownloadSpeed" }

// PremiumFeatureVoiceRecognition — The ability to convert voice notes to text
type PremiumFeatureVoiceRecognition struct {
}

func (t *PremiumFeatureVoiceRecognition) GetType() string { return "premiumFeatureVoiceRecognition" }

// PremiumFeatureDisabledAds — Disabled ads
type PremiumFeatureDisabledAds struct {
}

func (t *PremiumFeatureDisabledAds) GetType() string { return "premiumFeatureDisabledAds" }

// PremiumFeatureUniqueReactions — Allowed to use more reactions
type PremiumFeatureUniqueReactions struct {
}

func (t *PremiumFeatureUniqueReactions) GetType() string { return "premiumFeatureUniqueReactions" }

// PremiumFeatureUniqueStickers — Allowed to use premium stickers with unique effects
type PremiumFeatureUniqueStickers struct {
}

func (t *PremiumFeatureUniqueStickers) GetType() string { return "premiumFeatureUniqueStickers" }

// PremiumFeatureCustomEmoji — Allowed to use custom emoji stickers in message texts and captions
type PremiumFeatureCustomEmoji struct {
}

func (t *PremiumFeatureCustomEmoji) GetType() string { return "premiumFeatureCustomEmoji" }

// PremiumFeatureAdvancedChatManagement — Ability to change position of the main chat list, archive and mute all new chats from non-contacts, and completely disable notifications about the user's contacts joined Telegram
type PremiumFeatureAdvancedChatManagement struct {
}

func (t *PremiumFeatureAdvancedChatManagement) GetType() string { return "premiumFeatureAdvancedChatManagement" }

// PremiumFeatureProfileBadge — A badge in the user's profile
type PremiumFeatureProfileBadge struct {
}

func (t *PremiumFeatureProfileBadge) GetType() string { return "premiumFeatureProfileBadge" }

// PremiumFeatureEmojiStatus — The ability to show an emoji status along with the user's name
type PremiumFeatureEmojiStatus struct {
}

func (t *PremiumFeatureEmojiStatus) GetType() string { return "premiumFeatureEmojiStatus" }

// PremiumFeatureAnimatedProfilePhoto — Profile photo animation on message and chat screens
type PremiumFeatureAnimatedProfilePhoto struct {
}

func (t *PremiumFeatureAnimatedProfilePhoto) GetType() string { return "premiumFeatureAnimatedProfilePhoto" }

// PremiumFeatureForumTopicIcon — The ability to set a custom emoji as a forum topic icon
type PremiumFeatureForumTopicIcon struct {
}

func (t *PremiumFeatureForumTopicIcon) GetType() string { return "premiumFeatureForumTopicIcon" }

// PremiumFeatureAppIcons — Allowed to set a premium application icons
type PremiumFeatureAppIcons struct {
}

func (t *PremiumFeatureAppIcons) GetType() string { return "premiumFeatureAppIcons" }

// PremiumFeatureRealTimeChatTranslation — Allowed to translate chat messages real-time
type PremiumFeatureRealTimeChatTranslation struct {
}

func (t *PremiumFeatureRealTimeChatTranslation) GetType() string { return "premiumFeatureRealTimeChatTranslation" }

// PremiumFeatureUpgradedStories — Allowed to use many additional features for stories
type PremiumFeatureUpgradedStories struct {
}

func (t *PremiumFeatureUpgradedStories) GetType() string { return "premiumFeatureUpgradedStories" }

// PremiumFeatureChatBoost — The ability to boost chats
type PremiumFeatureChatBoost struct {
}

func (t *PremiumFeatureChatBoost) GetType() string { return "premiumFeatureChatBoost" }

// PremiumFeatureAccentColor — The ability to choose accent color for replies and user profile
type PremiumFeatureAccentColor struct {
}

func (t *PremiumFeatureAccentColor) GetType() string { return "premiumFeatureAccentColor" }

// PremiumFeatureBackgroundForBoth — The ability to set private chat background for both users
type PremiumFeatureBackgroundForBoth struct {
}

func (t *PremiumFeatureBackgroundForBoth) GetType() string { return "premiumFeatureBackgroundForBoth" }

// PremiumFeatureSavedMessagesTags — The ability to use tags in Saved Messages
type PremiumFeatureSavedMessagesTags struct {
}

func (t *PremiumFeatureSavedMessagesTags) GetType() string { return "premiumFeatureSavedMessagesTags" }

// PremiumFeatureMessagePrivacy — The ability to disallow incoming voice and video note messages in private chats using setUserPrivacySettingRules with userPrivacySettingAllowPrivateVoiceAndVideoNoteMessages
type PremiumFeatureMessagePrivacy struct {
}

func (t *PremiumFeatureMessagePrivacy) GetType() string { return "premiumFeatureMessagePrivacy" }

// PremiumFeatureLastSeenTimes — The ability to view last seen and read times of other users even if they can't view last seen or read time for the current user
type PremiumFeatureLastSeenTimes struct {
}

func (t *PremiumFeatureLastSeenTimes) GetType() string { return "premiumFeatureLastSeenTimes" }

// PremiumFeatureBusiness — The ability to use Business features
type PremiumFeatureBusiness struct {
}

func (t *PremiumFeatureBusiness) GetType() string { return "premiumFeatureBusiness" }

// PremiumFeatureMessageEffects — The ability to use all available message effects
type PremiumFeatureMessageEffects struct {
}

func (t *PremiumFeatureMessageEffects) GetType() string { return "premiumFeatureMessageEffects" }

// PremiumFeatureChecklists — The ability to create and use checklist messages
type PremiumFeatureChecklists struct {
}

func (t *PremiumFeatureChecklists) GetType() string { return "premiumFeatureChecklists" }

// PremiumFeaturePaidMessages — The ability to require a payment for incoming messages in new chats
type PremiumFeaturePaidMessages struct {
}

func (t *PremiumFeaturePaidMessages) GetType() string { return "premiumFeaturePaidMessages" }

// PremiumFeatureProtectPrivateChatContent — The ability to enable content protection in private chats
type PremiumFeatureProtectPrivateChatContent struct {
}

func (t *PremiumFeatureProtectPrivateChatContent) GetType() string { return "premiumFeatureProtectPrivateChatContent" }

// BusinessFeature — Describes a feature available to Business user accounts
type BusinessFeature struct {
}

func (t *BusinessFeature) GetType() string { return "BusinessFeature" }

// BusinessFeatureLocation — The ability to set location
type BusinessFeatureLocation struct {
}

func (t *BusinessFeatureLocation) GetType() string { return "businessFeatureLocation" }

// BusinessFeatureOpeningHours — The ability to set opening hours
type BusinessFeatureOpeningHours struct {
}

func (t *BusinessFeatureOpeningHours) GetType() string { return "businessFeatureOpeningHours" }

// BusinessFeatureQuickReplies — The ability to use quick replies
type BusinessFeatureQuickReplies struct {
}

func (t *BusinessFeatureQuickReplies) GetType() string { return "businessFeatureQuickReplies" }

// BusinessFeatureGreetingMessage — The ability to set up a greeting message
type BusinessFeatureGreetingMessage struct {
}

func (t *BusinessFeatureGreetingMessage) GetType() string { return "businessFeatureGreetingMessage" }

// BusinessFeatureAwayMessage — The ability to set up an away message
type BusinessFeatureAwayMessage struct {
}

func (t *BusinessFeatureAwayMessage) GetType() string { return "businessFeatureAwayMessage" }

// BusinessFeatureAccountLinks — The ability to create links to the business account with predefined message text
type BusinessFeatureAccountLinks struct {
}

func (t *BusinessFeatureAccountLinks) GetType() string { return "businessFeatureAccountLinks" }

// BusinessFeatureStartPage — The ability to customize start page
type BusinessFeatureStartPage struct {
}

func (t *BusinessFeatureStartPage) GetType() string { return "businessFeatureStartPage" }

// BusinessFeatureBots — The ability to connect a bot to the account
type BusinessFeatureBots struct {
}

func (t *BusinessFeatureBots) GetType() string { return "businessFeatureBots" }

// BusinessFeatureEmojiStatus — The ability to show an emoji status along with the business name
type BusinessFeatureEmojiStatus struct {
}

func (t *BusinessFeatureEmojiStatus) GetType() string { return "businessFeatureEmojiStatus" }

// BusinessFeatureChatFolderTags — The ability to display folder names for each chat in the chat list
type BusinessFeatureChatFolderTags struct {
}

func (t *BusinessFeatureChatFolderTags) GetType() string { return "businessFeatureChatFolderTags" }

// BusinessFeatureUpgradedStories — Allowed to use many additional features for stories
type BusinessFeatureUpgradedStories struct {
}

func (t *BusinessFeatureUpgradedStories) GetType() string { return "businessFeatureUpgradedStories" }

// PremiumStoryFeature — Describes a story feature available to Premium users
type PremiumStoryFeature struct {
}

func (t *PremiumStoryFeature) GetType() string { return "PremiumStoryFeature" }

// PremiumStoryFeaturePriorityOrder — Stories of the current user are displayed before stories of non-Premium contacts, supergroups, and channels
type PremiumStoryFeaturePriorityOrder struct {
}

func (t *PremiumStoryFeaturePriorityOrder) GetType() string { return "premiumStoryFeaturePriorityOrder" }

// PremiumStoryFeatureStealthMode — The ability to hide the fact that the user viewed other's stories
type PremiumStoryFeatureStealthMode struct {
}

func (t *PremiumStoryFeatureStealthMode) GetType() string { return "premiumStoryFeatureStealthMode" }

// PremiumStoryFeaturePermanentViewsHistory — The ability to check who opened the current user's stories after they expire
type PremiumStoryFeaturePermanentViewsHistory struct {
}

func (t *PremiumStoryFeaturePermanentViewsHistory) GetType() string { return "premiumStoryFeaturePermanentViewsHistory" }

// PremiumStoryFeatureCustomExpirationDuration — The ability to set custom expiration duration for stories
type PremiumStoryFeatureCustomExpirationDuration struct {
}

func (t *PremiumStoryFeatureCustomExpirationDuration) GetType() string { return "premiumStoryFeatureCustomExpirationDuration" }

// PremiumStoryFeatureSaveStories — The ability to save other's unprotected stories
type PremiumStoryFeatureSaveStories struct {
}

func (t *PremiumStoryFeatureSaveStories) GetType() string { return "premiumStoryFeatureSaveStories" }

// PremiumStoryFeatureLinksAndFormatting — The ability to use links and formatting in story caption, and use inputStoryAreaTypeLink areas
type PremiumStoryFeatureLinksAndFormatting struct {
}

func (t *PremiumStoryFeatureLinksAndFormatting) GetType() string { return "premiumStoryFeatureLinksAndFormatting" }

// PremiumStoryFeatureVideoQuality — The ability to choose better quality for viewed stories
type PremiumStoryFeatureVideoQuality struct {
}

func (t *PremiumStoryFeatureVideoQuality) GetType() string { return "premiumStoryFeatureVideoQuality" }

// PremiumLimit — Contains information about a limit, increased for Premium users @type The type of the limit @default_value Default value of the limit @premium_value Value of the limit for Premium users
type PremiumLimit struct {
	Type *PremiumLimitType `json:"type"`
	DefaultValue int32 `json:"default_value"`
	PremiumValue int32 `json:"premium_value"`
}

func (t *PremiumLimit) GetType() string { return "premiumLimit" }

// PremiumFeatures — Contains information about features, available to Premium users
type PremiumFeatures struct {
	Features []*PremiumFeature `json:"features"` // The list of available features
	Limits []*PremiumLimit `json:"limits"` // The list of limits, increased for Premium users
	PaymentLink *InternalLinkType `json:"payment_link"` // An internal link to be opened to pay for Telegram Premium if store payment isn't possible; may be null if direct payment isn't available
}

func (t *PremiumFeatures) GetType() string { return "premiumFeatures" }

// BusinessFeatures — Contains information about features, available to Business user accounts @features The list of available business features
type BusinessFeatures struct {
	Features []*BusinessFeature `json:"features"`
}

func (t *BusinessFeatures) GetType() string { return "businessFeatures" }

// PremiumSource — Describes a source from which the Premium features screen is opened
type PremiumSource struct {
}

func (t *PremiumSource) GetType() string { return "PremiumSource" }

// PremiumSourceLimitExceeded — A limit was exceeded @limit_type Type of the exceeded limit
type PremiumSourceLimitExceeded struct {
	LimitType *PremiumLimitType `json:"limit_type"`
}

func (t *PremiumSourceLimitExceeded) GetType() string { return "premiumSourceLimitExceeded" }

// PremiumSourceFeature — A user tried to use a Premium feature @feature The used feature
type PremiumSourceFeature struct {
	Feature *PremiumFeature `json:"feature"`
}

func (t *PremiumSourceFeature) GetType() string { return "premiumSourceFeature" }

// PremiumSourceBusinessFeature — A user tried to use a Business feature @feature The used feature; pass null if none specific feature was used
type PremiumSourceBusinessFeature struct {
	Feature *BusinessFeature `json:"feature"`
}

func (t *PremiumSourceBusinessFeature) GetType() string { return "premiumSourceBusinessFeature" }

// PremiumSourceStoryFeature — A user tried to use a Premium story feature @feature The used feature
type PremiumSourceStoryFeature struct {
	Feature *PremiumStoryFeature `json:"feature"`
}

func (t *PremiumSourceStoryFeature) GetType() string { return "premiumSourceStoryFeature" }

// PremiumSourceLink — A user opened an internal link of the type internalLinkTypePremiumFeaturesPage @referrer The referrer from the link
type PremiumSourceLink struct {
	Referrer string `json:"referrer"`
}

func (t *PremiumSourceLink) GetType() string { return "premiumSourceLink" }

// PremiumSourceSettings — A user opened the Premium features screen from settings
type PremiumSourceSettings struct {
}

func (t *PremiumSourceSettings) GetType() string { return "premiumSourceSettings" }

// PremiumFeaturePromotionAnimation — Describes a promotion animation for a Premium feature @feature Premium feature @animation Promotion animation for the feature
type PremiumFeaturePromotionAnimation struct {
	Feature *PremiumFeature `json:"feature"`
	Animation *Animation `json:"animation"`
}

func (t *PremiumFeaturePromotionAnimation) GetType() string { return "premiumFeaturePromotionAnimation" }

// BusinessFeaturePromotionAnimation — Describes a promotion animation for a Business feature @feature Business feature @animation Promotion animation for the feature
type BusinessFeaturePromotionAnimation struct {
	Feature *BusinessFeature `json:"feature"`
	Animation *Animation `json:"animation"`
}

func (t *BusinessFeaturePromotionAnimation) GetType() string { return "businessFeaturePromotionAnimation" }

// PremiumState — Contains state of Telegram Premium subscription and promotion videos for Premium features
type PremiumState struct {
	State *FormattedText `json:"state"` // Text description of the state of the current Premium subscription; may be empty if the current user has no Telegram Premium subscription
	PaymentOptions []*PremiumStatePaymentOption `json:"payment_options"` // The list of available options for buying Telegram Premium
	Animations []*PremiumFeaturePromotionAnimation `json:"animations"` // The list of available promotion animations for Premium features
	BusinessAnimations []*BusinessFeaturePromotionAnimation `json:"business_animations"` // The list of available promotion animations for Business features
}

func (t *PremiumState) GetType() string { return "premiumState" }

// StorePaymentPurpose — Describes a purpose of an in-store payment
type StorePaymentPurpose struct {
}

func (t *StorePaymentPurpose) GetType() string { return "StorePaymentPurpose" }

// StorePaymentPurposePremiumSubscription — The user subscribing to Telegram Premium @is_restore Pass true if this is a restore of a Telegram Premium purchase; only for App Store @is_upgrade Pass true if this is an upgrade from a monthly subscription to early subscription; only for App Store
type StorePaymentPurposePremiumSubscription struct {
	IsRestore bool `json:"is_restore"`
	IsUpgrade bool `json:"is_upgrade"`
}

func (t *StorePaymentPurposePremiumSubscription) GetType() string { return "storePaymentPurposePremiumSubscription" }

// StorePaymentPurposePremiumGift — The user gifting Telegram Premium to another user
type StorePaymentPurposePremiumGift struct {
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	UserID int64 `json:"user_id"` // Identifiers of the user which will receive Telegram Premium
	Text *FormattedText `json:"text"` // Text to show along with the gift codes; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed
}

func (t *StorePaymentPurposePremiumGift) GetType() string { return "storePaymentPurposePremiumGift" }

// StorePaymentPurposePremiumGiftCodes — The user boosting a chat by creating Telegram Premium gift codes for other users
type StorePaymentPurposePremiumGiftCodes struct {
	BoostedChatID int64 `json:"boosted_chat_id"` // Identifier of the supergroup or channel chat, which will be automatically boosted by the users for duration of the Premium subscription and which is administered by the user
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	UserIDs []int64 `json:"user_ids"` // Identifiers of the users which can activate the gift codes
	Text *FormattedText `json:"text"` // Text to show along with the gift codes; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed
}

func (t *StorePaymentPurposePremiumGiftCodes) GetType() string { return "storePaymentPurposePremiumGiftCodes" }

// StorePaymentPurposePremiumGiveaway — The user creating a Telegram Premium giveaway
type StorePaymentPurposePremiumGiveaway struct {
	Parameters *GiveawayParameters `json:"parameters"` // Giveaway parameters
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
}

func (t *StorePaymentPurposePremiumGiveaway) GetType() string { return "storePaymentPurposePremiumGiveaway" }

// StorePaymentPurposeStarGiveaway — The user creating a Telegram Star giveaway
type StorePaymentPurposeStarGiveaway struct {
	Parameters *GiveawayParameters `json:"parameters"` // Giveaway parameters
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	WinnerCount int32 `json:"winner_count"` // The number of users to receive Telegram Stars
	StarCount int64 `json:"star_count"` // The number of Telegram Stars to be distributed through the giveaway
}

func (t *StorePaymentPurposeStarGiveaway) GetType() string { return "storePaymentPurposeStarGiveaway" }

// StorePaymentPurposeStars — The user buying Telegram Stars
type StorePaymentPurposeStars struct {
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	StarCount int64 `json:"star_count"` // Number of bought Telegram Stars
	ChatID int64 `json:"chat_id"` // Identifier of the chat that is supposed to receive the Telegram Stars; pass 0 if none
}

func (t *StorePaymentPurposeStars) GetType() string { return "storePaymentPurposeStars" }

// StorePaymentPurposeGiftedStars — The user buying Telegram Stars for other users
type StorePaymentPurposeGiftedStars struct {
	UserID int64 `json:"user_id"` // Identifier of the user to which Telegram Stars are gifted
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	StarCount int64 `json:"star_count"` // Number of bought Telegram Stars
}

func (t *StorePaymentPurposeGiftedStars) GetType() string { return "storePaymentPurposeGiftedStars" }

// StoreTransaction — Describes an in-store transaction
type StoreTransaction struct {
}

func (t *StoreTransaction) GetType() string { return "StoreTransaction" }

// StoreTransactionAppStore — A purchase through App Store @receipt App Store receipt
type StoreTransactionAppStore struct {
	Receipt []byte `json:"receipt"`
}

func (t *StoreTransactionAppStore) GetType() string { return "storeTransactionAppStore" }

// StoreTransactionGooglePlay — A purchase through Google Play
type StoreTransactionGooglePlay struct {
	PackageName string `json:"package_name"` // Application package name
	StoreProductID string `json:"store_product_id"` // Identifier of the purchased store product
	PurchaseToken string `json:"purchase_token"` // Google Play purchase token
}

func (t *StoreTransactionGooglePlay) GetType() string { return "storeTransactionGooglePlay" }

// TelegramPaymentPurpose — Describes a purpose of a payment toward Telegram
type TelegramPaymentPurpose struct {
}

func (t *TelegramPaymentPurpose) GetType() string { return "TelegramPaymentPurpose" }

// TelegramPaymentPurposePremiumGift — The user gifting Telegram Premium to another user
type TelegramPaymentPurposePremiumGift struct {
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency, or "XTR" for payments in Telegram Stars
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	UserID int64 `json:"user_id"` // Identifier of the user which will receive Telegram Premium
	MonthCount int32 `json:"month_count"` // Number of months the Telegram Premium subscription will be active for the user
	Text *FormattedText `json:"text"` // Text to show to the user receiving Telegram Premium; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed
}

func (t *TelegramPaymentPurposePremiumGift) GetType() string { return "telegramPaymentPurposePremiumGift" }

// TelegramPaymentPurposePremiumGiftCodes — The user boosting a chat by creating Telegram Premium gift codes for other users
type TelegramPaymentPurposePremiumGiftCodes struct {
	BoostedChatID int64 `json:"boosted_chat_id"` // Identifier of the supergroup or channel chat, which will be automatically boosted by the users for duration of the Premium subscription and which is administered by the user
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	UserIDs []int64 `json:"user_ids"` // Identifiers of the users which can activate the gift codes
	MonthCount int32 `json:"month_count"` // Number of months the Telegram Premium subscription will be active for the users
	Text *FormattedText `json:"text"` // Text to show along with the gift codes; 0-getOption("gift_text_length_max") characters. Only Bold, Italic, Underline, Strikethrough, Spoiler, and CustomEmoji entities are allowed
}

func (t *TelegramPaymentPurposePremiumGiftCodes) GetType() string { return "telegramPaymentPurposePremiumGiftCodes" }

// TelegramPaymentPurposePremiumGiveaway — The user creating a Telegram Premium giveaway
type TelegramPaymentPurposePremiumGiveaway struct {
	Parameters *GiveawayParameters `json:"parameters"` // Giveaway parameters
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	WinnerCount int32 `json:"winner_count"` // Number of users which will be able to activate the gift codes
	MonthCount int32 `json:"month_count"` // Number of months the Telegram Premium subscription will be active for the users
}

func (t *TelegramPaymentPurposePremiumGiveaway) GetType() string { return "telegramPaymentPurposePremiumGiveaway" }

// TelegramPaymentPurposeStars — The user buying Telegram Stars
type TelegramPaymentPurposeStars struct {
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	StarCount int64 `json:"star_count"` // Number of bought Telegram Stars
	ChatID int64 `json:"chat_id"` // Identifier of the chat that is supposed to receive the Telegram Stars; pass 0 if none
}

func (t *TelegramPaymentPurposeStars) GetType() string { return "telegramPaymentPurposeStars" }

// TelegramPaymentPurposeGiftedStars — The user buying Telegram Stars for other users
type TelegramPaymentPurposeGiftedStars struct {
	UserID int64 `json:"user_id"` // Identifier of the user to which Telegram Stars are gifted
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	StarCount int64 `json:"star_count"` // Number of bought Telegram Stars
}

func (t *TelegramPaymentPurposeGiftedStars) GetType() string { return "telegramPaymentPurposeGiftedStars" }

// TelegramPaymentPurposeStarGiveaway — The user creating a Telegram Star giveaway
type TelegramPaymentPurposeStarGiveaway struct {
	Parameters *GiveawayParameters `json:"parameters"` // Giveaway parameters
	Currency string `json:"currency"` // ISO 4217 currency code of the payment currency
	Amount int64 `json:"amount"` // Paid amount, in the smallest units of the currency
	WinnerCount int32 `json:"winner_count"` // The number of users to receive Telegram Stars
	StarCount int64 `json:"star_count"` // The number of Telegram Stars to be distributed through the giveaway
}

func (t *TelegramPaymentPurposeStarGiveaway) GetType() string { return "telegramPaymentPurposeStarGiveaway" }

// TelegramPaymentPurposeJoinChat — The user joins a chat and subscribes to regular payments in Telegram Stars @invite_link Invite link to use
type TelegramPaymentPurposeJoinChat struct {
	InviteLink string `json:"invite_link"`
}

func (t *TelegramPaymentPurposeJoinChat) GetType() string { return "telegramPaymentPurposeJoinChat" }

// DeviceToken — Represents a data needed to subscribe for push notifications through registerDevice method.
type DeviceToken struct {
}

func (t *DeviceToken) GetType() string { return "DeviceToken" }

// DeviceTokenFirebaseCloudMessaging — A token for Firebase Cloud Messaging @token Device registration token; may be empty to deregister a device @encrypt True, if push notifications must be additionally encrypted
type DeviceTokenFirebaseCloudMessaging struct {
	Token string `json:"token"`
	Encrypt bool `json:"encrypt"`
}

func (t *DeviceTokenFirebaseCloudMessaging) GetType() string { return "deviceTokenFirebaseCloudMessaging" }

// DeviceTokenApplePush — A token for Apple Push Notification service @device_token Device token; may be empty to deregister a device @is_app_sandbox True, if App Sandbox is enabled
type DeviceTokenApplePush struct {
	DeviceToken string `json:"device_token"`
	IsAppSandbox bool `json:"is_app_sandbox"`
}

func (t *DeviceTokenApplePush) GetType() string { return "deviceTokenApplePush" }

// DeviceTokenApplePushVoIP — A token for Apple Push Notification service VoIP notifications @device_token Device token; may be empty to deregister a device @is_app_sandbox True, if App Sandbox is enabled @encrypt True, if push notifications must be additionally encrypted
type DeviceTokenApplePushVoIP struct {
	DeviceToken string `json:"device_token"`
	IsAppSandbox bool `json:"is_app_sandbox"`
	Encrypt bool `json:"encrypt"`
}

func (t *DeviceTokenApplePushVoIP) GetType() string { return "deviceTokenApplePushVoIP" }

// DeviceTokenWindowsPush — A token for Windows Push Notification Services @access_token The access token that will be used to send notifications; may be empty to deregister a device
type DeviceTokenWindowsPush struct {
	AccessToken string `json:"access_token"`
}

func (t *DeviceTokenWindowsPush) GetType() string { return "deviceTokenWindowsPush" }

// DeviceTokenMicrosoftPush — A token for Microsoft Push Notification Service @channel_uri Push notification channel URI; may be empty to deregister a device
type DeviceTokenMicrosoftPush struct {
	ChannelUri string `json:"channel_uri"`
}

func (t *DeviceTokenMicrosoftPush) GetType() string { return "deviceTokenMicrosoftPush" }

// DeviceTokenMicrosoftPushVoIP — A token for Microsoft Push Notification Service VoIP channel @channel_uri Push notification channel URI; may be empty to deregister a device
type DeviceTokenMicrosoftPushVoIP struct {
	ChannelUri string `json:"channel_uri"`
}

func (t *DeviceTokenMicrosoftPushVoIP) GetType() string { return "deviceTokenMicrosoftPushVoIP" }

// DeviceTokenWebPush — A token for web Push API
type DeviceTokenWebPush struct {
	Endpoint string `json:"endpoint"` // Absolute URL exposed by the push service where the application server can send push messages; may be empty to deregister a device
	P256dhBase64url string `json:"p256dh_base64url"` // Base64url-encoded P-256 elliptic curve Diffie-Hellman public key
	AuthBase64url string `json:"auth_base64url"` // Base64url-encoded authentication secret
}

func (t *DeviceTokenWebPush) GetType() string { return "deviceTokenWebPush" }

// DeviceTokenSimplePush — A token for Simple Push API for Firefox OS @endpoint Absolute URL exposed by the push service where the application server can send push messages; may be empty to deregister a device
type DeviceTokenSimplePush struct {
	Endpoint string `json:"endpoint"`
}

func (t *DeviceTokenSimplePush) GetType() string { return "deviceTokenSimplePush" }

// DeviceTokenUbuntuPush — A token for Ubuntu Push Client service @token Token; may be empty to deregister a device
type DeviceTokenUbuntuPush struct {
	Token string `json:"token"`
}

func (t *DeviceTokenUbuntuPush) GetType() string { return "deviceTokenUbuntuPush" }

// DeviceTokenBlackBerryPush — A token for BlackBerry Push Service @token Token; may be empty to deregister a device
type DeviceTokenBlackBerryPush struct {
	Token string `json:"token"`
}

func (t *DeviceTokenBlackBerryPush) GetType() string { return "deviceTokenBlackBerryPush" }

// DeviceTokenTizenPush — A token for Tizen Push Service @reg_id Push service registration identifier; may be empty to deregister a device
type DeviceTokenTizenPush struct {
	RegID string `json:"reg_id"`
}

func (t *DeviceTokenTizenPush) GetType() string { return "deviceTokenTizenPush" }

// DeviceTokenHuaweiPush — A token for HUAWEI Push Service @token Device registration token; may be empty to deregister a device @encrypt True, if push notifications must be additionally encrypted
type DeviceTokenHuaweiPush struct {
	Token string `json:"token"`
	Encrypt bool `json:"encrypt"`
}

func (t *DeviceTokenHuaweiPush) GetType() string { return "deviceTokenHuaweiPush" }

// PushReceiverID — Contains a globally unique push receiver identifier, which can be used to identify which account has received a push notification @id The globally unique identifier of push notification subscription
type PushReceiverID struct {
	ID JSONInt64 `json:"id"`
}

func (t *PushReceiverID) GetType() string { return "pushReceiverId" }

// BackgroundFill — Describes a fill of a background
type BackgroundFill struct {
}

func (t *BackgroundFill) GetType() string { return "BackgroundFill" }

// BackgroundFillSolid — Describes a solid fill of a background @color A color of the background in the RGB format
type BackgroundFillSolid struct {
	Color int32 `json:"color"`
}

func (t *BackgroundFillSolid) GetType() string { return "backgroundFillSolid" }

// BackgroundFillGradient — Describes a gradient fill of a background
type BackgroundFillGradient struct {
	TopColor int32 `json:"top_color"` // A top color of the background in the RGB format
	BottomColor int32 `json:"bottom_color"` // A bottom color of the background in the RGB format
	RotationAngle int32 `json:"rotation_angle"` // Clockwise rotation angle of the gradient, in degrees; 0-359. Must always be divisible by 45
}

func (t *BackgroundFillGradient) GetType() string { return "backgroundFillGradient" }

// BackgroundFillFreeformGradient — Describes a freeform gradient fill of a background @colors A list of 3 or 4 colors of the freeform gradient in the RGB format
type BackgroundFillFreeformGradient struct {
	Colors []int32 `json:"colors"`
}

func (t *BackgroundFillFreeformGradient) GetType() string { return "backgroundFillFreeformGradient" }

// BackgroundType — Describes the type of background
type BackgroundType struct {
}

func (t *BackgroundType) GetType() string { return "BackgroundType" }

// BackgroundTypeWallpaper — A wallpaper in JPEG format
type BackgroundTypeWallpaper struct {
	IsBlurred bool `json:"is_blurred"` // True, if the wallpaper must be downscaled to fit in 450x450 square and then box-blurred with radius 12
	IsMoving bool `json:"is_moving"` // True, if the background needs to be slightly moved when device is tilted
}

func (t *BackgroundTypeWallpaper) GetType() string { return "backgroundTypeWallpaper" }

// BackgroundTypePattern — A PNG or TGV (gzipped subset of SVG with MIME type "application/x-tgwallpattern") pattern to be combined with the background fill chosen by the user
type BackgroundTypePattern struct {
	Fill *BackgroundFill `json:"fill"` // Fill of the background
	Intensity int32 `json:"intensity"` // Intensity of the pattern when it is shown above the filled background; 0-100
	IsInverted bool `json:"is_inverted"` // True, if the background fill must be applied only to the pattern itself. All other pixels are black in this case. For dark themes only
	IsMoving bool `json:"is_moving"` // True, if the background needs to be slightly moved when device is tilted
}

func (t *BackgroundTypePattern) GetType() string { return "backgroundTypePattern" }

// BackgroundTypeFill — A filled background @fill The background fill
type BackgroundTypeFill struct {
	Fill *BackgroundFill `json:"fill"`
}

func (t *BackgroundTypeFill) GetType() string { return "backgroundTypeFill" }

// BackgroundTypeChatTheme — A background from a chat theme based on an emoji; can be used only as a chat background in channels @theme_name Name of the emoji chat theme
type BackgroundTypeChatTheme struct {
	ThemeName string `json:"theme_name"`
}

func (t *BackgroundTypeChatTheme) GetType() string { return "backgroundTypeChatTheme" }

// InputBackground — Contains information about background to set
type InputBackground struct {
}

func (t *InputBackground) GetType() string { return "InputBackground" }

// InputBackgroundLocal — A background from a local file
type InputBackgroundLocal struct {
	Background *InputFile `json:"background"` // Background file to use. Only inputFileLocal and inputFileGenerated are supported. The file must be in JPEG format for wallpapers and in PNG format for patterns
}

func (t *InputBackgroundLocal) GetType() string { return "inputBackgroundLocal" }

// InputBackgroundRemote — A background from the server @background_id The background identifier
type InputBackgroundRemote struct {
	BackgroundID JSONInt64 `json:"background_id"`
}

func (t *InputBackgroundRemote) GetType() string { return "inputBackgroundRemote" }

// InputBackgroundPrevious — A background previously set in the chat; for chat backgrounds only @message_id Identifier of the message with the background
type InputBackgroundPrevious struct {
	MessageID int64 `json:"message_id"`
}

func (t *InputBackgroundPrevious) GetType() string { return "inputBackgroundPrevious" }

// EmojiChatTheme — Describes a chat theme based on an emoji
type EmojiChatTheme struct {
	Name string `json:"name"` // Theme name
	LightSettings *ThemeSettings `json:"light_settings"` // Theme settings for a light chat theme
	DarkSettings *ThemeSettings `json:"dark_settings"` // Theme settings for a dark chat theme
}

func (t *EmojiChatTheme) GetType() string { return "emojiChatTheme" }

// GiftChatTheme — Describes a chat theme based on an upgraded gift
type GiftChatTheme struct {
	Gift *UpgradedGift `json:"gift"` // The gift
	LightSettings *ThemeSettings `json:"light_settings"` // Theme settings for a light chat theme
	DarkSettings *ThemeSettings `json:"dark_settings"` // Theme settings for a dark chat theme
}

func (t *GiftChatTheme) GetType() string { return "giftChatTheme" }

// GiftChatThemes — Contains a list of chat themes based on upgraded gifts
type GiftChatThemes struct {
	Themes []*GiftChatTheme `json:"themes"` // A list of chat themes
	NextOffset string `json:"next_offset"` // The offset for the next request. If empty, then there are no more results
}

func (t *GiftChatThemes) GetType() string { return "giftChatThemes" }

// ChatTheme — Describes a chat theme
type ChatTheme struct {
}

func (t *ChatTheme) GetType() string { return "ChatTheme" }

// ChatThemeEmoji — A chat theme based on an emoji @name Name of the theme; full theme description is received through updateEmojiChatThemes
type ChatThemeEmoji struct {
	Name string `json:"name"`
}

func (t *ChatThemeEmoji) GetType() string { return "chatThemeEmoji" }

// ChatThemeGift — A chat theme based on an upgraded gift @gift_theme The chat theme
type ChatThemeGift struct {
	GiftTheme *GiftChatTheme `json:"gift_theme"`
}

func (t *ChatThemeGift) GetType() string { return "chatThemeGift" }

// InputChatTheme — Describes a chat theme to set
type InputChatTheme struct {
}

func (t *InputChatTheme) GetType() string { return "InputChatTheme" }

// InputChatThemeEmoji — A theme based on an emoji @name Name of the theme
type InputChatThemeEmoji struct {
	Name string `json:"name"`
}

func (t *InputChatThemeEmoji) GetType() string { return "inputChatThemeEmoji" }

// InputChatThemeGift — A theme based on an upgraded gift @name Name of the upgraded gift. A gift can be used only in one chat in a time.
type InputChatThemeGift struct {
	Name string `json:"name"`
}

func (t *InputChatThemeGift) GetType() string { return "inputChatThemeGift" }

// TimeZone — Describes a time zone
type TimeZone struct {
	ID string `json:"id"` // Unique time zone identifier
	Name string `json:"name"` // Time zone name
	UtcTimeOffset int32 `json:"utc_time_offset"` // Current UTC time offset for the time zone
}

func (t *TimeZone) GetType() string { return "timeZone" }

// TimeZones — Contains a list of time zones @time_zones A list of time zones
type TimeZones struct {
	TimeZones []*TimeZone `json:"time_zones"`
}

func (t *TimeZones) GetType() string { return "timeZones" }

// Hashtags — Contains a list of hashtags @hashtags A list of hashtags
type Hashtags struct {
	Hashtags []string `json:"hashtags"`
}

func (t *Hashtags) GetType() string { return "hashtags" }

// CanPostStoryResult — Represents result of checking whether the current user can post a story on behalf of the specific chat
type CanPostStoryResult struct {
}

func (t *CanPostStoryResult) GetType() string { return "CanPostStoryResult" }

// CanPostStoryResultOk — A story can be sent @story_count Number of stories that can be posted by the user
type CanPostStoryResultOk struct {
	StoryCount int32 `json:"story_count"`
}

func (t *CanPostStoryResultOk) GetType() string { return "canPostStoryResultOk" }

// CanPostStoryResultPremiumNeeded — The user must subscribe to Telegram Premium to be able to post stories
type CanPostStoryResultPremiumNeeded struct {
}

func (t *CanPostStoryResultPremiumNeeded) GetType() string { return "canPostStoryResultPremiumNeeded" }

// CanPostStoryResultBoostNeeded — The chat must be boosted first by Telegram Premium subscribers to post more stories. Call getChatBoostStatus to get current boost status of the chat
type CanPostStoryResultBoostNeeded struct {
}

func (t *CanPostStoryResultBoostNeeded) GetType() string { return "canPostStoryResultBoostNeeded" }

// CanPostStoryResultActiveStoryLimitExceeded — The limit for the number of active stories exceeded. The user can buy Telegram Premium, delete an active story, or wait for the oldest story to expire
type CanPostStoryResultActiveStoryLimitExceeded struct {
}

func (t *CanPostStoryResultActiveStoryLimitExceeded) GetType() string { return "canPostStoryResultActiveStoryLimitExceeded" }

// CanPostStoryResultWeeklyLimitExceeded — The weekly limit for the number of posted stories exceeded. The user needs to buy Telegram Premium or wait specified time @retry_after Time left before the user can post the next story, in seconds
type CanPostStoryResultWeeklyLimitExceeded struct {
	RetryAfter int32 `json:"retry_after"`
}

func (t *CanPostStoryResultWeeklyLimitExceeded) GetType() string { return "canPostStoryResultWeeklyLimitExceeded" }

// CanPostStoryResultMonthlyLimitExceeded — The monthly limit for the number of posted stories exceeded. The user needs to buy Telegram Premium or wait specified time @retry_after Time left before the user can post the next story, in seconds
type CanPostStoryResultMonthlyLimitExceeded struct {
	RetryAfter int32 `json:"retry_after"`
}

func (t *CanPostStoryResultMonthlyLimitExceeded) GetType() string { return "canPostStoryResultMonthlyLimitExceeded" }

// CanPostStoryResultLiveStoryIsActive — The user or the chat has an active live story. The live story must be deleted first @story_id Identifier of the active live story
type CanPostStoryResultLiveStoryIsActive struct {
	StoryID int32 `json:"story_id"`
}

func (t *CanPostStoryResultLiveStoryIsActive) GetType() string { return "canPostStoryResultLiveStoryIsActive" }

// StartLiveStoryResult — Represents result of starting a live story
type StartLiveStoryResult struct {
}

func (t *StartLiveStoryResult) GetType() string { return "StartLiveStoryResult" }

// StartLiveStoryResultOk — The live story was successfully posted @story The live story
type StartLiveStoryResultOk struct {
	Story *Story `json:"story"`
}

func (t *StartLiveStoryResultOk) GetType() string { return "startLiveStoryResultOk" }

// StartLiveStoryResultFail — The live story failed to post with an error to be handled @error_type Type of the error; other error types may be returned as regular errors
type StartLiveStoryResultFail struct {
	ErrorType *CanPostStoryResult `json:"error_type"`
}

func (t *StartLiveStoryResultFail) GetType() string { return "startLiveStoryResultFail" }

// CanTransferOwnershipResult — Represents result of checking whether the current session can be used to transfer a chat ownership to another user
type CanTransferOwnershipResult struct {
}

func (t *CanTransferOwnershipResult) GetType() string { return "CanTransferOwnershipResult" }

// CanTransferOwnershipResultOk — The session can be used
type CanTransferOwnershipResultOk struct {
}

func (t *CanTransferOwnershipResultOk) GetType() string { return "canTransferOwnershipResultOk" }

// CanTransferOwnershipResultPasswordNeeded — The 2-step verification needs to be enabled first
type CanTransferOwnershipResultPasswordNeeded struct {
}

func (t *CanTransferOwnershipResultPasswordNeeded) GetType() string { return "canTransferOwnershipResultPasswordNeeded" }

// CanTransferOwnershipResultPasswordTooFresh — The 2-step verification was enabled recently, user needs to wait @retry_after Time left before the session can be used to transfer ownership of a chat, in seconds
type CanTransferOwnershipResultPasswordTooFresh struct {
	RetryAfter int32 `json:"retry_after"`
}

func (t *CanTransferOwnershipResultPasswordTooFresh) GetType() string { return "canTransferOwnershipResultPasswordTooFresh" }

// CanTransferOwnershipResultSessionTooFresh — The session was created recently, user needs to wait @retry_after Time left before the session can be used to transfer ownership of a chat, in seconds
type CanTransferOwnershipResultSessionTooFresh struct {
	RetryAfter int32 `json:"retry_after"`
}

func (t *CanTransferOwnershipResultSessionTooFresh) GetType() string { return "canTransferOwnershipResultSessionTooFresh" }

// CheckChatUsernameResult — Represents result of checking whether a username can be set for a chat
type CheckChatUsernameResult struct {
}

func (t *CheckChatUsernameResult) GetType() string { return "CheckChatUsernameResult" }

// CheckChatUsernameResultOk — The username can be set
type CheckChatUsernameResultOk struct {
}

func (t *CheckChatUsernameResultOk) GetType() string { return "checkChatUsernameResultOk" }

// CheckChatUsernameResultUsernameInvalid — The username is invalid
type CheckChatUsernameResultUsernameInvalid struct {
}

func (t *CheckChatUsernameResultUsernameInvalid) GetType() string { return "checkChatUsernameResultUsernameInvalid" }

// CheckChatUsernameResultUsernameOccupied — The username is occupied
type CheckChatUsernameResultUsernameOccupied struct {
}

func (t *CheckChatUsernameResultUsernameOccupied) GetType() string { return "checkChatUsernameResultUsernameOccupied" }

// CheckChatUsernameResultUsernamePurchasable — The username can be purchased at https://fragment.com. Information about the username can be received using getCollectibleItemInfo
type CheckChatUsernameResultUsernamePurchasable struct {
}

func (t *CheckChatUsernameResultUsernamePurchasable) GetType() string { return "checkChatUsernameResultUsernamePurchasable" }

// CheckChatUsernameResultPublicChatsTooMany — The user has too many chats with username, one of them must be made private first
type CheckChatUsernameResultPublicChatsTooMany struct {
}

func (t *CheckChatUsernameResultPublicChatsTooMany) GetType() string { return "checkChatUsernameResultPublicChatsTooMany" }

// CheckChatUsernameResultPublicGroupsUnavailable — The user can't be a member of a public supergroup
type CheckChatUsernameResultPublicGroupsUnavailable struct {
}

func (t *CheckChatUsernameResultPublicGroupsUnavailable) GetType() string { return "checkChatUsernameResultPublicGroupsUnavailable" }

// CheckStickerSetNameResult — Represents result of checking whether a name can be used for a new sticker set
type CheckStickerSetNameResult struct {
}

func (t *CheckStickerSetNameResult) GetType() string { return "CheckStickerSetNameResult" }

// CheckStickerSetNameResultOk — The name can be set
type CheckStickerSetNameResultOk struct {
}

func (t *CheckStickerSetNameResultOk) GetType() string { return "checkStickerSetNameResultOk" }

// CheckStickerSetNameResultNameInvalid — The name is invalid
type CheckStickerSetNameResultNameInvalid struct {
}

func (t *CheckStickerSetNameResultNameInvalid) GetType() string { return "checkStickerSetNameResultNameInvalid" }

// CheckStickerSetNameResultNameOccupied — The name is occupied
type CheckStickerSetNameResultNameOccupied struct {
}

func (t *CheckStickerSetNameResultNameOccupied) GetType() string { return "checkStickerSetNameResultNameOccupied" }

// ResetPasswordResult — Represents result of 2-step verification password reset
type ResetPasswordResult struct {
}

func (t *ResetPasswordResult) GetType() string { return "ResetPasswordResult" }

// ResetPasswordResultOk — The password was reset
type ResetPasswordResultOk struct {
}

func (t *ResetPasswordResultOk) GetType() string { return "resetPasswordResultOk" }

// ResetPasswordResultPending — The password reset request is pending @pending_reset_date Point in time (Unix timestamp) after which the password can be reset immediately using resetPassword
type ResetPasswordResultPending struct {
	PendingResetDate int32 `json:"pending_reset_date"`
}

func (t *ResetPasswordResultPending) GetType() string { return "resetPasswordResultPending" }

// ResetPasswordResultDeclined — The password reset request was declined @retry_date Point in time (Unix timestamp) when the password reset can be retried
type ResetPasswordResultDeclined struct {
	RetryDate int32 `json:"retry_date"`
}

func (t *ResetPasswordResultDeclined) GetType() string { return "resetPasswordResultDeclined" }

// MessageFileType — Contains information about a file with messages exported from another app
type MessageFileType struct {
}

func (t *MessageFileType) GetType() string { return "MessageFileType" }

// MessageFileTypePrivate — The messages were exported from a private chat @name Name of the other party; may be empty if unrecognized
type MessageFileTypePrivate struct {
	Name string `json:"name"`
}

func (t *MessageFileTypePrivate) GetType() string { return "messageFileTypePrivate" }

